import { connectionExplorer } from './connection-charts';

const base = import.meta.env.BASE_URL;
const record = 'https://github.com/stephenlewandowski/western-basin-worldbuilding/blob/main/reports/lake_erie_coast_context_2026-10-04.md';

/** A dated regional reading, separate from the frozen energy baseline and artwork. */
export function coastReading(): string {
  return `<section class="section-shell coast-reading" id="coast-field-guide">
    <div class="section-head"><div><p class="eyebrow accent">BEYOND THE TERRACE</p><h2>Power, passage<br>and <em>pleasure.</em></h2></div><p>A cooling tower beyond the marsh. Rescue boats at Marblehead. Fishing crews before dawn and a coaster climbing above Sandusky Bay. This coast has more than one reason to keep the lights on.</p></div>
    <nav class="coast-jumps" aria-label="Read the coast"><a href="#nuclear-coast">Nuclear power &amp; compute</a><a href="#working-security">Working security</a><a href="#living-lake">Fish, refuges &amp; migration</a><a href="#coast-after-hours">Cedar Point &amp; after hours</a></nav>
    <p class="coast-grounding">Present-day anchors checked 4 October 2026; future passages below are imagined alternatives. The existing illustration shows a composite service terrace. The wider coast reaches from Toledo and Oak Harbor through Port Clinton and Marblehead toward Sandusky, with an inland aviation connection at Toledo Express.</p>

    <article class="coast-chapter" id="nuclear-coast">
      <p class="eyebrow">POWER / A LONG MEMORY</p><h3>Davis-Besse, and what comes after.</h3>
      <p>Davis-Besse stands near Oak Harbor on the Lake Erie shore. Its operating fission reactor has a current NRC license through 22 April 2037. That date leaves the 2075 coast open to more than one future. <a href="https://www.nrc.gov/facilities-safety/facility-finder/reactors/davi">NRC plant record ↗</a></p>
      <p>The compute connection already has a commercial basis: Vistra’s January 2026 agreement with Meta includes Davis-Besse. The operator says electricity continues into the shared regional grid; the agreement does not establish a private supply line to a nearby data center. <a href="https://investor.vistracorp.com/2026-01-09-Vistra-and-Meta-Announce-Agreements-to-Support-Nuclear-Plants-in-PJM-and-Add-New-Nuclear-Generation-to-the-Grid">Operator announcement ↗</a></p>
      <div class="coast-alternatives" aria-label="Three imagined nuclear futures">
        <details open><summary>A successor fission coast</summary><p>By 2075, replacement fission generation might share a grid corridor with compute halls and other users. New reactors, including possible modular designs, need their own siting, licensing and fuel arrangements. The old unit’s retirement and records remain part of the landscape.</p></details>
        <details><summary>Fusion joins the coast</summary><p>Imagine a new fusion installation joining the regional grid after the technology becomes dependable. It is a successor or addition, not a conversion of Davis-Besse’s reactor. DOE’s pilot-plant roadmap is an ambition, not evidence of a local commercial plant. Cooling, component replacement and fuel handling still take work.</p><p>Deuterium–tritium fusion also brings tritium control and activated materials. A fusion coast inherits the earlier fission waste obligations. <a href="https://www.energy.gov/fusion/office-fusion">DOE fusion roadmap ↗</a> · <a href="https://www.nrc.gov/materials/fusion/faq">NRC fusion materials ↗</a></p></details>
        <details><summary>Custody outlasts generation</summary><p>Another 2075 coast keeps the old landmark after its last electrical output. A stewardship campus preserves records, inspects stored fuel and prepares lawful transfers when a destination is available. Workers change; the obligation continues. The grid draws on a different mix.</p></details>
      </div>
      <details class="coast-long-read"><summary>Waste solutions are a chain of responsibilities.</summary><p>Spent fission fuel moves from cooling pools to licensed storage, with transport and eventual disposal requiring separate decisions. Dry casks provide interim custody; a durable solution also needs an authorized destination, community participation and records that survive changes of operator.</p><p>Future fuel recycling could recover useful material, but it leaves radioactive waste needing disposition. Neither recycling nor fusion makes inherited spent fuel disappear. No Lake Erie repository or present Davis-Besse recycling program is proposed here. <a href="https://www.nrc.gov/facilities-safety/high-level-waste">NRC waste overview ↗</a> · <a href="https://www.energy.gov/ne/advanced-nuclear-fuel-recycling-program">DOE recycling development ↗</a></p></details>
      <div class="coast-principle"><p class="eyebrow">ONE SCIENTIFIC PRINCIPLE</p><h4>Useful computation still becomes heat.</h4><p>A hypothetical facility drawing <strong>10 MW</strong> for <strong>24 hours</strong> uses <strong>240 MWh</strong>. Most of that electricity eventually becomes heat. This is a unit example, not a measured local data center or a reactor allocation.</p><p>Davis-Besse already uses a cooling tower with Lake Erie makeup water. Future plant and compute cooling need their own water and heat budgets. Reusing heat depends on its temperature, distance and a customer who needs it; a pipe drawn toward a greenhouse does not guarantee useful recovery. <a href="${record}#energy-water-and-heat">Sources and limits ↗</a></p></div>
      ${connectionExplorer('coast', 'coast-energy')}
    </article>

    <article class="coast-chapter" id="working-security">
      <p class="eyebrow">SECURITY / PUBLIC WORK, DISTINCT BOUNDARIES</p><h3>Rescue sheds, training grounds, an inland airfield.</h3>
      <p><a href="https://www.ong.ohio.gov/about-us/facilities/camp-perry/index.html">Camp Perry ↗</a> brings military training and the National Matches near Port Clinton. <a href="https://www.atlanticarea.uscg.mil/Our-Organization/Great-Lakes-District/Units/Sector-Detroit/Units/Marblehead/">Coast Guard Station Marblehead ↗</a> connects rescue, boating safety, ice rescue, environmental response and maritime security. The <a href="https://www.180fw.ang.af.mil/About-Us/">180th Fighter Wing ↗</a> at Toledo Express provides an air-defense and civil-support connection inland, rather than a promise of constant jets above every beach.</p>
      <p><strong>Possible 2075:</strong> a rescue mechanic waits for a replacement pump while a family checks a ferry weather board. Training areas, nuclear custody, public docks and wildlife access have different rules. Civilian environmental survey craft in the lead image remain civilian; future aircraft types and patrol arrangements are undecided.</p>
    </article>

    <article class="coast-chapter" id="living-lake">
      <p class="eyebrow">ECOLOGY / THE COAST’S OTHER CALENDAR</p><h3>Fish at the dock. Warblers in the willows.</h3>
      <p>Walleye and yellow perch support angling, charter trips and fish-dock work; Ohio also has commercial yellow-perch fishing. <a href="https://www.glfc.org/lake-erie-committee.php">Lake Erie fisheries ↗</a> and <a href="https://www.fws.gov/refuge/ottawa">Ottawa National Wildlife Refuge ↗</a> make water, habitat and seasonal work central to the region. <a href="https://dam.assets.ohio.gov/image/upload/ohiodnr.gov/documents/wildlife/wildlife-area-maps/Magee%20Marsh%20Trail%20Map%20Points%20of%20Interest.pdf">Magee Marsh’s boardwalks ↗</a> and migratory birds bring guides, visitors and lodging into the same coastal economy.</p>
      <p><strong>Possible 2075:</strong> marsh water gates, quiet shelters, fish cold stores and seasonal shuttles become as recognizable as compute halls. A bird guide and a cooling-water technician compare the morning’s records. Warm-water discharge, fish habitat and radiological monitoring remain different questions. Nuclear power supplies no automatic ecological improvement.</p>
      <p>Migration can shape work inland too: the fighter wing has documented bird-hazard and habitat assessment at its airfield. Future lighting and maintenance schedules might respond to passage, without turning protected birds into scenery. <a href="https://www.180fw.ang.af.mil/News/Features/Display/Article/1188992/180fw-hosts-bash-team-visit/">Documented airfield connection ↗</a></p>
    </article>

    <article class="coast-chapter" id="coast-after-hours">
      <p class="eyebrow">RECREATION / KEEP THE THRILL, SHOW THE WORK</p><h3>Cedar Point, after the last launch.</h3>
      <p><a href="https://www.sixflags.com/cedarpoint">Cedar Point ↗</a> anchors a different coastal skyline on its Sandusky peninsula: roller coasters, a beach, marinas and resorts. Entertainment is part of the region’s identity, alongside energy, defense and habitat.</p>
      <p><strong>Possible 2075:</strong> imagine repairable launch coasters with replaceable drive assemblies, lake-facing weather shelters and ferry arrivals. Regenerative braking recovers some ride energy; it cannot make the park a net power source. Storm closures, seasonal jobs, bird passage and queue-side shade remain part of a visitor’s day. Continued operation in 2075 is a design choice, not a forecast.</p>
      <aside class="coast-scene"><p class="eyebrow">AN IMAGINED DUSK</p><h4>One more run?</h4><p>A park electrician wants a final coaster run. A refuge worker asks for the lights to fall; the fish dock needs refrigeration. Across the regional network, a compute operator can postpone a flexible batch—but the rescue station’s work cannot wait. The shift ends with a negotiation over who can wait and what has to keep working.</p><p class="coast-scene-note">A scene seed for stories and games, not a claim that these sites share one feeder or control room.</p></aside>
    </article>
    <p class="coast-record-link"><a href="${record}">Dated grounding, geographic scope and scenario sources ↗</a> · <a href="${base}maps/?region=coast">Back to the regional maps ↗</a></p>
  </section>`;
}
