import './style.css';
import { essays, type Essay, type EssayKey } from './content';
import { readingHallScene, mountReadingHallScene } from './reading-hall';
import { insetCallouts } from './inset-callouts';
import { returnVisitScene, mountReturnVisitScene } from './return-visit';
import heroWide from '../../assets/phase17d/hf01/hf01_glass_city_2075_hero_wide.webp';
import maintenanceView from '../../assets/phase17d/hf01/hf01_glass_city_2075_maintenance.webp';
import canopySection from '../../assets/phase17d/hf01/hf01_canopy_old_wall_section_public.svg';
import industryWide from '../../assets/phase17d/hf04/hf04_industrial_metabolism_2075_hero_wide.webp';
import industryMaintenance from '../../assets/phase17d/hf04/hf04_industrial_metabolism_2075_maintenance.webp';
import industrySection from '../../assets/phase17d/hf04/hf04_qualification_cell_section_public.svg';
import bioAgWide from '../../assets/phase17d/hf03/hf03_maumee_bio_ag_2075_hero_wide.webp';
import bioAgMaintenance from '../../assets/phase17d/hf03/hf03_maumee_bio_ag_2075_maintenance.webp';
import bioAgSection from '../../assets/phase17d/hf03/hf03_field_seam_drainage_section_public.svg';
import coastWide from '../../assets/phase17d/hf02/hf02_lake_erie_energy_security_coast_2075_hero_wide.webp';
import coastMaintenance from '../../assets/phase17d/hf02/hf02_lake_erie_energy_security_coast_2075_maintenance.webp';
import coastSection from '../../assets/phase17d/hf02/hf02_service_terrace_recovery_section.svg';
import hallA from '../../assets/phase17d/hf05/hf05_composition_a.webp';
import hallB from '../../assets/phase17d/hf05/hf05_composition_b.webp';
import hallC from '../../assets/phase17d/hf05/hf05_composition_c.webp';
import observedFlow from '../../outputs/model_lab/observations/waterville_daily_flow_2025.svg';
import basinPreview from '../../assets/atlas/region/basin_preview.svg';

const root = document.querySelector<HTMLDivElement>('#app');
if (!root) throw new Error('Atlas root is missing');

const base = import.meta.env.BASE_URL;
const path = (suffix = '') => `${base}${suffix}`;
const repo = 'https://github.com/stephenlewandowski/western-basin-worldbuilding';
const source = (file: string) => `${repo}/blob/main/${file}`;
const page = document.body.dataset.page ?? 'home';

function nav(active: string): string {
  const item = (label: string, href: string, key: string) =>
    `<a href="${path(href)}" ${active === key ? 'aria-current="page"' : ''}>${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to content</a>
    <header class="site-header"><div class="header-inner">
      <a class="brand" href="${path()}"><span class="brand-mark" aria-hidden="true">WB<span>•</span></span><span>WESTERN BASIN<br><strong>ATLAS</strong></span></a>
      <nav class="top-nav" aria-label="Main navigation">
        ${item('Maps', 'maps/', 'maps')}${item('Futurescapes', '#futurescapes', 'atlas')}${item('Studies', '#essays', 'studies')}${item('Stories', '#stories', 'stories')}${item('Methods', 'methods/', 'methods')}${item('Updates', 'updates/', 'updates')}
      </nav>
    </div></header>`;
}

function footer(): string {
  return `<footer class="site-footer"><div class="footer-inner">
    <div><span class="eyebrow">Western Basin Worldbuilding</span><p>An illustrated research and speculative worldbuilding project rooted in Toledo, the Maumee watershed, and western Lake Erie.</p></div>
    <div class="footer-links"><a href="${path('maps/')}">Maps & regions</a><a href="${path('methods/')}">Methods & credits</a><a href="${path()}#model-lab">Model Lab</a><a href="${path()}#stories">Stories</a><a href="${path('roadmap/')}">Roadmap</a><a href="${path('updates/')}">Updates</a><a href="${repo}">Research repository ↗</a><a href="${path('game/')}">Vesper Station game ↗</a></div>
    <p class="footer-bottom">Western Basin Atlas · Real geography first; fictional interpretation second.</p>
  </div></footer>`;
}

function layout(content: string, active: string): string {
  return `${nav(active)}<main id="main">${content}</main>${footer()}`;
}

function card(essay: Essay): string {
  return `<a class="essay-card" href="${path(essay.slug)}">
    <div class="card-image"><img src="${essay.cover}" alt="${essay.coverAlt}" loading="lazy" /></div>
    <div class="card-content"><span class="eyebrow">${essay.number} / ${essay.status}</span><h3>${essay.title}</h3><p>${essay.subtitle}</p><span class="card-link">Explore the study <span aria-hidden="true">↗</span></span></div>
  </a>`;
}

function home(): string {
  const places = [
    { slug: 'glass-city-2075', title: 'Glass City 2075', image: heroWide, alt: 'Toledo-derived street beneath an optical canopy, with a replacement cassette and maintenance crew', text: 'A maintained optical canopy brings replacement work, freight and public passage into an older Toledo-derived street.' },
    { slug: 'maumee-bio-ag-2075', title: 'Maumee Bio-Ag Landscape 2075', image: bioAgWide, alt: 'Open Maumee-derived field beside a cultivation seam, old drainage gate and separate reed wetland', text: 'Open fields meet selective cultivation, machine repair, outside supply and the continuing work of maintaining drainage.' },
    { slug: 'industrial-metabolism-2075', title: 'Industrial Metabolism 2075', image: industryWide, alt: 'Old industrial crane hall with a removable cell, staffed inspection and separate material bays', text: 'An inherited crane hall makes room for replaceable process cells, human qualification and materials that may still leave as residuals.' },
    { slug: 'lake-erie-energy-security-coast-2075', title: 'Lake Erie Energy &amp; Security Coast 2075', image: coastWide, alt: 'Lake Erie service terrace with screened galleries, a dry civilian survey cradle and exposed quay', text: 'Weather-screen work, civilian survey recovery and separate utility spaces share an exposed working coast.' }
  ];
  return layout(`<section class="hero"><div class="hero-inner">
    <div class="hero-copy"><p class="eyebrow accent">WESTERN BASIN ATLAS / ILLUSTRATED FUTURES</p><h1>The future<br>has a <em>watershed.</em></h1><p class="hero-deck">An illustrated, scientifically grounded futures atlas rooted in Toledo, the Maumee watershed and western Lake Erie.</p><div class="hero-actions"><a class="button button-primary" href="${path('maps/')}">Explore the basin <span aria-hidden="true">↗</span></a><a class="text-link" href="${path('atlas/basin-reading-hall/')}#story">Play a Reading Hall encounter <span aria-hidden="true">↗</span></a></div></div>
    <div class="hero-art"><div class="hero-art-frame"><img src="${heroWide}" alt="Illustrated Toledo-derived working street beneath an optical glass canopy, with a replacement cassette and maintenance crew after rain" fetchpriority="high" /><span class="art-label">GLASS CITY 2075</span></div><p class="hero-art-caption">Composite Toledo-derived 2075 scenario and design concept.</p></div>
  </div></section>
  <section id="maps" class="section-shell map-teaser"><div><p class="eyebrow accent">MAPS / WHERE THE FUTURES BEGIN</p><h2>A river basin.<br><em>Many ways in.</em></h2><p>Find Toledo, the upstream river towns and the working coast. Five overlapping regional identities lead into imagined places; real landmarks and earlier research maps keep the ground in view.</p><a class="button button-primary" href="${path('maps/')}">Explore maps & regions ↗</a><p><a class="text-link" href="${path('maps/')}#river-record">Inspect a real day on the Maumee ↗</a></p></div><a href="${path('maps/')}" class="map-teaser-art"><img src="${basinPreview}" alt="Maumee watershed and selected physical waterways from Fort Wayne through Defiance to Toledo and western Lake Erie" loading="lazy" /><span>REAL GEOGRAPHY · REGIONAL CHARACTER · POSSIBLE FUTURES</span></a></section>
  <section id="futurescapes" class="futurescape-section section-shell"><div class="section-label">2075 FUTURESCAPES</div><div class="section-head"><div><h2>Places shaped by<br><em>work and change.</em></h2></div><p>Explore four imagined places through a lead image, a working detail and an explanation of their systems. Each is a scenario and design concept grounded in the region's landscape and dependencies.</p></div><div class="futurescape-cards">${places.map(place => `<article class="futurescape-card futurescape-feature"><a href="${path(`atlas/${place.slug}/`)}"><img src="${place.image}" alt="${place.alt}" loading="lazy" /><span class="eyebrow">SCENARIO AND DESIGN CONCEPT</span><h3>${place.title}</h3><p>${place.text}</p><span class="card-link">Explore the futurescape <span aria-hidden="true">↗</span></span></a></article>`).join('')}</div></section>
  <section id="essays" class="essays-section section-shell"><div class="section-head"><div><div class="section-label">STUDIES</div><h2>Follow the basin's<br>connections.</h2></div><p>Watershed pathways and a real intake structure sit beside imagined farm and industrial arrangements. Each study distinguishes sourced geography, approximate drawings and future concepts. Quantitative diagnostic examples have their own Model Lab below.</p></div><div class="card-grid">${essays.map(card).join('')}</div></section>
  <section id="stories" class="section-shell story-teaser"><div><p class="eyebrow accent">STORIES / A SMALL WORLD TO STEP INTO</p><h2>Before the<br><em>last bus.</em></h2><p>Her daughter wants a picnic. Renata has a water report that leaves their channel out, and five minutes before the bus goes.</p><p>A paper sun, a returned field case and a stubborn wheel make room for an ordinary encounter in Toledo, 2075.</p><a class="button button-primary" href="${path('atlas/basin-reading-hall/')}#story">Play Before the Last Bus <span aria-hidden="true">↗</span></a> <a class="text-link" href="${path('atlas/basin-reading-hall/')}#return-visit">Continue with The Return Visit ↗</a></div><a class="story-teaser-art" href="${path('atlas/basin-reading-hall/')}#story" aria-label="Play the Reading Hall encounter"><img src="${hallA}" alt="People compare records at a timber counter beside the stepped instrument rooms of the Basin Reading Hall" loading="lazy" /><span>THE BASIN READING HALL · INTERACTIVE ENCOUNTERS</span></a></section>
  <section id="model-lab" class="intro-section section-shell"><div class="section-label">MODEL LAB / SYNTHETIC DIAGNOSTICS</div><div class="intro-grid"><h2>Inspect the routing.<br><em>Compare the assumptions.</em></h2><div><p>Model Lab tests water and nutrient accounting on the Maumee watershed's qualified routing network. Three saved examples use synthetic unit pulses to show how unresolved links and explicit assumptions change the ledger.</p><p>These are arithmetic and routing tests, not measured loads, calibrated predictions or evidence of nutrient removal. A read-only explorer lets you inspect accounting areas, traces, case comparisons and source records.</p><p>The <a href="${path('maps/')}#river-record">Waterville observation explorer</a> offers a separate measured river record in the browser. The synthetic-case explorer runs locally in R/Shiny, separately from this website. <a href="${source('src/R/model_lab/explorer/README.md')}">Explorer setup ↗</a> · <a href="${source('data/model_lab/README.md')}">Saved cases and reproducibility ↗</a> · <a href="${path('methods/')}#model-lab-methods">Model limits</a></p></div></div></section>
  <section class="intro-section section-shell"><div class="section-label">HOW THE ATLAS IS BUILT</div><div class="intro-grid"><h2>Start with the place.<br><em>Follow the connections.</em></h2><div><p>Toledo sits where the Maumee River, Lake Erie, agriculture, drinking water, industry, freight, energy, ecology and public institutions meet. Those connections constrain the futures explored here.</p><p>The Atlas combines sourced studies of the basin with clearly marked imagined futures. A convincing illustration does not establish that a proposed technology works.</p><a class="text-link" href="${path('methods/')}">Evidence, uncertainty and Methods <span aria-hidden="true">↗</span></a></div></div></section>
  <section class="status-band"><div class="section-shell status-grid"><div><p class="eyebrow accent">UPDATES / WHAT IS BEING DEVELOPED</p><h2>An Atlas<br>in progress.</h2></div><div><p>The next illustrated place is the Basin Reading Hall: a civic room where people inspect published findings and request clarification. Two interactive encounters let you meet its people; three composition studies show the building around them. Its visual orientation is established, with architectural detail still in development.</p><a class="button button-outline" href="${path('updates/')}">Read the updates <span aria-hidden="true">↗</span></a> <a class="text-link" href="${path('roadmap/')}">Areas of ongoing work <span aria-hidden="true">↗</span></a></div></div></section>`, 'home');
}

function essayView(essay: Essay): string {
  const index = essays.findIndex((item) => item.key === essay.key);
  const next = essays[(index + 1) % essays.length];
  return layout(`<div class="essay-page"><section class="essay-hero section-shell">
    <a class="back-link" href="${path()}#essays">← All studies</a> <a class="map-context-link" href="${path('maps/')}">Locate the regional context ↗</a>
    <div class="essay-header-grid"><div><p class="eyebrow accent">ATLAS STUDY ${essay.number} / ${essay.place.toUpperCase()}</p><h1>${essay.title}</h1><p class="essay-subtitle">${essay.subtitle}</p><div class="status-pill">${essay.status}</div></div><p class="essay-lead">${essay.lead}</p></div>
    </section><div class="section-shell"><figure class="cover-figure"><a href="${essay.cover}" target="_blank" rel="noopener" aria-label="Open the lead figure full size"><img src="${essay.cover}" alt="${essay.coverAlt}" /></a><figcaption>Lead figure · Open image for full size <span aria-hidden="true">↗</span></figcaption></figure></div>
    <section class="section-shell reading-section"><div class="reading-side"><span class="eyebrow">THE READER'S QUESTION</span><h2>${essay.question}</h2></div><div class="prose">${essay.reading.map((paragraph) => `<p>${paragraph}</p>`).join('')}</div></section>
    <section class="section-shell panel-section"><div class="section-head"><div><div class="section-label"><span class="rule-number">${essay.number}</span> VISUAL SEQUENCE</div><h2>Read the panels.</h2></div><p>Click a figure to inspect its labels at full size. The sequence moves from place or form to the relationships that organize it.</p></div>
      <div class="panel-grid">${essay.panels.map((panel) => `<figure class="panel"><a href="${panel.image}" target="_blank" rel="noopener" aria-label="Open ${panel.title} full size"><img src="${panel.image}" alt="${panel.alt}" loading="lazy" /></a><figcaption><strong>${panel.title}</strong><span>${panel.caption}</span></figcaption></figure>`).join('')}</div>
    </section><section class="section-shell boundary-section"><div class="boundary-box"><span class="eyebrow">INTERPRETIVE BOUNDARY</span><p>${essay.boundary}</p></div><div class="source-box"><span class="eyebrow">FOLLOW THE WORK</span><ul>${essay.sources.map(({ label, path: file }) => `<li><a href="${source(file)}">${label} ↗</a></li>`).join('')}</ul><small>Source links open the research repository and its technical records.</small></div></section>
    ${essay.key === 'industry' ? `<section class="section-shell future-related"><p class="eyebrow">FROM STUDY TO FUTURESCAPE</p><h2>Enter the working hall.</h2><p>The <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075 ↗</a> explores a working hall informed by this study of conditional exchange. Its composite architecture is a separate design concept, not a reconstruction of the district diagram.</p></section>` : ''}
    <a class="next-essay" href="${path(next.slug)}"><span class="eyebrow">NEXT STUDY / ${next.number}</span><strong>${next.title} <span aria-hidden="true">↗</span></strong></a>
  </div>`, 'studies');
}

function glassCity(): string {
  return layout(`<div class="future-page">
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a> <a class="map-context-link" href="${path('maps/')}?region=glass">Explore this regional context ↗</a><h1>Glass City<br><em>2075.</em></h1><p class="future-question">What happens when a glassmaking city makes shade, repair, freight, and public passage part of the same maintained roof?</p></section>
    <section class="future-opening"><figure><img src="${heroWide}" alt="Composite Toledo-derived street after rain, beneath a branching translucent optical canopy as workers guide a suspended replacement cassette" fetchpriority="high" /><figcaption>Lead image · Composite Toledo-derived 2075 scenario and design concept.</figcaption></figure></section>
    <div class="section-shell future-context prose"><p>A composite Toledo-derived industrial street has gained a second roofline: patterned optical leaves over older brick and concrete, with walkable service ribs and public space below. One cassette is being replaced while people cross, wait, and move freight nearby.</p><p>The canopy is a speculative architectural form. Its interfaces require energy, labor, access, and agreements; the image does not show a built project or a predicted future.</p></div>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / WORKING DETAIL</p><h2>Repair belongs<br>in the picture.</h2></div><p>A closer, deliberately composed view of the human-guided replacement, its open berth, service access, and old/new material joints.</p></div><figure><a href="${maintenanceView}" target="_blank" rel="noopener" aria-label="Open the working-detail illustration full size"><img src="${maintenanceView}" alt="Workers guide a replaceable glass canopy cassette beside its open attachment berth, above an older brick wall and a cordoned public route" loading="lazy" /></a><figcaption>Working detail · Concept illustration, not an engineered lifting procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / HOW IT WORKS</p><h2>Old wall,<br>new working roof.</h2></div><p>The section separates masonry, attachment, a walkable service rib, glazing, data and electrical paths, and the public route. It shows relationships without measured dimensions or performance.</p></div><figure><a href="${canopySection}" target="_blank" rel="noopener" aria-label="Open the canopy and old-wall section full size"><img src="${canopySection}" alt="Qualitative section showing retained masonry, replaceable optical cassettes, service rib, distinct data and electrical paths, maintenance access, public route, and an unconnected neighbor" loading="lazy" /></a><figcaption>Reading inset · Six numbered groups are described below. Qualitative design concept; no dimensions or performance claims.</figcaption></figure>${insetCallouts('canopy')}</section>
    <section class="section-shell future-boundary"><div class="boundary-box"><h2>What is grounded / What is speculative</h2><p>Grounded in current Toledo and Western Basin industrial, settlement, climate and infrastructure context, the scene asks how public passage and maintenance might share an inherited street.</p><p>Invented for this 2075 scenario are the canopy, glass interfaces, connections, street arrangement and depicted workers. Energy, labor, access and property agreements remain necessary; the neighboring structure is unconnected. No real parcel, surveyed sightline or measured geometry is shown. Structural suitability, optical or cooling performance, health benefit, bird safety, affordability and wider adoption remain unresolved.</p></div><div class="source-box"><p class="eyebrow">METHODS / TECHNICAL RECORD</p><ul><li><a href="${path('methods/')}">Methods and sources ↗</a></li><li><a href="${source('reports/phase17d_hf01_final_production_notes.md')}">Image provenance and technical record ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><h2>Related studies and Methods</h2><p><a href="${path('methods/')}">Methods</a> explains the distinction between sourced context and invented architecture. <a href="${path()}#essays">Explore the studies</a> for the basin's wider systems; these do not validate the canopy's proposed technology.</p><p><a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075</a> explores another use of inherited industrial structure.</p></section>
  </div>`, 'atlas');
}

function industrialMetabolism(): string {
  return layout(`<div class="future-page">
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a> <a class="map-context-link" href="${path('maps/')}?region=industry">Explore this regional context ↗</a><h1 class="future-long-title">Industrial<br><em>Metabolism 2075.</em></h1><p class="future-question">What would industry look like if the work between an available residual and a usable input occupied the architecture?</p></section>
    <section class="future-opening"><figure><img src="${industryWide}" alt="Composite Toledo-derived old brick crane hall with a suspended replaceable industrial cell, tall modular frontage, workers, separate material bays, and open freight yard" fetchpriority="high" /><figcaption>Lead image · Composite Toledo-derived 2075 scenario and design concept.</figcaption></figure></section>
    <div class="section-shell future-context prose"><p>A composite Toledo-derived crane hall holds a tall, replaceable exchange frontage. An old crane lowers one opaque cell toward an empty berth. Protected qualification, separate stores, a staffed handoff, and external rail freight share the hall without becoming one automatic process.</p><p>The scene proposes a physical place for checking, repair, rejection, and outside dependencies. It does not assign a new process to a real plant or assert that any material exchange succeeds.</p></div>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / WORKING DETAIL</p><h2>Replacement has<br>an open edge.</h2></div><p>A separately composed close view brings a worn coupling, empty berth, human-guided lift, protected inspection window, and held material into focus.</p></div><figure><a href="${industryMaintenance}" target="_blank" rel="noopener" aria-label="Open the Industrial Metabolism working-detail illustration full size"><img src="${industryMaintenance}" alt="Worker examines a worn connection at an empty modular berth while riggers guide a suspended cell and a quality worker checks a sample behind protected glass" loading="lazy" /></a><figcaption>Working detail · Concept illustration, not an engineered lifting or isolation procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / HOW IT WORKS</p><h2>Qualification takes<br>room and authority.</h2></div><p>The section distinguishes the retained crane hall, removable cell, empty berth, protected optical gallery, accessible services, and four separate material dispositions. It encodes no measured geometry or flow rate.</p></div><figure><a href="${industrySection}" target="_blank" rel="noopener" aria-label="Open the qualification-cell section full size"><img src="${industrySection}" alt="Qualitative section showing old crane and brick, a lifted opaque cell, empty berth, protected staffed gallery, accessible heat and water services, separate incoming, held, qualified and outgoing residual bays, and external freight" loading="lazy" /></a><figcaption>Reading inset · Six numbered groups are described below. Qualitative design concept; qualification and rejection remain human decisions.</figcaption></figure>${insetCallouts('industry')}</section>
    <section class="section-shell future-boundary"><div class="boundary-box"><h2>What is grounded / What is speculative</h2><p>Grounded in Toledo and Great Lakes manufacturing, freight and infrastructure, the scene explores the work needed between an available residual and a potentially usable input. Qualification, labor and outside resources remain necessary.</p><p>Invented for this 2075 scenario are the crane-hall frontage, removable cell family, protected gallery and material arrangement. Human decisions keep incoming, held/rejected, conditionally qualified and outgoing residual material distinct; qualification does not guarantee use. No real plant, measured geometry, compatible stream, structural capacity, throughput, recovery rate, environmental outcome or continuous operation is asserted. Supplies and residual handling cross the boundary; this is not a closed loop.</p></div><div class="source-box"><p class="eyebrow">METHODS / TECHNICAL RECORD</p><ul><li><a href="${path('methods/')}">Methods and sources ↗</a></li><li><a href="${source('reports/phase17d_hf04_final_production_notes.md')}">Image provenance and technical record ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><h2>Related studies and Methods</h2><p><a href="${path('atlas/industrial-exchange/')}">Industrial Exchange</a> examines qualification, external inputs and residual handling. The working hall is a separate architectural design concept informed by that study.</p><p><a href="${path('methods/')}">Methods</a> explains the limits of these qualitative connections.</p></section>
  </div>`, 'atlas');
}

function maumeeBioAg(): string {
  return layout(`<div class="future-page hf03-page">
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a> <a class="map-context-link" href="${path('maps/')}?region=swamp">Explore this regional context ↗</a><h1 class="future-long-title">Maumee Bio-Ag<br><em>Landscape 2075.</em></h1><p class="future-question">What work appears when productive fields, selective cultivation, machine service, and old drainage must share an edge?</p></section>
    <section class="future-opening"><figure><img src="${bioAgWide}" alt="Composite Maumee-derived farm with open crop rows, a folded bio-ag working seam, a farmer maintaining an old drainage gate, a stopped field machine under repair, a supply truck, and a separate ditch and reed wetland" fetchpriority="high" /><figcaption>Lead image · Composite Maumee-derived 2075 scenario and design concept.</figcaption></figure></section>
    <div class="section-shell future-context prose"><p>A composite Maumee-derived farm keeps open crop rows beside a long, folded working seam. Translucent propagation bays alternate with opaque contained work and service access. A farmer clears sediment at an older gate while a technician repairs a stopped field machine; a conventional delivery keeps outside supply visible.</p><p>The ditch and reed wetland remain separate from the contained work. This scene proposes an adaptation with labor, qualification, stewardship, and downstream responsibility; it does not depict a real farm or demonstrate yield, nutrient removal, water treatment, or ecological improvement.</p></div>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / WORKING DETAIL</p><h2>The gate needs<br>hands and judgment.</h2></div><p>A separately composed close view of sediment clearing, worn water control, muddy access, and the same field-machine repair beyond.</p></div><figure><a href="${bioAgMaintenance}" target="_blank" rel="noopener" aria-label="Open the Maumee Bio-Ag working-detail illustration full size"><img src="${bioAgMaintenance}" alt="Farmer clears reeds and sediment from a weathered drainage gate in wet clay, with ditch water and reeds beyond and a technician servicing a stopped wheeled field machine near the folded seam" loading="lazy" /></a><figcaption>Working detail · Routine work in a speculative composite scene; no drainage or treatment outcome is asserted.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / HOW IT WORKS</p><h2>Separate spaces,<br>shared upkeep.</h2></div><p>The inset distinguishes the open field, selective cultivation, machine berth, opaque contained work, hold/reject route, old gate and ditch, wetland edge, and outside supply. Its coordinates describe the display only.</p></div><figure><a href="${bioAgSection}" target="_blank" rel="noopener" aria-label="Open the field, seam and drainage section full size"><img src="${bioAgSection}" alt="Qualitative section of open productive field, translucent propagation, stopped machine service, opaque contained qualification, hold and outward route, maintained old drainage gate and ditch, distinct wetland reeds, and external supplies" loading="lazy" /></a><figcaption>Reading inset · Six numbered groups are described below. Qualitative design concept; no measured geometry, process result, or environmental outcome.</figcaption></figure>${insetCallouts('farm')}</section>
    <section class="section-shell future-boundary"><div class="boundary-box"><h2>What is grounded / What is speculative</h2><p>Grounded in Maumee agriculture, drainage, weather, farm work and ecology, the scene keeps open productive fields, outside inputs, old water controls and a distinct ditch and wetland edge in view.</p><p>Invented for this 2075 scenario are the selective propagation envelope, folded service seam, opaque contained work, machinery and exact arrangement. Contained work remains separate from open cultivation, drainage and wetland. No real farm, measured geometry, engineered-organism release, yield gain, nutrient removal, water treatment, ecological improvement, verified containment, adoption or self-sufficient loop is claimed.</p></div><div class="source-box"><p class="eyebrow">METHODS / TECHNICAL RECORD</p><ul><li><a href="${path('methods/')}">Methods and sources ↗</a></li><li><a href="${source('reports/phase17d_hf03_final_production_notes.md')}">Image provenance and technical record ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><h2>Related studies and Methods</h2><p><a href="${path('atlas/farm-2075/')}">Farm 2075</a> explores agricultural land use and outside dependencies. <a href="${path('atlas/field-to-lake/')}">From Field to Lake</a> distinguishes sourced watershed geography from process explanation and uncertain lake response.</p><p>These studies provide context, not evidence that the depicted cultivation or processing technology performs as imagined. <a href="${path('methods/')}">Read the Methods.</a></p></section>
  </div>`, 'atlas');
}

function lakeErieCoast(): string {
  return layout(`<div class="future-page hf02-page">
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a> <a class="map-context-link" href="${path('maps/')}?region=coast">Explore this regional context ↗</a><h1 class="future-long-title">Lake Erie Energy &amp;<br><em>Security Coast 2075.</em></h1><p class="future-question">What does advanced energy and observation look like when every connection faces lake weather, needs repair, and crosses distinct responsibilities?</p></section>
    <section class="future-opening"><figure><img src="${coastWide}" alt="Composite Lake Erie and Toledo-derived working coast: a long stepped service terrace, technician replacing a weather screen, grounded civilian environmental survey craft in a dry cradle, working quay and open windy lake" fetchpriority="high" /><figcaption>Lead image · Composite Lake Erie / Toledo-derived 2075 scenario and design concept.</figcaption></figure></section>
    <div class="section-shell future-context prose"><p>A composite working coast has become a low, stepped service terrace. Protected inspection and comparison space sits behind replaceable weather screens; opaque energy and utility rooms are separated from a dry recovery berth and an exposed quay. A stopped civilian environmental survey craft is brought ashore for service while ordinary utility and waterfront work continues.</p><p>Wind, whitecaps, corrosion and occasional fouling make maintenance visible. Staffed thresholds make the access boundary legible; they do not imply uninterrupted service. This is a speculative composite, not a real facility, survey, forecast or energy-technology selection.</p></div>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / WORKING DETAIL</p><h2>A screen wears.<br>A person replaces it.</h2></div><p>A separately composed close view of a technician changing a cloudy sacrificial screen while a returned environmental sensor case is brought to a comparison bench.</p></div><figure><a href="${coastMaintenance}" target="_blank" rel="noopener" aria-label="Open the working-detail illustration full size"><img src="${coastMaintenance}" alt="Technician at reachable height replaces a cloudy, fouled protective inspection screen with tools and an old panel nearby; another worker examines a returned environmental survey sensor case at a bench; windy Lake Erie is beyond" loading="lazy" /></a><figcaption>Working detail · Human servicing and comparison, not proof of successful calibration or an engineered procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / HOW IT WORKS</p><h2>Protected work,<br>exposed edge.</h2></div><p>Follow the service terrace from land to lake, using the six numbered descriptions below. The section shows qualitative relationships.</p></div><figure><a href="${coastSection}" target="_blank" rel="noopener" aria-label="Open the lake-edge service-terrace inset full size"><img src="${coastSection}" alt="Qualitative land-to-lake service-terrace section with six numbered groups; the corresponding descriptions follow the image" loading="lazy" /></a><figcaption>How it works · Qualitative section; its numbered groups are described below. No measured geometry or demonstrated performance.</figcaption></figure><ol class="hf02-inset-callouts" aria-label="Six areas in the lake-edge service-terrace inset"><li><strong>01 / Access + supply</strong><span>A staffed handoff marks a controlled access boundary between the landward service approach and terrace; outside utilities remain external.</span></li><li><strong>02 / Utility + isolation</strong><span>Separate opaque energy and utility rooms keep services distinct and allow an unavailable bay; no energy type or output is specified.</span></li><li><strong>03 / Screen + comparison</strong><span>A replaceable weather screen protects a staffed comparison and calibration workspace for returned sensor equipment; no calibration result is implied.</span></li><li><strong>04 / Survey recovery</strong><span>A stopped civilian environmental-survey craft rests in a dry recovery cradle and depends on human retrieval and repair.</span></li><li><strong>05 / Quay + fouling</strong><span>The exposed working quay meets the wetted edge; subtle biological fouling and weathering indicate upkeep, not abundance or control.</span></li><li><strong>06 / Lake Erie</strong><span>Open lake water brings wind and wave exposure; the section is not a surveyed shoreline and does not establish resilience.</span></li></ol></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><h2>What is grounded / What is speculative</h2><p>Grounded in Lake Erie and Toledo waterfront, utility, port, weather, fouling and environmental-observation context, the scene explores conditional dependencies on energy, human service, recovery, access and institutions.</p><p>Invented for this 2075 scenario are the terrace, recovery cradle, gallery, utility arrangement, craft and workers. The real Toledo intake crib is a separate reference asset; no co-location, surveyed future site or measured geometry is asserted. No exact future energy mix or output, weather tolerance, continuous observation, successful calibration, redundancy, treatment result, security effectiveness or deployment is established. Observation does not itself provide control, and available equipment does not guarantee successful protection.</p></div><div class="source-box"><p class="eyebrow">METHODS / TECHNICAL RECORD</p><ul><li><a href="${path('methods/')}">Methods and sources ↗</a></li><li><a href="${source('reports/phase17d_hf02_final_production_notes.md')}">Image provenance and technical record ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><h2>Related studies and Methods</h2><p><a href="${path('atlas/toledo-crib/')}">The Toledo Intake Crib study</a> concerns a separate, real offshore asset and an imagined retrofit. The futurescape asserts no co-location with that asset or surveyed future site.</p><p><a href="${path('methods/')}">Methods</a> explains the evidence and concept boundary. Explore other working landscapes in <a href="${path()}#futurescapes">the futurescapes collection</a>.</p></section>
  </div>`, 'atlas');
}

function readingHall(): string {
  return layout(`<div class="future-page reading-hall-page">
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#stories">← Stories and places</a><p class="eyebrow accent">VISUAL WORKSHOP · AN IMAGINED TOLEDO, 2075</p><a class="map-context-link" href="${path('maps/')}?region=glass">Explore Toledo’s regional context ↗</a><h1>The Basin<br><em>Reading Hall.</em></h1><p class="future-question">A place to ask what a finding actually covers—and to meet the people keeping its instruments and records alive.</p><a class="button button-primary" href="#story">Play Before the Last Bus <span aria-hidden="true">↓</span></a> <a class="text-link" href="#return-visit">The Return Visit ↓</a></section>
    <section class="future-opening"><figure><a href="${hallA}" target="_blank" rel="noopener" aria-label="Open composition study A full size"><img src="${hallA}" alt="Two people compare record folders at a worn timber counter, with readers and stepped glass instrument rooms in a bright adapted civic hall" fetchpriority="high" /></a><figcaption>Composition A · Across the public counter. Selected visual orientation; generated study, with architectural detail still in development.</figcaption></figure></section>
    <div class="section-shell future-context prose"><p>The room smells of warm timber and somebody’s coffee. A field case arrives at a separate hatch. Behind the staff rail, one instrument compartment is being changed while the upper rooms stay in place. At the public counter, yesterday’s edition is still available beside today’s.</p><p>Here, information has a door, a shelf, a working shift and occasionally a wheel that needs replacing. People can compare methods and ask for clarification. A correction takes a responsible person and a later decision.</p></div>
    ${readingHallScene()}
    ${returnVisitScene()}
    <section class="section-shell future-detail" id="compositions"><div class="section-head"><div><p class="eyebrow">THREE WAYS INTO THE SAME IDEA</p><h2>Counter, threshold,<br><em>working spine.</em></h2></div><p>A foregrounds the encounter. B follows the return from the field. C makes the stepped instrument rooms and upkeep easier to read. A fixes the hall’s orientation. B and C remain camera studies; no surveyed layout or final character portraits are established.</p></div><div class="composition-grid"><figure><a href="${hallB}" target="_blank" rel="noopener" aria-label="Open composition study B full size"><img src="${hallB}" alt="A closed field cooler arrives at a receiving hatch, a dry recorder is checked at a separate bench, and the public counter is visible beyond" loading="lazy" /></a><figcaption><strong>B / Field-return threshold</strong> · Sealed sample receiving and dry recorder handoff face the service court.</figcaption></figure><figure><a href="${hallC}" target="_blank" rel="noopener" aria-label="Open composition study C full size"><img src="${hallC}" alt="Readers sit beside a three-tier instrument spine with staff stairs, while a technician services a compact floor-supported instrument cabinet behind a rail" loading="lazy" /></a><figcaption><strong>C / Inhabited spine</strong> · Fixed rooms, staff landings and a ground-level service event.</figcaption></figure></div></section>
    <section class="section-shell hall-inventions"><div class="section-head"><div><p class="eyebrow accent">THINGS THAT COULD RETURN IN OTHER STORIES</p><h2>A future you<br>can handle.</h2></div><p>Three useful devices for comics and games: small enough to touch, specific enough to cause trouble.</p></div><div class="reading-order-grid"><article><h3>The edition cabinet</h3><p>A public shelf that keeps earlier findings beside the current version. A misplaced divider can start a mystery; finding an old edition can change a conversation.</p></article><article><h3>The comparison dock</h3><p>Two bench positions keep different instruments and dated methods side by side. An adapter fits, yet the records may still be incomparable.</p></article><article><h3>The service berth</h3><p>A fixed frame holds replaceable compact instrument compartments. A missing seal, unavailable bay or stubborn trolley wheel gives a character something to do.</p></article></div></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><h2>Where the idea comes from</h2><p>Model Lab and the repository keep source records, explicit assumptions, earlier outputs and unresolved questions visible. The hall turns those practices into a civic space.</p><p>The building, devices, institutional arrangements and story are imagined. The illustrations are composition studies. Composition A fixes the counter on the front left, instrument rooms on the right, and a separate field-return threshold at the left rear. Service access runs behind the rooms. Technical grounding and unresolved detail stay in the workshop record.</p></div><div class="source-box"><p class="eyebrow">FOLLOW THE THREAD</p><ul><li><a href="${path('methods/')}#observed-flow">A real river record</a></li><li><a href="${path()}#model-lab">Model Lab</a></li><li><a href="${source('reports/creative_development_2026-10-03.md')}">Visual workshop and image provenance ↗</a></li><li><a href="${source('stories/README.md')}">Story workshop ↗</a></li><li><a href="${source('docs/phase_briefs/hf05_reading_hall_continuity_lock.md')}">Hall continuity plan ↗</a></li></ul></div></section>
  </div>`, 'atlas');
}

function methods(): string {
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">THE WORK BEHIND THE IMAGES</p><h1>Methods<br><em>& credits.</em></h1><p>The Atlas brings sourced studies and imagined futures into one publication. Each image should make clear what the project can support and where interpretation begins.</p></section>
  <section class="section-shell method-block"><div class="section-label">READING THE ATLAS</div><div class="method-grid"><div><h2>Different kinds<br>of knowledge.</h2><p>A compelling picture is not proof. Grounded geography and systems do not validate future machinery or establish that a proposed adaptation will work.</p></div><div class="prose"><p><strong>Evidence and model:</strong> sourced observations and reproducibly derived information about current systems, with their limitations.</p><p><strong>Scenario:</strong> a conditional exploration of a possible future, without a forecast or assigned probability.</p><p><strong>Fictional canon:</strong> a deliberate choice established for the fictional setting. It is not evidence about the real basin.</p><p><strong>Provisional sketch and design material:</strong> proposed architecture, equipment, characters or stories. A polished illustration does not promote these ideas to canon.</p></div></div></section>
  <section class="section-shell method-block"><div class="section-label">FROM PICTURE TO EXPLANATION</div><div class="reading-order-grid"><article><p class="eyebrow">FUTURESCAPE</p><h3>A place to enter.</h3><p>A lead image introduces an imagined 2075 place. A working detail shows the human labor and maintenance within it.</p></article><article><p class="eyebrow">HOW IT WORKS</p><h3>Follow the relationships.</h3><p>A system inset explains interfaces, access and dependencies. Qualitative geometry and lines do not establish measured dimensions, flow, probability or performance.</p></article><article><p class="eyebrow">STUDIES</p><h3>Examine the context.</h3><p>The collection includes evidence/model studies and scenario/design studies. A related study offers context without proving a futurescape's proposed technology.</p></article></div><p class="method-boundary">The raster futurescapes are generated concept illustrations. System insets are authored qualitative diagrams. Neither supplies measurements. Exact image sources, generation history, packaging settings and hashes remain available in the repository's production records.</p></section>
  <section id="map-methods" class="section-shell method-block"><div class="section-label">MAPS / GEOGRAPHY AND REGIONAL CHARACTER</div><div class="method-grid"><div><h2>Place before<br><em>invention.</em></h2><p>The <a href="${path('maps/')}">map explorer</a> makes the real basin a way into the Atlas.</p></div><div class="prose"><p>The public map generalizes retained USGS physical waterways, watershed boundaries and lake geometry. Municipality markers use Census representative points; facility markers retain their source-specific address or asset precision. The physical intake crib uses its resolved Coast Guard location, distinct from a legacy monitoring point.</p><p>Regional identities describe overlapping character and connections, with no territorial polygons. Composite 2075 scenes remain linked interpretations without exact site pins. Held historical swamp geometry and nonphysical analytical connectors are excluded.</p><p>Earlier geology, energy and freight plates retain their original labels and dated limits. Their lines and capacities do not demonstrate present operations, shipments or successful future machinery. <a href="${source('assets/atlas/region/source_manifest.json')}">Derivative sources, settings and hashes ↗</a>.</p></div></div></section>
  <section id="model-lab-methods" class="section-shell method-block"><div class="section-label">MODEL LAB</div><div class="method-grid"><div><h2>Quantitative tests,<br>stated limits.</h2><p>The illustrated watershed study explains geography and processes. Model Lab separately tests routing and mass accounting with saved synthetic cases.</p></div><div class="prose"><p>The three cases compare strict handling of unresolved links, a hypothetical successor route and a hypothetical nitrogen pass-through assumption. They use diagnostic unit pulses, not observed water or nutrient inputs. Assumed non-forwarding is bookkeeping, not measured storage, treatment or ecological retention.</p><p>Map polygons are watershed accounting areas, not stream channels. Traces show topology and routing-policy reachability, not source attribution, travel time or concentration. Missing field observations cannot be treated as zero merely because a synthetic diagnostic omits an input.</p><p>The local Shiny explorer reads saved outputs and checks schemas, identities, units and source/code provenance. It does not run the model or edit a scenario. Independent Python and R checks audit the saved accounting; matching hashes establish content identity, not scientific truth.</p><p><a href="${source('data/model_lab/README.md')}">Cases, reproduction and validators ↗</a> · <a href="${source('src/R/model_lab/explorer/README.md')}">Local explorer setup ↗</a> · <a href="${source('reports/model_lab_v01_water_nutrient_readiness.md')}">Evidence readiness and limits ↗</a></p></div></div></section>
  <section id="observed-flow" class="section-shell method-block observed-record"><div class="section-label">ONE REAL RIVER RECORD</div><div class="section-head"><div><h2>The river’s record.</h2></div><p>Daily mean discharge at the Maumee River’s Waterville gauge, recorded by USGS. This complete 2025 series was downloaded on 3 September 2026. <a href="${path('maps/')}#river-record">Explore individual days and the scientific principle ↗</a>.</p></div><figure><a href="${observedFlow}" target="_blank" rel="noopener" aria-label="Open the Waterville observed daily-flow chart full size"><img src="${observedFlow}" alt="Line chart of 365 daily mean Maumee River discharges at Waterville in 2025, with a pronounced April peak and source quality flags distinguished" loading="lazy" /></a><figcaption>USGS station 04193500 · Daily means in cubic feet per second. One station’s historical observations; this chart is separate from the synthetic routing cases.</figcaption></figure><ul class="flow-legend"><li><span aria-hidden="true">━</span> 322 approved days in the snapshot</li><li><span aria-hidden="true">○</span> 43 provisional days in the snapshot</li><li><span aria-hidden="true">▲</span> 13 estimated values, also approved</li></ul><p>Approval and estimation flags describe the retained snapshot. A daily mean does not show an instantaneous peak, flood extent or nutrient load. The longer retained record has one missing day, 1 June 2026; this complete-year view does not fill it.</p><p><a href="https://waterdata.usgs.gov/monitoring-location/04193500/">USGS station record ↗</a> · <a href="${source('outputs/model_lab/observations/waterville_daily_flow_2025.csv')}">Daily values and flags ↗</a> · <a href="${source('reports/model_lab_empirical_inputs_2026-10-03.md')}">Input assessment and source snapshot ↗</a></p></section>
  <section class="section-shell method-block"><div class="section-label">TECHNICAL TRANSPARENCY</div><div class="method-grid"><div><h2>Research remains<br>traceable.</h2><p>The repository preserves sources, builders, validation and versioned research baselines. A “frozen” package is reviewed research preserved at a recorded version, so later worldbuilding cannot silently change it; this does not mean complete knowledge of the basin.</p><p>Technical records use <strong>E</strong> for evidence/model, <strong>S</strong> for scenario, <strong>C</strong> for fictional canon and <strong>K</strong> for provisional sketch material. “Design concept” describes the visual subset of K; it does not change a record's status.</p></div><div class="prose"><p>Research covers water, geology, energy, freight, ecology, health, climate, governance, population and technology. Shared system definitions and bounded stress pathways are indexed through the research reports.</p><p>Contamination, exposure, dose and illness are distinct. Observation does not itself provide control; technology does not automatically provide protection; an available response is not evidence of a successful response. Model pathways stop where a further claim lacks support.</p><p><a href="${source('metadata/sources.yml')}">Source registry ↗</a> · <a href="${source('reports/README.md')}">Research by subject and validation ↗</a> · <a href="${source('docs/canon_status.md')}">Fictional canon register ↗</a> · <a href="${source('PROJECT_STATUS.md')}">Detailed development status ↗</a></p><p>Illustration records: <a href="${source('reports/phase17d_hf01_final_production_notes.md')}">Glass City</a>, <a href="${source('reports/phase17d_hf03_final_production_notes.md')}">Maumee Bio-Ag</a>, <a href="${source('reports/phase17d_hf04_final_production_notes.md')}">Industrial Metabolism</a>, and <a href="${source('reports/phase17d_hf02_final_production_notes.md')}">Lake Erie Coast</a>.</p></div></div></section>
  <section class="section-shell method-block"><div class="section-label">CREDITS / SOURCE RIGHTS</div><div class="method-grid"><div><h2>Shared records,<br>careful attribution.</h2><p>Original site design, editorial text and diagrams belong to the Western Basin Worldbuilding project. Third-party data and imagery retain their own terms.</p></div><div class="prose"><p>Documented research sources include <a href="https://www.usgs.gov/3d-hydrography-program/access-3dhp-data-products">USGS hydrography ↗</a>, <a href="https://www.epa.gov/tmdl/epas-approval-ohios-maumee-watershed-nutrient-total-maximum-daily-load">US EPA's Maumee nutrient TMDL ↗</a>, <a href="https://coastalscience.noaa.gov/science-areas/habs/hab-forecasts/lake-erie/">NOAA's Lake Erie HAB work ↗</a>, and <a href="https://toledo.oh.gov/departments/public-works/water/water-treatment">City of Toledo water treatment ↗</a>. Individual source reports and figure manifests identify the inputs used.</p><p>The real Toledo intake crib location uses the U.S. Coast Guard Light List, corroborating NOAA/NDBC evidence and aerial review. Its drawing remains approximate. The third-party reference photograph is excluded because reuse rights are unconfirmed. Held Great Black Swamp geometry and its reference image are also excluded.</p><p>The repository's MIT license covers original code and documentation, not third-party data or imagery. See the <a href="${source('docs/references/DATA_AND_ASSET_LICENSING.md')}">data and asset licensing notes ↗</a>.</p></div></div></section>
  <section class="section-shell end-cta"><h2>Follow a system<br>through the basin.</h2><a class="button button-primary" href="${path()}#essays">Explore the studies <span aria-hidden="true">↗</span></a></section>`, 'methods');
}

function roadmap(): string {
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">AREAS OF WORK / REVIEWED 3 OCTOBER 2026</p><h1>From a basin<br>to possible <em>lives.</em></h1><p>Explore the work available now and the questions still being developed.</p></section>
  <section class="section-shell roadmap-section"><div class="timeline"><div class="timeline-item"><span class="timeline-status done">EXPLORE</span><div><h2>Maps and real observations</h2><p>A basin map, five regional readings and eleven sourced landmarks connect the Atlas’s imagined places to geography. Earlier research maps are visible alongside a Waterville daily-flow explorer. The next useful scientific link is a compatible measured nutrient series; geography and discharge alone cannot establish its loads. <a href="${path('maps/')}">Explore the map.</a></p></div></div>
    <div class="timeline-item"><span class="timeline-status done">RESEARCH</span><div><h2>Research foundation</h2><p>Sourced environmental, infrastructure, health, governance and technology studies describe the basin and its dependencies. Versioned models preserve their assumptions and limits; they do not provide complete knowledge of the region. <a href="${path('methods/')}">Explore the Methods and research records.</a></p></div></div>
    <div class="timeline-item"><span class="timeline-status done">EXPLORE</span><div><h2>Studies</h2><p>Four illustrated studies range from watershed pathways and a real water-intake structure to possible farm and industrial arrangements. Each distinguishes evidence from approximation and future concept. <a href="${path()}#essays">Browse the studies.</a></p></div></div>
    <div class="timeline-item"><span class="timeline-status active">DEVELOPING</span><div><h2>2075 Futurescapes</h2><p>Explore Glass City, Maumee Bio-Ag Landscape, Industrial Metabolism and the Lake Erie Energy &amp; Security Coast. The Basin Reading Hall now has three composition studies and two interactive encounters. The counter, instrument spine and separate return/service areas have a fixed visual orientation; architectural detail remains in development. <a href="${path()}#futurescapes">Enter the futurescapes.</a></p></div></div>
    <div class="timeline-item"><span class="timeline-status done">LOCAL TOOL</span><div><h2>Model Lab</h2><p>Saved synthetic routing examples and a local read-only explorer are available. They test accounting and explicit assumptions, not measured loads or calibrated watershed behavior. A separate observed Waterville flow record can be explored day by day from the map, with its source chart in Methods. Routed empirical modeling still needs suitable inputs and a documented geographic crosswalk. <a href="${path()}#model-lab">Find the Model Lab guides.</a></p></div></div>
    <div class="timeline-item"><span class="timeline-status active">EXPLORING</span><div><h2>People and stories</h2><p><a href="${path('atlas/basin-reading-hall/')}#story">Before the Last Bus</a> and <a href="${path('atlas/basin-reading-hall/')}#return-visit">The Return Visit</a> follow Renata’s question through a public correction, a location check and an errand she may miss. Six ordinary-day drafts are preserved in the story workshop; characters and events remain provisional fiction. <a href="${path('game/')}">Vesper Station</a> is a separate experimental game companion.</p></div></div>
  </div></section>
  <section class="status-band"><div class="section-shell status-grid"><div><h2>Questions<br>still open.</h2></div><div><p>The historical Great Black Swamp's candidate boundary remains unresolved for use here. The Toledo intake crib's physical location is resolved, while its illustrated future retrofit remains speculative. Futurescape architecture and activities remain scenarios and design concepts; no performance or future deployment follows from their depiction.</p><a class="button button-outline" href="${source('PROJECT_STATUS.md')}">Technical status record ↗</a> <a class="text-link" href="${path('updates/')}">Read the updates ↗</a></div></div></section>`, 'roadmap');
}

function updates(): string {
  const entries: { date: string; display: string; title: string; text: string; href: string; linkLabel: string }[] = [
    { date: '2026-10-03', display: '3 October 2026', title: 'Maps become a way into the Atlas', href: path('maps/'), linkLabel: 'Explore the basin ↗', text: 'A geographic explorer brings eleven sourced landmarks and five overlapping regional identities into view, with links to imagined futures and encounters. Earlier watershed, geology, energy and freight maps now have a public collection. At Waterville, select a day from the real 2025 flow record and inspect its original quality flags.' },
    { date: '2026-10-03', display: '3 October 2026', title: 'The Return Visit: another Reading Hall encounter', href: path('atlas/basin-reading-hall/')+'#return-visit', linkLabel: 'Play The Return Visit ↗', text: 'Renata returns to find a clearer public card. Catch the bus for a shirt handoff, or stay while Hannah checks the place on her map. The six-panel adaptation of the earlier encounter has been withdrawn for narrative continuity problems; its source material remains in the repository.' },
    { date: '2026-10-03', display: '3 October 2026', title: 'Model Lab: inspect saved routing examples', href: source('src/R/model_lab/explorer/README.md'), linkLabel: 'Explorer setup and saved cases ↗', text: 'A local read-only explorer compares three synthetic water/nutrient routing cases, their accounting areas, traces and ledgers. Source and setup guides are available in the repository. The examples test arithmetic and assumptions; they are not measured loads or calibrated predictions. The R/Shiny app runs separately from this website.' },
    { date: '2026-10-03', display: '3 October 2026', title: 'Step into the Basin Reading Hall', href: path('atlas/basin-reading-hall/'), linkLabel: 'Explore the hall and story ↗', text: 'A civic observation and interpretation hall is the next information-ecology scene. Three composition studies explore a public counter, field-return threshold and stepped instrument spine. A short interactive story, Before the Last Bus, gives the developing hall an ordinary human encounter.' },
    { date: '2026-09-28', display: '28 September 2026', title: 'Lake Erie Energy &amp; Security Coast 2075 is published', href: path('atlas/lake-erie-energy-security-coast-2075/'), linkLabel: 'Explore this futurescape ↗', text: 'A working coast brings weather-screen replacement, civilian environmental-survey recovery and exposed quay work into view. A system inset and six numbered descriptions explain its dependencies. The scene is a composite scenario and design concept, with no surveyed siting, intake-crib co-location or energy, treatment or security performance claim.' },
    { date: '2026-09-28', display: '28 September 2026', title: 'Maumee Bio-Ag Landscape 2075 is published', href: path('atlas/maumee-bio-ag-2075/'), linkLabel: 'Explore this futurescape ↗', text: 'Open fields meet selective cultivation, machine service, old drainage and a separate wetland edge. A closer view follows the human work of clearing a sedimented gate. This imagined farm asserts no yield gain, water treatment, ecological improvement or verified containment.' },
    { date: '2026-09-28', display: '28 September 2026', title: 'Industrial Metabolism 2075 joins the futurescapes', href: path('atlas/industrial-metabolism-2075/'), linkLabel: 'Explore this futurescape ↗', text: 'An old crane hall makes room for removable process cells, staffed qualification and separate material bays. The working detail shows repair and inspection; outside freight and residual handling keep the proposed system open. No successful exchange or process performance is established.' },
    { date: '2026-09-27', display: '27 September 2026', title: 'Glass City 2075 gains a working detail and system inset', href: path('atlas/glass-city-2075/'), linkLabel: 'Explore this futurescape ↗', text: 'A Toledo-derived street is explored through its optical canopy, cassette-replacement work and an old-wall section. Public passage and maintenance share the picture. The architecture remains a scenario and design concept without structural, optical or cooling-performance claims.' }
  ];
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">UPDATES</p><h1>New in<br>the <em>Atlas.</em></h1><p>New illustrated places, research tools and work still in development. <a href="${path('roadmap/')}">See the areas of ongoing work.</a></p></section><section class="section-shell updates-section">${entries.map(entry => `<article class="update-entry"><div class="update-meta"><time datetime="${entry.date}">${entry.display}</time></div><div><h2>${entry.title}</h2><p>${entry.text}</p><div class="update-links"><a href="${entry.href}">${entry.linkLabel}</a><a href="${path('methods/')}">Methods and sources ↗</a></div></div></article>`).join('')}</section>`, 'updates');
}

const essay = essays.find((item) => item.key === page as EssayKey);
if (page === 'maps') {
  root.innerHTML = layout('<section class="plain-hero section-shell"><h1>Loading the basin map…</h1></section>', 'maps');
  import('./region-explorer').then(module => {
    root.innerHTML = layout(module.regionExplorer(), 'maps');
    module.mountRegionExplorer();
    if (location.hash) document.getElementById(location.hash.slice(1))?.scrollIntoView({ behavior: 'instant' });
  });
} else root.innerHTML = essay ? essayView(essay) : page === 'glass-city' ? glassCity() : page === 'industrial-metabolism' ? industrialMetabolism() : page === 'maumee-bio-ag' ? maumeeBioAg() : page === 'lake-erie-coast' ? lakeErieCoast() : page === 'reading-hall' ? readingHall() : page === 'methods' ? methods() : page === 'roadmap' ? roadmap() : page === 'updates' ? updates() : home();

if (page === 'reading-hall') {
  mountReadingHallScene();
  mountReturnVisitScene();
}
