import './style.css';
import { essays, type Essay, type EssayKey } from './content';
import heroWide from '../../assets/phase17d/hf01/hf01_glass_city_2075_hero_wide.webp';
import maintenanceView from '../../assets/phase17d/hf01/hf01_glass_city_2075_maintenance.webp';
import canopySection from '../../assets/phase17d/hf01/hf01_canopy_old_wall_section.svg';
import industryWide from '../../assets/phase17d/hf04/hf04_industrial_metabolism_2075_hero_wide.webp';
import industryMaintenance from '../../assets/phase17d/hf04/hf04_industrial_metabolism_2075_maintenance.webp';
import industrySection from '../../assets/phase17d/hf04/hf04_qualification_cell_section.svg';
import bioAgWide from '../../assets/phase17d/hf03/hf03_maumee_bio_ag_2075_hero_wide.webp';
import bioAgMaintenance from '../../assets/phase17d/hf03/hf03_maumee_bio_ag_2075_maintenance.webp';
import bioAgSection from '../../assets/phase17d/hf03/hf03_field_seam_drainage_section.svg';
import coastWide from '../../assets/phase17d/hf02/hf02_lake_erie_energy_security_coast_2075_hero_wide.webp';
import coastMaintenance from '../../assets/phase17d/hf02/hf02_lake_erie_energy_security_coast_2075_maintenance.webp';
import coastSection from '../../assets/phase17d/hf02/hf02_service_terrace_recovery_section.svg';

const root = document.querySelector<HTMLDivElement>('#app');
if (!root) throw new Error('Atlas root is missing');

const base = import.meta.env.BASE_URL;
const path = (suffix = '') => `${base}${suffix}`;
const repo = 'https://github.com/stephenlewandowski/western-basin-worldbuilding';
const source = (file: string) => `${repo}/blob/main/${file}`;
const page = document.body.dataset.page ?? 'home';

function nav(active: string): string {
  const item = (label: string, href: string, key: string) =>
    `<a href="${path(href)}" ${active === key ? 'aria-current="page"' : ''}>${label}</a>`;
  return `<a class="skip-link" href="#main">Skip to content</a>
    <header class="site-header"><div class="header-inner">
      <a class="brand" href="${path()}"><span class="brand-mark" aria-hidden="true">WB<span>•</span></span><span>WESTERN BASIN<br><strong>WORLDBUILDING</strong></span></a>
      <nav class="top-nav" aria-label="Main navigation">
        ${item('Home', '', 'home')}${item('Atlas', '#futurescapes', 'atlas')}${item('Methods & credits', 'methods/', 'methods')}${item('Roadmap', 'roadmap/', 'roadmap')}${item('Updates', 'updates/', 'updates')}
      </nav>
    </div></header>`;
}

function footer(): string {
  return `<footer class="site-footer"><div class="footer-inner">
    <div><span class="eyebrow">Western Basin Worldbuilding</span><p>An illustrated research and speculative worldbuilding project rooted in Toledo, the Maumee watershed, and western Lake Erie.</p></div>
    <div class="footer-links"><a href="${path('methods/')}">Methods & credits</a><a href="${path('roadmap/')}">Roadmap</a><a href="${path('updates/')}">Updates</a><a href="${repo}">Research repository ↗</a><a href="${path('game/')}">Vesper Station game ↗</a></div>
    <p class="footer-bottom">Atlas Preview · Four futurescapes published · Futurescape development continues · September 2026 · Real geography first; fictional interpretation second.</p>
  </div></footer>`;
}

function layout(content: string, active: string): string {
  return `${nav(active)}<main id="main">${content}</main>${footer()}`;
}

function card(essay: Essay): string {
  return `<a class="essay-card" href="${path(essay.slug)}">
    <div class="card-image"><img src="${essay.cover}" alt="${essay.coverAlt}" loading="lazy" /></div>
    <div class="card-content"><span class="eyebrow">${essay.number} / ${essay.status}</span><h3>${essay.title}</h3><p>${essay.subtitle}</p><span class="card-link">Read the visual essay <span aria-hidden="true">↗</span></span></div>
  </a>`;
}

function home(): string {
  return layout(`<section class="hero"><div class="hero-inner">
    <div class="hero-copy"><p class="eyebrow accent">AN ILLUSTRATED REGIONAL & SYSTEMS ATLAS · PREVIEW v0.1</p>
      <h1>The future<br>has a <em>watershed.</em></h1>
      <p class="hero-deck">A grounded look at the places and systems around Toledo and western Lake Erie—and at the lives that might grow from them.</p>
      <div class="hero-actions"><a class="button button-primary" href="${path('atlas/glass-city-2075/')}">Enter Glass City 2075 <span aria-hidden="true">↗</span></a><a class="text-link" href="${path('methods/')}">How to read this atlas <span aria-hidden="true">↗</span></a></div>
    </div>
    <div class="hero-art"><div class="hero-art-frame"><img src="${heroWide}" alt="Illustrated Toledo-derived working street beneath a branching optical glass canopy, with a suspended replacement cassette and maintenance crew after rain" fetchpriority="high" /><span class="art-label">HF-01 / GLASS CITY 2075</span></div><p class="hero-art-caption">Composite Toledo-derived 2075 scenario / K architectural form.</p></div>
  </div></section>
  <section id="futurescapes" class="futurescape-section section-shell"><div class="section-label">FOUR PUBLISHED FUTURESCAPES · 2075</div>
    <div class="section-head"><div><h2>From systems model<br>to <em>inhabited futurescapes.</em></h2></div><p>The Atlas is extending its scientific systems model into inhabited 2075 futurescapes: speculative places in which technology changes the physical form and use of the Western Basin. Each place is introduced by a lead image, then explored through a working detail, a system explanation, and its evidence boundaries.</p></div>
    <div class="futurescape-cards"><article class="futurescape-card futurescape-feature"><a href="${path('atlas/glass-city-2075/')}"><img src="${heroWide}" alt="Glass City 2075 optical arcade and cassette replacement" loading="lazy" /><span class="eyebrow">FIRST FUTURESCAPE / S–K CONCEPT</span><h3>HF-01 — Glass City 2075</h3><p>Enter a Toledo-derived street beneath a maintained optical canopy. Follow the replacement work, ordinary public route, and the boundaries of this speculative 2075 place.</p><span class="card-link">Explore the futurescape and system section <span aria-hidden="true">↗</span></span></a></article><article class="futurescape-card futurescape-feature"><a href="${path('atlas/industrial-metabolism-2075/')}"><img src="${industryWide}" alt="Industrial Metabolism 2075 old crane hall, suspended modular cell, and vertical qualification frontage" loading="lazy" /><span class="eyebrow">SECOND FUTURESCAPE / S–K CONCEPT</span><h3>HF-04 — Industrial Metabolism 2075</h3><p>Enter an old crane hall reorganized for replaceable process cells, staffed qualification, segregated materials, and open freight exchange.</p><span class="card-link">Explore the hall and qualification section <span aria-hidden="true">↗</span></span></a></article><article class="futurescape-card futurescape-feature"><a href="${path('atlas/maumee-bio-ag-2075/')}"><img src="${bioAgWide}" alt="Composite Maumee-derived open field, folded working seam, old drainage gate, and separate reed wetland" loading="lazy" /><span class="eyebrow">THIRD PUBLISHED FUTURESCAPE / S–K CONCEPT</span><h3>HF-03 — Maumee Bio-Ag Landscape 2075</h3><p>Follow an unroofed productive field, segmented cultivation and service seam, ordinary gate maintenance, outside supply, and distinct ditch and wetland edge.</p><span class="card-link">Explore the futurescape and its section <span aria-hidden="true">↗</span></span></a></article><article class="futurescape-card futurescape-feature"><a href="${path('atlas/lake-erie-energy-security-coast-2075/')}"><img src="${coastWide}" alt="Composite Lake Erie service terrace with protected galleries, dry civilian survey recovery cradle, working quay and open windy water" loading="lazy" /><span class="eyebrow">FOURTH PUBLISHED FUTURESCAPE / SCENARIO</span><h3>Lake Erie Energy &amp; Security Coast 2075</h3><p>Follow weather-screen maintenance, civilian environmental-survey recovery, separate utility spaces and the exposed lake edge.</p><span class="card-link">Explore the working coast and system inset <span aria-hidden="true">↗</span></span></a></article></div>
    <p class="futurescape-latest"><a class="text-link" href="${path('updates/')}">Read the latest project update <span aria-hidden="true">↗</span></a></p>
  </section>
  <section class="intro-section section-shell"><div class="section-label"><span class="rule-number">I</span> THE IDEA</div>
    <div class="intro-grid"><h2>Start with the place.<br><em>Follow the connections.</em></h2><div><p>Toledo sits where the Maumee River, Lake Erie, agriculture, drinking water, industry, freight, energy, ecology, and public institutions meet. Those connections shape what can plausibly happen next.</p><p>This project moves from a sourced model of the real basin to possible futures and an inhabited world. Each step is labeled so observation, scenario, and invention remain clear. <em>The Glass Basin</em> is a working name for that future-facing Atlas; its final title remains open.</p></div></div>
    <div class="process-line" aria-label="Project sequence"><span>REAL PLACE</span><b>→</b><span>CONNECTED SYSTEMS</span><b>→</b><span>POSSIBLE FUTURES</span><b>→</b><span>LIVED WORLD</span></div>
  </section>
  <section id="essays" class="essays-section section-shell"><div class="section-head"><div><div class="section-label"><span class="rule-number">II</span> STUDIES / HOW THE ATLAS WORKS</div><h2>Four ways into<br>the basin.</h2></div><p>These accepted Phase 17A studies are the Atlas’s scientific and systems-support layer. Open a study to see its figures at full size, its evidence status, and its limits.</p></div>
    <div class="card-grid">${essays.map(card).join('')}</div>
  </section>
  <section class="status-band"><div class="section-shell status-grid"><div><p class="eyebrow accent">CURRENT WORK / FUTURESCAPE DEVELOPMENT</p><h2>From model<br>to lived world.</h2></div><div><p>The scientific foundation remains accepted and frozen through Phase 16. Phase 17A’s four studies support the systems explanation. Glass City, Industrial Metabolism, Maumee Bio-Ag, and Lake Erie Energy &amp; Security Coast are the four published futurescapes. Their architecture and activities remain scenario and design concepts, with no new canon. Further futurescape development remains in progress. GBI-03 Adaptive Crop / Propagation Envelope is established; the Bio-Ag Edge Processing Module remains provisional. Phase 17C ordinary-day tests remain separate and provisional.</p><a class="button button-outline" href="${path('roadmap/')}">See the roadmap <span aria-hidden="true">↗</span></a> <a class="text-link" href="${path('updates/')}">Project updates <span aria-hidden="true">↗</span></a></div></div></section>
  <section class="section-shell approach-section"><div class="section-label"><span class="rule-number">III</span> READING KEY</div><h2>What kind of claim<br>am I looking at?</h2><div class="key-grid"><div><span class="key-letter evidence">E</span><h3>Evidence / model</h3><p>Sourced or reproducibly derived information about the real basin.</p></div><div><span class="key-letter scenario">S</span><h3>Scenario</h3><p>A plausible future condition used for exploration, never a forecast.</p></div><div><span class="key-letter canon">C</span><h3>Canon</h3><p>A deliberate fictional choice. This preview makes no new canon.</p></div><div><span class="key-letter sketch">K</span><h3>Sketch</h3><p>Provisional visual or narrative development.</p></div></div><a class="text-link" href="${path('methods/')}">Read the methods and credits <span aria-hidden="true">↗</span></a></section>`, 'home');
}

function essayView(essay: Essay): string {
  const index = essays.findIndex((item) => item.key === essay.key);
  const next = essays[(index + 1) % essays.length];
  return layout(`<div class="essay-page"><section class="essay-hero section-shell">
    <a class="back-link" href="${path()}#essays">← All visual essays</a>
    <div class="essay-header-grid"><div><p class="eyebrow accent">ATLAS STUDY ${essay.number} / ${essay.place.toUpperCase()}</p><h1>${essay.title}</h1><p class="essay-subtitle">${essay.subtitle}</p><div class="status-pill">${essay.status}</div></div><p class="essay-lead">${essay.lead}</p></div>
    </section><div class="section-shell"><figure class="cover-figure"><a href="${essay.cover}" target="_blank" rel="noopener" aria-label="Open the lead figure full size"><img src="${essay.cover}" alt="${essay.coverAlt}" /></a><figcaption>Lead figure · Open image for full size <span aria-hidden="true">↗</span></figcaption></figure></div>
    <section class="section-shell reading-section"><div class="reading-side"><span class="eyebrow">THE READER'S QUESTION</span><h2>${essay.question}</h2></div><div class="prose">${essay.reading.map((paragraph) => `<p>${paragraph}</p>`).join('')}</div></section>
    <section class="section-shell panel-section"><div class="section-head"><div><div class="section-label"><span class="rule-number">${essay.number}</span> VISUAL SEQUENCE</div><h2>Read the panels.</h2></div><p>Click a figure to inspect its labels at full size. The sequence moves from place or form to the relationships that organize it.</p></div>
      <div class="panel-grid">${essay.panels.map((panel) => `<figure class="panel"><a href="${panel.image}" target="_blank" rel="noopener" aria-label="Open ${panel.title} full size"><img src="${panel.image}" alt="${panel.alt}" loading="lazy" /></a><figcaption><strong>${panel.title}</strong><span>${panel.caption}</span></figcaption></figure>`).join('')}</div>
    </section><section class="section-shell boundary-section"><div class="boundary-box"><span class="eyebrow">INTERPRETIVE BOUNDARY</span><p>${essay.boundary}</p></div><div class="source-box"><span class="eyebrow">FOLLOW THE WORK</span><ul>${essay.sources.map(({ label, path: file }) => `<li><a href="${source(file)}">${label} ↗</a></li>`).join('')}</ul><small>Source links lead to the project repository. Access depends on repository visibility.</small></div></section>
    ${essay.key === 'industry' ? `<section class="section-shell future-related"><p class="eyebrow">FROM STUDY TO FUTURESCAPE</p><h2>Enter the working hall.</h2><p>The <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075 hero ↗</a> uses this earlier exchange study as S/K development lineage. Its composite crane hall is a separate architectural sketch, not a reconstruction of this district diagram.</p></section>` : ''}
    <a class="next-essay" href="${path(next.slug)}"><span class="eyebrow">NEXT STUDY / ${next.number}</span><strong>${next.title} <span aria-hidden="true">↗</span></strong></a>
  </div>`, 'atlas');
}

function glassCity(): string {
  return layout(`<div class="future-page">
    <section class="future-opening"><figure><img src="${heroWide}" alt="Composite Toledo-derived street after rain, beneath a branching translucent optical canopy as workers guide a suspended replacement cassette" fetchpriority="high" /><figcaption>HF-01 / GLASS CITY 2075 · Composite Toledo-derived 2075 scenario / K architectural form.</figcaption></figure></section>
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a><p class="eyebrow accent">PHASE 17D / FIRST PUBLIC FUTURESCAPE</p><h1>Glass City<br><em>2075.</em></h1><div class="future-intro-grid"><p class="future-question">What happens when a glassmaking city makes shade, repair, freight, and public passage part of the same maintained roof?</p><div class="prose"><p>A composite Toledo-derived industrial street has gained a second roofline: patterned optical leaves over older brick and concrete, with walkable service ribs and public space below. One cassette is being replaced while people cross, wait, and move freight nearby.</p><p>The canopy is a speculative architectural form. Its interfaces require energy, labor, access, and agreements; the image does not show a built project or a predicted future.</p></div></div></section>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / MAINTENANCE VIEW</p><h2>Repair belongs<br>in the picture.</h2></div><p>A closer, deliberately composed view of the human-guided replacement, its open berth, service access, and old/new material joints.</p></div><figure><a href="${maintenanceView}" target="_blank" rel="noopener" aria-label="Open the maintenance illustration full size"><img src="${maintenanceView}" alt="Workers guide a replaceable glass canopy cassette beside its open attachment berth, above an older brick wall and a cordoned public route" loading="lazy" /></a><figcaption>Maintenance view · Concept illustration, not an engineered lifting procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / EXPLANATORY SECTION</p><h2>Old wall,<br>new working roof.</h2></div><p>The section separates masonry, attachment, a walkable service rib, glazing, data and electrical paths, and the public route. It shows relationships without measured dimensions or performance.</p></div><figure><a href="${canopySection}" target="_blank" rel="noopener" aria-label="Open the canopy and old-wall section full size"><img src="${canopySection}" alt="Qualitative section showing retained masonry, replaceable optical cassettes, service rib, distinct data and electrical paths, maintenance access, public route, and an unconnected neighbor" loading="lazy" /></a><figcaption>Supporting section · Schematic K form; no dimensions or performance claims.</figcaption></figure></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><p class="eyebrow">E / S / K BOUNDARY</p><p><strong>E:</strong> inherited Toledo and Western Basin industrial, settlement, climate, and systems context. <strong>S:</strong> conditional adaptation involving energy, labor, maintenance, access, and governance. <strong>K:</strong> this arcade, its glass and connections, the freight handoff, street arrangement, and depicted activities. No new canon is created.</p><p>Composite view; no mapped parcel or surveyed sightline. Structural suitability, optics, cooling or health benefit, bird safety, affordability, cross-property continuity, and citywide adoption are unresolved.</p></div><div class="source-box"><p class="eyebrow">FOLLOW THE WORK</p><ul><li><a href="${source('docs/phase_briefs/phase17d_futurist_atlas_synthesis.md')}">Phase 17D synthesis ↗</a></li><li><a href="${source('reports/phase17d_hero_futurescape_concepts.md')}">HF-01 concept and boundaries ↗</a></li><li><a href="${source('reports/phase17d_hf01_final_production_notes.md')}">Production and provenance notes ↗</a></li><li><a href="${path('methods/')}">Methods and claim types ↗</a></li><li><a href="${path('roadmap/')}">Project roadmap ↗</a></li><li><a href="${path('updates/')}">HF-01 update ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><p class="eyebrow">RELATED ATLAS WORK</p><h2>What persists when<br>a real asset changes?</h2><p><a href="${path('atlas/toledo-crib/')}">The Toledo Intake Crib ↗</a> uses a separately verified physical asset to explain old/new persistence. Glass City is a different, composite street and does not depict the crib site.</p><p><a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075 ↗</a> is the second Phase 17D futurescape, moving from the broad public canopy to a tall maintained factory interior.</p><a class="text-link" href="${path()}#essays">Explore the four systems studies <span aria-hidden="true">↗</span></a></section>
  </div>`, 'atlas');
}

function industrialMetabolism(): string {
  return layout(`<div class="future-page">
    <section class="future-opening"><figure><img src="${industryWide}" alt="Composite Toledo-derived old brick crane hall with a suspended replaceable industrial cell, tall modular frontage, workers, separate material bays, and open freight yard" fetchpriority="high" /><figcaption>HF-04 / INDUSTRIAL METABOLISM 2075 · Composite Toledo-derived 2075 scenario / K architectural form.</figcaption></figure></section>
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a><p class="eyebrow accent">PHASE 17D / SECOND PUBLIC FUTURESCAPE</p><h1 class="future-long-title">Industrial<br><em>Metabolism 2075.</em></h1><div class="future-intro-grid"><p class="future-question">What would industry look like if the work between an available residual and a usable input occupied the architecture?</p><div class="prose"><p>A composite Toledo-derived crane hall holds a tall, replaceable exchange frontage. An old crane lowers one opaque cell toward an empty berth. Protected qualification, separate stores, a staffed handoff, and external rail freight share the hall without becoming one automatic process.</p><p>The scene proposes a physical place for checking, repair, rejection, and outside dependencies. It does not assign a new process to a real plant or assert that any material exchange succeeds.</p></div></div></section>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / MAINTENANCE VIEW</p><h2>Replacement has<br>an open edge.</h2></div><p>A separately composed close view brings a worn coupling, empty berth, human-guided lift, protected inspection window, and held material into focus.</p></div><figure><a href="${industryMaintenance}" target="_blank" rel="noopener" aria-label="Open the Industrial Metabolism maintenance illustration full size"><img src="${industryMaintenance}" alt="Worker examines a worn connection at an empty modular berth while riggers guide a suspended cell and a quality worker checks a sample behind protected glass" loading="lazy" /></a><figcaption>Maintenance view · Concept illustration, not an engineered lifting or isolation procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / EXPLANATORY SECTION</p><h2>Qualification takes<br>room and authority.</h2></div><p>The section distinguishes the retained crane hall, removable cell, empty berth, protected optical gallery, accessible services, and four separate material dispositions. It encodes no measured geometry or flow rate.</p></div><figure><a href="${industrySection}" target="_blank" rel="noopener" aria-label="Open the qualification-cell section full size"><img src="${industrySection}" alt="Qualitative section showing old crane and brick, a lifted opaque cell, empty berth, protected staffed gallery, accessible heat and water services, separate incoming, held, qualified and outgoing residual bays, and external freight" loading="lazy" /></a><figcaption>Supporting section · Schematic K form; qualification and rejection remain human decisions.</figcaption></figure></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><p class="eyebrow">E / S / K BOUNDARY</p><p><strong>E:</strong> inherited Toledo and Great Lakes freight, manufacturing, material, and infrastructure context. <strong>S:</strong> FT-03's conditional exchanges, qualification, external dependencies, and institutional responsibilities. <strong>K:</strong> this crane-hall frontage, removable cell family, optical gallery, material arrangement, and depicted activities. No new canon is created.</p><p>Composite view; no named plant, surveyed site, process specification, compatible stream, structural capacity, throughput, recovery fraction, environmental outcome, or continuous operation is asserted. A residual can remain held, be rejected, or leave for outside handling; qualification does not guarantee use.</p></div><div class="source-box"><p class="eyebrow">FOLLOW THE WORK</p><ul><li><a href="${source('docs/phase_briefs/phase17d_futurist_atlas_synthesis.md')}">Phase 17D synthesis ↗</a></li><li><a href="${source('reports/phase17d_hero_futurescape_concepts.md')}">HF-04 concept and limits ↗</a></li><li><a href="${source('reports/phase17b_lived_world_condition_packets.md')}#ft-03-connected-not-closed">FT-03 scenario packet (S) ↗</a></li><li><a href="${source('reports/phase17d_hf04_final_production_notes.md')}">Production and provenance notes ↗</a></li><li><a href="${path('methods/')}">Methods and claim types ↗</a></li><li><a href="${path('roadmap/')}">Project roadmap ↗</a></li><li><a href="${path('updates/')}">HF-04 update ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><p class="eyebrow">RELATED ATLAS WORK</p><h2>Follow the exchange<br>back to its study.</h2><p><a href="${path('atlas/industrial-exchange/')}">Industrial Exchange ↗</a> is the earlier Phase 17A systems study. It explains selected external inputs, qualification, and governance; this hall is a distinct S/K architectural interpretation.</p><p><a href="${path('atlas/glass-city-2075/')}">Glass City 2075 ↗</a> is the first futurescape and the public visual calibration for this second hero.</p><a class="text-link" href="${path()}#essays">Explore the four systems studies <span aria-hidden="true">↗</span></a></section>
  </div>`, 'atlas');
}

function maumeeBioAg(): string {
  return layout(`<div class="future-page hf03-page">
    <section class="future-opening"><figure><img src="${bioAgWide}" alt="Composite Maumee-derived farm with open crop rows, a folded bio-ag working seam, a farmer maintaining an old drainage gate, a stopped field machine under repair, a supply truck, and a separate ditch and reed wetland" fetchpriority="high" /><figcaption>HF-03 / MAUMEE BIO-AG LANDSCAPE 2075 · Composite Maumee-derived 2075 scenario / K architectural form.</figcaption></figure></section>
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a><p class="eyebrow accent">PHASE 17D / THIRD PUBLISHED FUTURESCAPE</p><h1 class="future-long-title">Maumee Bio-Ag<br><em>Landscape 2075.</em></h1><div class="future-intro-grid"><p class="future-question">What work appears when productive fields, selective cultivation, machine service, and old drainage must share an edge?</p><div class="prose"><p>A composite Maumee-derived farm keeps open crop rows beside a long, folded working seam. Translucent propagation bays alternate with opaque contained work and service access. A farmer clears sediment at an older gate while a technician repairs a stopped field machine; a conventional delivery keeps outside supply visible.</p><p>The ditch and reed wetland remain separate from the contained work. This scene proposes an adaptation with labor, qualification, stewardship, and downstream responsibility; it does not depict a real farm or demonstrate yield, nutrient removal, water treatment, or ecological improvement.</p></div></div></section>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / MAINTENANCE VIEW</p><h2>The gate needs<br>hands and judgment.</h2></div><p>A separately composed close view of sediment clearing, worn water control, muddy access, and the same field-machine repair beyond.</p></div><figure><a href="${bioAgMaintenance}" target="_blank" rel="noopener" aria-label="Open the Maumee Bio-Ag maintenance illustration full size"><img src="${bioAgMaintenance}" alt="Farmer clears reeds and sediment from a weathered drainage gate in wet clay, with ditch water and reeds beyond and a technician servicing a stopped wheeled field machine near the folded seam" loading="lazy" /></a><figcaption>Maintenance view · Routine work in a speculative composite scene; no drainage or treatment outcome is asserted.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / EXPLANATORY SECTION</p><h2>Separate spaces,<br>shared upkeep.</h2></div><p>The inset distinguishes the open field, selective cultivation, machine berth, opaque contained work, hold/reject route, old gate and ditch, wetland edge, and outside supply. Its coordinates describe the display only.</p></div><figure><a href="${bioAgSection}" target="_blank" rel="noopener" aria-label="Open the field, seam and drainage section full size"><img src="${bioAgSection}" alt="Qualitative section of open productive field, translucent propagation, stopped machine service, opaque contained qualification, hold and outward route, maintained old drainage gate and ditch, distinct wetland reeds, and external supplies" loading="lazy" /></a><figcaption>Supporting section · Schematic K form; no measured geometry, process result, or environmental outcome.</figcaption></figure></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><p class="eyebrow">E / S / K BOUNDARY</p><p><strong>E:</strong> inherited Maumee agriculture, drainage, weather, farm work, and ecology. <strong>S:</strong> conditional maintained agricultural adaptation, external inputs, labor, qualification, stewardship, and downstream responsibility. <strong>K:</strong> the folded seam, modules, crop envelope, machinery, gate juxtaposition, workers, and exact spatial arrangement. No new canon is created.</p><p>No real farm, Great Black Swamp candidate geometry, engineered organism release, measured yield or nutrient capture, water treatment, ecological benefit, safe containment certification, or closed self-sufficient loop is claimed. GBI-03 Adaptive Crop / Propagation Envelope is an S/K invention entry, not canon; the Bio-Ag Edge Processing Module remains provisional.</p></div><div class="source-box"><p class="eyebrow">FOLLOW THE WORK</p><ul><li><a href="${source('docs/phase_briefs/phase17d_futurist_atlas_synthesis.md')}">Phase 17D synthesis ↗</a></li><li><a href="${source('reports/phase17d_hero_futurescape_concepts.md')}">HF-03 concept and limits ↗</a></li><li><a href="${source('reports/phase17d_hf03_composition_studies.md')}">C / C-L1 composition lineage ↗</a></li><li><a href="${source('docs/phase_briefs/phase17d_glass_basin_invention_catalog.md')}">Invention catalog ↗</a></li><li><a href="${source('reports/phase17d_hf03_final_production_notes.md')}">Production and provenance notes ↗</a></li><li><a href="${path('methods/')}">Methods and claim types ↗</a></li><li><a href="${path('roadmap/')}">Project roadmap ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><p class="eyebrow">RELATED ATLAS WORK</p><h2>Three different<br>working futurescapes.</h2><p><a href="${path('atlas/glass-city-2075/')}">Glass City 2075 ↗</a> follows a maintained Toledo-derived street canopy. <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075 ↗</a> follows staffed exchange inside an older hall. This Maumee-derived scene extends the visual language into fields, clay, drainage, and reeds.</p><a class="text-link" href="${path()}#essays">Explore the earlier systems studies <span aria-hidden="true">↗</span></a></section>
  </div>`, 'atlas');
}

function lakeErieCoast(): string {
  return layout(`<div class="future-page hf02-page">
    <section class="future-opening"><figure><img src="${coastWide}" alt="Composite Lake Erie and Toledo-derived working coast: a long stepped service terrace, technician replacing a weather screen, grounded civilian environmental survey craft in a dry cradle, working quay and open windy lake" fetchpriority="high" /><figcaption>Lead image · Composite Lake Erie / Toledo-derived 2075 scenario and design concept.</figcaption></figure></section>
    <section class="section-shell future-intro"><a class="back-link" href="${path()}#futurescapes">← All futurescapes</a><p class="eyebrow accent">FOURTH PUBLISHED FUTURESCAPE</p><h1 class="future-long-title">Lake Erie Energy &amp;<br><em>Security Coast 2075.</em></h1><div class="future-intro-grid"><p class="future-question">What does advanced energy and observation look like when every connection faces lake weather, needs repair, and crosses distinct responsibilities?</p><div class="prose"><p>A composite working coast has become a low, stepped service terrace. Protected inspection and comparison space sits behind replaceable weather screens; opaque energy and utility rooms are separated from a dry recovery berth and an exposed quay. A stopped civilian environmental survey craft is brought ashore for service while ordinary utility and waterfront work continues.</p><p>Wind, whitecaps, corrosion and occasional fouling make maintenance visible. Staffed thresholds make the access boundary legible; they do not imply uninterrupted service. This is a speculative composite, not a real facility, survey, forecast or energy-technology selection.</p></div></div></section>
    <section class="section-shell future-detail"><div class="section-head"><div><p class="eyebrow">02 / WORKING DETAIL</p><h2>A screen wears.<br>A person replaces it.</h2></div><p>A separately composed close view of a technician changing a cloudy sacrificial screen while a returned environmental sensor case is brought to a comparison bench.</p></div><figure><a href="${coastMaintenance}" target="_blank" rel="noopener" aria-label="Open the working-detail illustration full size"><img src="${coastMaintenance}" alt="Technician at reachable height replaces a cloudy, fouled protective inspection screen with tools and an old panel nearby; another worker examines a returned environmental survey sensor case at a bench; windy Lake Erie is beyond" loading="lazy" /></a><figcaption>Working detail · Human servicing and comparison, not proof of successful calibration or an engineered procedure.</figcaption></figure></section>
    <section class="section-shell future-section"><div class="section-head"><div><p class="eyebrow">03 / HOW IT WORKS</p><h2>Protected work,<br>exposed edge.</h2></div><p>The qualitative inset follows the service terrace from land to lake. Its numbered key is repeated below as readable page text; the drawing's coordinates describe only the graphic.</p></div><figure><a href="${coastSection}" target="_blank" rel="noopener" aria-label="Open the lake-edge service-terrace inset full size"><img src="${coastSection}" alt="Qualitative land-to-lake service-terrace section with six numbered groups; the corresponding descriptions follow the image" loading="lazy" /></a><figcaption>How it works · Qualitative section; its numbered groups are described below. No measured geometry or demonstrated performance.</figcaption></figure><ol class="hf02-inset-callouts" aria-label="Six areas in the lake-edge service-terrace inset"><li><strong>01 / Access + supply</strong><span>A staffed handoff marks a controlled access boundary between the landward service approach and terrace; outside utilities remain external.</span></li><li><strong>02 / Utility + isolation</strong><span>Separate opaque energy and utility rooms keep services distinct and allow an unavailable bay; no energy type or output is specified.</span></li><li><strong>03 / Screen + comparison</strong><span>A replaceable weather screen protects a staffed comparison and calibration workspace for returned sensor equipment; no calibration result is implied.</span></li><li><strong>04 / Survey recovery</strong><span>A stopped civilian environmental-survey craft rests in a dry recovery cradle and depends on human retrieval and repair.</span></li><li><strong>05 / Quay + fouling</strong><span>The exposed working quay meets the wetted edge; subtle biological fouling and weathering indicate upkeep, not abundance or control.</span></li><li><strong>06 / Lake Erie</strong><span>Open lake water brings wind and wave exposure; the section is not a surveyed shoreline and does not establish resilience.</span></li></ol></section>
    <section class="section-shell future-boundary"><div class="boundary-box"><p class="eyebrow">SCENARIO / DESIGN BOUNDARY</p><p>The scene draws on inherited Lake Erie and Toledo waterfront, utility, port, weather, fouling, and environmental-observation context. Its maintained energy, observation, recovery, labor, access, and institutional relationships are conditional scenario dependencies. The terrace/cradle geometry, inspection gallery, energy-service arrangement, craft, operating scene, and depicted workers are design concepts. This page introduces no new canon.</p><p>No real facility, co-location with the Toledo intake crib, surveyed future siting or sightline, exact future energy mix or output, weather tolerance, continuous observation, successful calibration, redundancy, treatment result, security effectiveness, or deployment is asserted. The equipment and work shown are a visual proposition, not an operating instruction.</p></div><div class="source-box"><p class="eyebrow">EVIDENCE / METHODS</p><ul><li><a href="${source('docs/phase_briefs/phase17d_futurist_atlas_synthesis.md')}">Futurescape concepts ↗</a></li><li><a href="${source('reports/phase17d_hero_futurescape_concepts.md')}">Concept background and limits ↗</a></li><li><a href="${source('reports/phase17d_hf02_composition_studies.md')}">Visual study record ↗</a></li><li><a href="${source('reports/phase17d_three_hero_visual_retrospective.md')}">Visual-learning retrospective ↗</a></li><li><a href="${source('docs/phase_briefs/phase17d_glass_basin_invention_catalog.md')}">Invention candidate catalog ↗</a></li><li><a href="${path('methods/')}">Methods and claim types ↗</a></li><li><a href="${path('roadmap/')}">Project roadmap ↗</a></li></ul></div></section>
    <section class="section-shell future-related"><p class="eyebrow">RELATED ATLAS WORK</p><h2>A working coast<br>in a wider basin.</h2><p><a href="${path('atlas/glass-city-2075/')}">Glass City 2075 ↗</a>, <a href="${path('atlas/maumee-bio-ag-2075/')}">Maumee Bio-Ag Landscape 2075 ↗</a>, and <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075 ↗</a> show distinct maintained sections of the same speculative 2075 setting.</p><p><a href="${path('atlas/toledo-crib/')}">The Toledo Intake Crib study ↗</a> is a separate existing reference asset. No co-location with the crib or surveyed future site is asserted.</p></section>
  </div>`, 'atlas');
}

function methods(): string {
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">THE WORK BEHIND THE IMAGES</p><h1>Methods<br><em>& credits.</em></h1><p>This preview is an editorial selection from a larger research repository. Its figures show what the project can support and where interpretation begins.</p></section>
  <section class="section-shell method-block"><div class="section-label"><span class="rule-number">01</span> FOUR CLAIM TYPES</div><div class="method-grid"><div><h2>Keep the layers legible.</h2><p>Every figure carries an evidence status and a medium. A map, schematic, model, or concept drawing answers a different question; its appearance does not change the status of the underlying claim.</p></div><div class="definition-list"><div><b class="evidence">E</b><span><strong>Evidence / model</strong>Sourced observation or reproducibly derived current-system information.</span></div><div><b class="scenario">S</b><span><strong>Scenario</strong>A qualitative future exploration. It is not a prediction or a probability.</span></div><div><b class="canon">C</b><span><strong>Canon</strong>A chosen fact of the fictional setting. No new canon is created in this preview.</span></div><div><b class="sketch">K</b><span><strong>Sketch</strong>Provisional design, character, or narrative material.</span></div></div></div></section>
  <section class="section-shell method-block"><div class="section-label"><span class="rule-number">02</span> PUBLIC READING ORDER</div><div class="reading-order-grid"><article><p class="eyebrow">HERO FUTURESCAPE</p><h3>A speculative place to enter.</h3><p>A composite 2075 scene leads with lived space and visible technological change. It is scenario/sketch material, not a verified deployment or engineering proposal.</p></article><article><p class="eyebrow">SYSTEM EXPLANATION</p><h3>Show how the place works.</h3><p>System insets explain interfaces, maintenance, dependencies, and boundaries. The Lake Erie service-terrace inset is paired with six numbered HTML summaries readable on narrow screens; the diagram remains qualitative and does not establish measured performance.</p></article><article><p class="eyebrow">EVIDENCE / METHODS</p><h3>Keep the support traceable.</h3><p>Phase 17A studies, source records, reproducible methods, and frozen scientific baselines remain available as the Atlas’s evidence and systems-support layer.</p></article></div><p class="method-boundary">The published <a href="${path('atlas/glass-city-2075/')}">Glass City</a>, <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism</a>, <a href="${path('atlas/maumee-bio-ag-2075/')}">Maumee Bio-Ag</a>, and <a href="${path('atlas/lake-erie-energy-security-coast-2075/')}">Lake Erie Energy &amp; Security Coast</a> futurescapes remain composite scenario/design concepts. Six adjacent HTML callouts support mobile reading of the accepted Lake Erie system inset; that presentation does not imply migration of older insets. GBI-03 Adaptive Crop / Propagation Envelope is established; the Bio-Ag Edge Processing Module remains provisional. No yield, nutrient-removal, ecological-benefit, containment-success, adoption, or new-C claim is made, and the scientific baseline is unchanged.</p></section>
  <section class="section-shell method-block"><div class="section-label"><span class="rule-number">03</span> SOURCE TO FIGURE</div><div class="method-grid"><div><h2>Research remains traceable.</h2><p>The accepted science packages use public-source records, builders, validators, manifests, reviews, and freeze records. The Phase 17A illustrations add reader-facing interpretation while keeping their source gates and limitations documented.</p></div><div class="prose"><p>The research spans water, geology, energy, freight, ecology, health, climate, governance, population, technology, and their dependencies. Phase 14 organizes these into 13 Atlas system families; Phase 16 tests bounded stress pathways.</p><p>Qualitative lines and colors do not encode measured load, probability, performance, or severity unless a figure explicitly says so. A scenario diagram does not certify a real deployment or future outcome.</p><p><a href="${source('metadata/sources.yml')}">Source registry ↗</a> · <a href="${source('reports/README.md')}">Validation and report index ↗</a> · <a href="${source('docs/canon_status.md')}">Canon status ↗</a></p></div></div></section>
  <section class="section-shell method-block"><div class="section-label"><span class="rule-number">04</span> CREDITS & RIGHTS</div><div class="method-grid"><div><h2>Built from shared records,<br>drawn for this Atlas.</h2><p>Original site design, editorial text, and prototype drawings are part of Western Basin Worldbuilding. Source data and third-party imagery retain their own terms and attribution.</p></div><div class="prose"><p>Research sources documented in the repository include <a href="https://www.usgs.gov/3d-hydrography-program/access-3dhp-data-products">USGS hydrography ↗</a>, <a href="https://www.epa.gov/tmdl/epas-approval-ohios-maumee-watershed-nutrient-total-maximum-daily-load">US EPA's Maumee nutrient TMDL ↗</a>, <a href="https://coastalscience.noaa.gov/science-areas/habs/hab-forecasts/lake-erie/">NOAA's Lake Erie HAB work ↗</a>, and <a href="https://toledo.oh.gov/departments/public-works/water/water-treatment">City of Toledo water treatment ↗</a>, alongside other public records. Individual figure manifests and source reports identify the inputs used for each prototype.</p><p>The current Toledo intake crib coordinate uses the U.S. Coast Guard Light List, corroborating NOAA/NDBC observation evidence, and aerial review. The third-party source photograph is omitted from this web build because its reuse rights are not confirmed. Great Black Swamp held geometry and its reference image are also excluded.</p><p>The repository's MIT license covers its original code and documentation; it does not relicense third-party data or imagery. See the <a href="${source('docs/references/DATA_AND_ASSET_LICENSING.md')}">data and asset licensing notes ↗</a> and each essay’s source links for detail.</p></div></div></section>
  <section class="section-shell end-cta"><p class="eyebrow">CONTINUE EXPLORING</p><h2>System studies. One connected basin.</h2><a class="button button-primary" href="${path()}#essays">Browse the Atlas <span aria-hidden="true">↗</span></a></section>`, 'methods');
}

function roadmap(): string {
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">PROJECT ROADMAP / REVIEWED SEPTEMBER 2026</p><h1>From a basin model<br>to an <em>inhabited world.</em></h1><p>This page tracks the current work. Earlier phase briefs preserve their at-the-time wording; the status record and canon register carry the latest disposition.</p></section>
  <section class="section-shell roadmap-section"><div class="section-label"><span class="rule-number">01</span> WHERE WE ARE</div><div class="timeline">
    <div class="timeline-item"><span class="timeline-status done">FROZEN</span><div><h2>Phases 1–16 <small>Scientific & systems foundation</small></h2><p>Environmental, infrastructure, population, health, governance, technology, shared Atlas ontology, and bounded cross-system stress tests are complete, accepted, and frozen.</p></div></div>
    <div class="timeline-item"><span class="timeline-status done">ACCEPTED</span><div><h2>Phase 17A <small>Atlas prototype pattern</small></h2><p>Four static visual sets are accepted as analytical and concept components. Visual Grammar v0.3 is accepted for prototype use; Phase 17D has separate public futurescape style guidance.</p></div></div>
    <div class="timeline-item"><span class="timeline-status done">ACCEPTED</span><div><h2>Phase 17B <small>Initial future-world translation</small></h2><p>Fifteen seed units and seven lived-world condition packets are complete and accepted for development. Their future conditions remain scenario or sketch material, without canon promotion.</p></div></div>
    <div class="timeline-item"><span class="timeline-status done">DEVELOPMENT MATERIAL</span><div><h2>Phase 17C <small>Character & narrative architecture</small></h2><p>Ten role seeds, nine relationships, and six narrative-thread seeds are accepted for development. Ordinary-day tests remain separate and provisional; no final cast or new canon is selected.</p></div></div>
    <div class="timeline-item"><span class="timeline-status active">ACTIVE</span><div><h2>Phase 17D <small>Public futurescape visual development</small></h2><p><a href="${path('atlas/glass-city-2075/')}">Glass City 2075</a>, <a href="${path('atlas/industrial-metabolism-2075/')}">Industrial Metabolism 2075</a>, <a href="${path('atlas/maumee-bio-ag-2075/')}">Maumee Bio-Ag Landscape 2075</a>, and <a href="${path('atlas/lake-erie-energy-security-coast-2075/')}">Lake Erie Energy &amp; Security Coast 2075</a> are the four accepted/published futurescapes. The Lake Erie scene retains a civilian environmental-survey interpretation and is a composite scenario/design concept, not a construction proposal or performance claim. Phase 17D remains active, with HF-05 as future work. These futurescapes do not create new canon; Phase 17A studies remain the supporting systems material.</p></div></div>
  </div></section>
  <section class="status-band"><div class="section-shell status-grid"><div><p class="eyebrow accent">OPEN BOUNDARIES</p><h2>What remains<br>undecided.</h2></div><div><p>The Great Black Swamp geometry remains on hold and noncanonical. The crib's physical location is resolved, but the future retrofit is speculative. Phase 17B and 17C material has not been promoted to fictional canon. Phase 17D futurescape architecture remains S/K concept material, with no new C. This preview is a curated publication layer, not a new science or canon decision.</p><a class="button button-outline" href="${source('PROJECT_STATUS.md')}">Detailed status record ↗</a> <a class="text-link" href="${path('updates/')}">Project updates <span aria-hidden="true">↗</span></a></div></div></section>
  <section class="section-shell end-cta"><p class="eyebrow">START WITH THE WORK</p><h2>See the accepted visual studies.</h2><a class="button button-primary" href="${path()}#essays">Explore the Atlas <span aria-hidden="true">↗</span></a></section>`, 'roadmap');
}

function updates(): string {
  return layout(`<section class="plain-hero section-shell"><p class="eyebrow accent">PROJECT UPDATES / FUTURESCAPE DEVELOPMENT</p><h1>Work in<br><em>development.</em></h1><p>A dated log of public Atlas milestones. Each entry states what has been produced and keeps future concepts separate from evidence and canon.</p></section>
  <section class="section-shell updates-section"><div class="section-label"><span class="rule-number">01</span> RECENT UPDATES</div>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-28">28 September 2026</time><span class="update-status">FOURTH PUBLISHED FUTURESCAPE</span></div><div><h2>Lake Erie Energy &amp; Security Coast 2075 is published</h2><p>The fourth futurescape pairs an accepted lead image and working detail with a qualitative “How it works” system inset and six matching HTML callouts. The civilian environmental-survey interpretation is clear. This composite Lake Erie / Toledo-derived scenario and design concept makes no claim about real construction, surveyed siting, co-location with the Toledo intake crib, a future energy mix, continuity, treatment, or security performance; it creates no new canon.</p><div class="update-links"><a href="${path('atlas/lake-erie-energy-security-coast-2075/')}">Explore the Lake Erie coast ↗</a><a href="${path('methods/')}">Methods and claim types ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-28">28 September 2026</time><span class="update-status">HF-03 ACCEPTED / PUBLISHED · THIRD HERO SET</span></div><div><h2>Maumee Bio-Ag Landscape 2075 is published</h2><p>The third Phase 17D hero set pairs a wide image, a separately composed drainage-gate maintenance view, and a qualitative field-seam section. Human review accepted composition C — Bio-Ag Seam Dominant, light/weather C-L1 — Bright Broken Cloud, and the public claims; publication was authorized. The composite Maumee-derived scene remains S/K and creates no new canon. It demonstrates the Glass Basin style beyond brick/steel industrial Toledo without claiming a real farm, yield, nutrient removal, ecological benefit, containment success, or adoption.</p><div class="update-links"><a href="${path('atlas/maumee-bio-ag-2075/')}">Explore the HF-03 hero ↗</a><a href="${source('docs/phase_briefs/phase17d_glass_basin_invention_catalog.md')}">GBI-03 invention catalog ↗</a><a href="${source('reports/phase17d_hf03_final_production_notes.md')}">Production notes ↗</a><a href="${path('methods/')}">Methods ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-28">28 September 2026</time><span class="update-status">TWO-HERO RETROSPECTIVE · EARLIER MILESTONE</span></div><div><h2>HF-03 was selected as the next visual experiment</h2><p>At this earlier checkpoint, the two-hero retrospective selected HF-03 as the next visual composition experiment. Final production had not yet begun at that point. HF-02 remained an alternative and HF-05 later in sequence; production order was not a ranking of futures. No new C was created.</p><div class="update-links"><a href="${source('reports/phase17d_two_hero_visual_retrospective.md')}">Visual retrospective ↗</a><a href="${source('docs/phase_briefs/phase17d_glass_basin_invention_catalog.md')}">Invention catalog ↗</a><a href="${path('roadmap/')}">Roadmap ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-28">28 September 2026</time><span class="update-status">HF-04 HERO SET IN ATLAS BUILD</span></div><div><h2>Industrial Metabolism 2075 joins the futurescapes</h2><p>The second Phase 17D hero set now pairs an old crane hall and tall replaceable exchange frontage with a separate maintenance view and qualitative qualification section. Its staffed acceptance, held material, outside freight, and accessible services are S/K propositions. No real plant, successful exchange, throughput, recovery, or environmental outcome is asserted.</p><div class="update-links"><a href="${path('atlas/industrial-metabolism-2075/')}">Explore Industrial Metabolism ↗</a><a href="${source('reports/phase17d_hf04_final_production_notes.md')}">Production notes ↗</a><a href="${path('roadmap/')}">Roadmap ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-27">27 September 2026</time><span class="update-status">HF-01 HERO SET IN ATLAS BUILD</span></div><div><h2>Glass City 2075 gains a public-facing hero set</h2><p>The first Phase 17D futurescape gained a wide illustration, a distinct maintenance view, and a qualitative canopy section in the Atlas build. The Toledo-derived street is a composite S/K concept, not a real project or a claim of optical, cooling, or structural performance. At this earlier milestone, HF-04 had no produced image or page.</p><div class="update-links"><a href="${path('atlas/glass-city-2075/')}">Explore Glass City ↗</a><a href="${source('reports/phase17d_hf01_final_production_notes.md')}">Production notes ↗</a><a href="${path('methods/')}">Methods ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-27">27 September 2026</time><span class="update-status">DIRECTION ESTABLISHED</span></div><div><h2>Phase 17D futurist visual direction established</h2><p>The Atlas is moving toward hero-led 2075 futurescapes, followed by system explanation and evidence/methods. The established visual guidance is for presentation; Phase 17D remains S/K development material with no new C. Existing Phase 17A studies remain the scientific and systems-support layer.</p><div class="update-links"><a href="${source('docs/phase_briefs/phase17d_public_visual_style_guide.md')}">Public visual style guide ↗</a><a href="${path('roadmap/')}">Roadmap ↗</a><a href="${path('methods/')}">Methods ↗</a></div></div></article>
    <article class="update-entry"><div class="update-meta"><time datetime="2026-09-27">27 September 2026</time><span class="update-status">EARLIER DEVELOPMENT MILESTONE</span></div><div><h2>HF-01 Glass City 2075 enters visual development</h2><p>The procedural study established the canopy's spatial and maintenance logic but was not selected as the public hero. HF-01 was chosen as the first futurescape; HF-04 remained second in sequence.</p><div class="update-links"><a href="${source('docs/phase_briefs/phase17d_hf01_hf04_production_plan.md')}">HF-01 / HF-04 production plan ↗</a><a href="${path('roadmap/')}">Roadmap ↗</a></div></div></article>
  </section>`, 'updates');
}

const essay = essays.find((item) => item.key === page as EssayKey);
root.innerHTML = essay ? essayView(essay) : page === 'glass-city' ? glassCity() : page === 'industrial-metabolism' ? industrialMetabolism() : page === 'maumee-bio-ag' ? maumeeBioAg() : page === 'lake-erie-coast' ? lakeErieCoast() : page === 'methods' ? methods() : page === 'roadmap' ? roadmap() : page === 'updates' ? updates() : home();
