import type { EssayKey } from './content';

const studies: Record<EssayKey, { id: string; title: string; content: string }[]> = {
  field: [
    { id: 'route', title: 'Follow the water', content: `<p>A field, a drainage system, a tributary, the Maumee, then a nearshore interface. This is a generalized sequence of places; it does not trace one measured parcel of water.</p><ol class="reading-steps"><li><strong>Field and soil</strong><span>Water can mobilize material near its source.</span></li><li><strong>Drainage and small channels</strong><span>Movement begins through a network that the map only partly represents.</span></li><li><strong>Tributaries and the Maumee</strong><span>Transport, retention and transformation can occur along the way.</span></li><li><strong>Nearshore interface</strong><span>Delivery reaches receiving water; the lake has its own conditions.</span></li></ol><p>Regulated point-source discharge is a separate pathway. No discharge pipe is invented in this generalized field sequence.</p>` },
    { id: 'constituents', title: 'Different passengers', content: `<p>Water is the carrier. Phosphorus, nitrogen, organic matter and sediment need distinct explanations, even when a source represents some of the same process categories.</p><div class="reading-table"><table><caption>Process categories represented in the retained study</caption><thead><tr><th scope="col">Track</th><th scope="col">Represented processes</th></tr></thead><tbody><tr><th scope="row">Water / carrier</th><td>Transport</td></tr><tr><th scope="row">Phosphorus</th><td>Mobilization; transport; retention or transformation; delivery; discharge; receiving-water context</td></tr><tr><th scope="row">Nitrogen</th><td>Mobilization; transport; retention or transformation; delivery; discharge; receiving-water context</td></tr><tr><th scope="row">Carbon / organic matter</th><td>Mobilization; transport; delivery; discharge; receiving-water context</td></tr><tr><th scope="row">Sediment</th><td>Transport; retention or transformation; delivery</td></tr></tbody></table></div><p class="reading-note">A process absent from this source is not necessarily absent in nature. Shared categories establish no equal rate, form or fate. Carbon here is organic-matter context, rather than a greenhouse-gas inventory.</p>` },
    { id: 'lake', title: 'The lake is another question', content: `<p>Watershed delivery meets physical, chemical and biological receiving-water conditions. It may contribute to conditions favorable to a bloom; it does not create an inevitable nutrient-to-bloom result.</p><blockquote>Reaching the lake is a boundary in the explanation, rather than the end of the science.</blockquote><p>Harmful algal blooms belong to receiving-water context. They are not another constituent moving down a single pipe.</p>` },
    { id: 'record', title: 'Inspect a real observation', content: `<p>The Waterville record lets you select a day and see how much water passed one real gauge. A nutrient load would also need compatible concentration measurements.</p><a class="text-link" href="${import.meta.env.BASE_URL}maps/?mode=real#river-record">A day on the Maumee ↗</a>` },
  ],
  crib: [
    { id: 'landmark', title: 'One physical landmark', content: `<p>The offshore Toledo intake crib has a resolved physical position: <strong>41.699444, −83.259167</strong>. Nearby monitoring and legacy dataset coordinates describe different records.</p><p>The sketch interprets a recognizable structure without measured dimensions. Both views share an approximate older body; equipment added to the future view remains imagined.</p>` },
    { id: 'changes', title: 'What persists, changes and arrives', content: `<div class="reading-comparison"><article><span class="eyebrow">PERSISTS</span><h3>A recognizable core</h3><p>The physical site, crib body and lake setting anchor the interpretation.</p></article><article><span class="eyebrow">MODIFIED</span><h3>Ways of working</h3><p>Access, monitoring and operating arrangements could change around the older structure.</p></article><article><span class="eyebrow">ADDED / IMAGINED</span><h3>Equipment at the edge</h3><p>A sensor mast, communications module, inspection interface and service additions introduce new dependencies.</p></article></div>` },
    { id: 'upkeep', title: 'A device needs a visit', content: `<p>Sensing and communications remain tied to power, access, maintenance and responsible institutions. A speculative service or resilience interface supplies no demonstrated capability.</p><blockquote>Older infrastructure can persist while the work around it changes.</blockquote><p>The drawing is a visual concept, without a design proposal, certified access, capacity or security performance for the real water works.</p>` },
  ],
  farm: [
    { id: 'spaces', title: 'Keep the working spaces distinct', content: `<p>The study’s synthetic farm keeps cultivation as its primary land use. Drainage, storage, habitat, service roads and equipment still take room and require upkeep.</p><ul><li>Open fields and selective cultivation can coexist.</li><li>Equipment needs stopped time, access and replacement parts.</li><li>Drainage, possible storage and wetland relationships require separate explanation.</li><li>Held material and outward movement remain possible.</li></ul><p>The related device sketch shows the later illustrated working seam. It does not turn the earlier synthetic parcel into a surveyed layout.</p>` },
    { id: 'water', title: 'A gate is a decision point', content: `<ol class="reading-steps"><li><strong>Observe</strong><span>A sensor supplies a record, with limits.</span></li><li><strong>Decide</strong><span>A responsible person interprets it and chooses an action.</span></li><li><strong>Maintain</strong><span>Inspect, clear, repair or replace the gate and its working parts.</span></li><li><strong>Follow downstream</strong><span>Water and nutrients can leave the farm. Their movement and possible retention are different questions.</span></li></ol><p>Timing may be managed and reuse may be partial. A device or wetland in a drawing demonstrates no nutrient capture or treatment result.</p>` },
    { id: 'dependencies', title: 'What crosses the farm boundary?', content: `<div class="reading-table"><table><caption>Operating dependencies in the synthetic farm study</caption><thead><tr><th scope="col">Need</th><th scope="col">Work inside</th><th scope="col">Crossing the boundary</th></tr></thead><tbody><tr><th scope="row">Water</th><td>Field, drainage, storage</td><td>Rain or supplemental input; downstream export</td></tr><tr><th scope="row">Nutrients</th><td>Soil, crops, possible retention</td><td>Inputs; products, residuals and nutrient export</td></tr><tr><th scope="row">Energy</th><td>Pumps, cultivation equipment, possible storage</td><td>Grid, fuel and replacement equipment</td></tr><tr><th scope="row">Ecology</th><td>Buffers, perennial strips, wetland</td><td>Regional habitat and uncertain response</td></tr><tr><th scope="row">Information</th><td>Sensor, record, human decision, gate</td><td>Data and institutional dependencies</td></tr><tr><th scope="row">Maintenance</th><td>Inspect, clean, repair, replace</td><td>People, parts, service and residual handling</td></tr></tbody></table></div>` },
    { id: 'limits', title: 'A possible farm', content: `<p>No real parcel, adoption rate, yield, profitability or nutrient-removal efficiency is established. Black Swamp Country is a regional identity; the held historical swamp boundary is not used.</p><blockquote>Keeping a farm working is a chain of actions, rather than a single new machine.</blockquote>` },
  ],
  industry: [
    { id: 'connections', title: 'Read the connections by kind', content: `<div class="reading-table"><table><caption>Selected relationships in the synthetic district</caption><thead><tr><th scope="col">Kind</th><th scope="col">What the connection means</th></tr></thead><tbody><tr><th scope="row">Outside physical inputs</th><td>Grid or fuel, water, materials and freight enter operating systems.</td></tr><tr><th scope="row">Possible internal exchange</th><td>Energy use, material recovery, treated-water reuse or waste-heat interfaces remain conditional.</td></tr><tr><th scope="row">Information</th><td>Records, monitoring and inspection inform decisions; data alone transfers no material.</td></tr><tr><th scope="row">Institutional dependency</th><td>Contracts, standards, permits and operating agreements make an exchange possible.</td></tr></tbody></table></div><p>Physical exchange, information and institutional dependency are different kinds of connection. None supplies a measured quantity or a guaranteed exchange.</p>` },
    { id: 'qualification', title: 'Before something can be used again', content: `<ol class="reading-steps"><li><strong>A residual arrives</strong><span>Its existence does not make it a resource.</span></li><li><strong>Characterize and, if appropriate, reprocess</strong><span>Composition, condition and treatment determine what might be recovered.</span></li><li><strong>Qualify for a compatible user</strong><span>Specification, traceability, quality assurance and an agreement are needed.</span></li><li><strong>A possible new input</strong><span>A qualified material may still lack a user. Rejection and off-site handling remain possible.</span></li></ol><blockquote>Residual ≠ recoverable resource ≠ qualified input.</blockquote>` },
    { id: 'checks', title: 'Conditions that must line up', content: `<div class="reading-comparison"><article><h3>Material exchange</h3><p>Composition, condition, traceability, specification, quality checks and contract.</p></article><article><h3>Thermal exchange</h3><p>Temperature, timing and distance, alongside operating compatibility.</p></article><article><h3>Working continuity</h3><p>Inspection, repair, replacements and a plan for interruption or refusal.</p></article></div>` },
    { id: 'boundaries', title: 'An open district', content: `<p>Energy, materials, water and freight enter. Products, residuals and discharge can leave. Monitoring, permitting, data sharing and maintenance continue across those boundaries.</p><p>The related crane-hall sketch gives this work an architectural setting; it is a later composite concept, rather than the original district plan or a real factory.</p><blockquote>More connection does not establish self-sufficiency.</blockquote><p>No actual company, parcel, throughput, compatibility, economics, environmental benefit or continuous operation follows from this study.</p>` },
  ],
};

export function studyReading(key: EssayKey): string {
  const sections = studies[key];
  return `<section class="section-shell study-reading" id="read-the-study"><nav class="study-contents" aria-label="Study contents"><p class="eyebrow">IN THIS STUDY</p>${sections.map((section, i) => `<a href="#study-${section.id}"><span>${String(i + 1).padStart(2, '0')}</span>${section.title}</a>`).join('')}</nav><div class="study-chapters">${sections.map((section, i) => `<article id="study-${section.id}" class="study-chapter"><p class="eyebrow accent">${String(i + 1).padStart(2, '0')}</p><h2>${section.title}</h2>${section.content}</article>`).join('')}</div></section>`;
}
