args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)

nodes_path <- file.path(root, "data", "processed", "networks", "observation_system_nodes.csv")
edges_path <- file.path(root, "data", "processed", "networks", "observation_system_edges.csv")
metadata_path <- file.path(root, "metadata", "sources.yml")
map_png <- file.path(root, "outputs", "maps", "systems", "14_observation_decision_system_2026.png")
map_svg <- file.path(root, "outputs", "maps", "systems", "14_observation_decision_system_2026.svg")
validation_png <- file.path(root, "outputs", "figures", "observation_system_R_validation.png")

nodes <- read.csv(nodes_path, stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
edges <- read.csv(edges_path, stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
required_nodes <- c("node_id", "name", "domain", "node_type", "status", "organization", "latitude", "longitude", "spatial_role", "source_id", "confidence", "notes")
required_edges <- c("edge_id", "from_id", "to_id", "relationship_type", "relationship_basis", "source_id", "confidence", "notes")
stopifnot(setequal(names(nodes), required_nodes), setequal(names(edges), required_edges))
stopifnot(nrow(nodes) == 25, nrow(edges) == 21)
stopifnot(!anyDuplicated(nodes$node_id), !anyDuplicated(edges$edge_id))
stopifnot(all(nodes$domain %in% c("lake_erie_hab", "maumee_hydrology", "environmental_regulatory", "energy_information")))
stopifnot(all(nodes$node_type %in% c("physical_system", "sensor_or_station", "observation_network", "data_product", "model_or_forecast", "decision_organization", "operational_response")))
stopifnot(all(edges$from_id %in% nodes$node_id), all(edges$to_id %in% nodes$node_id))
stopifnot(all(nchar(nodes$source_id) > 0), all(nchar(edges$source_id) > 0))
stopifnot(all(nodes$confidence %in% c("high", "medium", "low")), all(edges$confidence %in% c("high", "medium", "low")))
stopifnot(all(edges$relationship_basis %in% c("observed", "documented", "qualified_documented", "inferred", "engineering_dependency")))
stopifnot(!any(grepl("trigger|automated|control", tolower(edges$relationship_type))))
stopifnot(!any(grepl("2050|2075|scenario|fictional", tolower(nodes$status))))
coords <- nodes[!is.na(nodes$latitude) | !is.na(nodes$longitude), ]
stopifnot(nrow(coords) == 2, all(coords$node_type == "sensor_or_station"))
stopifnot(all(as.numeric(coords$latitude) >= -90), all(as.numeric(coords$latitude) <= 90))
stopifnot(all(as.numeric(coords$longitude) >= -180), all(as.numeric(coords$longitude) <= 180))
metadata <- readLines(metadata_path, warn = FALSE)
for (source_id in unique(c(nodes$source_id, edges$source_id))) {
  stopifnot(any(grepl(paste0("^  ", source_id, ":"), metadata, fixed = FALSE)))
}
stopifnot(all(file.exists(c(map_png, map_svg))))
stopifnot(file.info(map_png)$size > 10000, file.info(map_svg)$size > 10000)
stopifnot(any(grepl("<svg", readLines(map_svg, warn = FALSE), fixed = TRUE)))
stopifnot(all(c("A", "B", "C", "D") %in% sub("^OBS-([A-D]).*", "\\1", edges$edge_id)))

png(validation_png, width = 1600, height = 900, res = 150, bg = "#f1eadc")
par(mar = c(9, 5, 4, 2), bg = "#f1eadc", fg = "#263238")
counts <- table(factor(nodes$node_type, levels = c("physical_system", "sensor_or_station", "observation_network", "data_product", "model_or_forecast", "decision_organization", "operational_response")))
barplot(counts, las = 2, col = c("#527e8b", "#a8a92e", "#5b8d72", "#2d7fa6", "#8b65a5", "#c37d32", "#b65c48"), border = NA, ylab = "Node count", main = "Phase 4A observation-to-decision baseline validation")
mtext("Independent R check: 25 nodes, 21 edges, four representative chains; abstract interfaces remain schematic", side = 1, line = 6, cex = 0.8)
dev.off()
cat("R Phase 4A observation-system validation passed: 25 nodes, 21 edges, four chains\n")
