args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[[1]] else normalizePath(file.path(dirname(sys.frame(1)$ofile), "../../.."), mustWork=FALSE)
read_csv <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE, na.strings=c(""))
N <- read_csv(file.path(root,"data/processed/networks/climate_hazard_nodes.csv"))
E <- read_csv(file.path(root,"data/processed/networks/climate_hazard_edges.csv"))
O <- read_csv(file.path(root,"data/processed/analysis/climate_hazard_observations.csv"))
S <- read_csv(file.path(root,"data/processed/analysis/climate_hazard_sources.csv"))
stopifnot(nrow(N)==26, nrow(E)==30, nrow(O)==28, nrow(S)==21)
stopifnot(length(unique(N$node_id))==26, length(unique(E$edge_id))==30, length(unique(O$observation_id))==28, length(unique(S$source_id))==21)
stopifnot(length(unique(S$url))==21)
stopifnot(all(N$source_id %in% S$source_id), all(E$source_id %in% S$source_id), all(O$source_id %in% S$source_id))
stopifnot(all(E$from_id %in% N$node_id), all(E$to_id %in% N$node_id))
stopifnot(all(N$reality_status=="real"), all(N$canon_status %in% c("verified","inferred")))
stopifnot(all(N$confidence %in% c("high","moderate","limited","unknown")), all(E$confidence %in% c("high","moderate","limited","unknown")), all(O$confidence %in% c("high","moderate","limited","unknown")))
stopifnot(all(O$observed_or_modeled %in% c("observed","derived from observed","observed_adjusted_series","expert_assessed_status","expert_assessed_index","historical_event_record","warning_threshold")))
stopifnot(all(grepl("^-?[0-9]+(\\.[0-9]+)?$", as.character(O$value))))
for (m in c("phase8a_biogeochemical_nutrient_flux_freeze_manifest.json", "phase8b_biogeochemical_dependencies_controls_freeze_manifest.json", "phase8c_biogeochemical_futures_freeze_manifest.json")) {
  p <- file.path(root,"reports",m); stopifnot(file.exists(p)); t <- paste(readLines(p, warn=FALSE), collapse="\n"); stopifnot(grepl("ACCEPTED / FROZEN",t,fixed=TRUE), grepl("21f8d6cc3ab6925a8001551f21ab771622ea9d41",t,fixed=TRUE))
}
map_png <- file.path(root,"outputs/maps/systems/29_climate_natural_hazards_2026.png")
map_svg <- file.path(root,"outputs/maps/systems/29_climate_natural_hazards_2026.svg")
stopifnot(file.exists(map_png), file.info(map_png)$size > 1000, file.exists(map_svg), file.info(map_svg)$size > 1000)
svg_text <- tolower(paste(readLines(map_svg, warn=FALSE), collapse=" "))
for (term in c("map 29", "extreme heat", "precip / flood", "drought / low water", "lake / coastal", "convective", "winter", "not hazard zones", "seiche")) stopifnot(grepl(term, svg_text, fixed=TRUE))
raw_text <- paste(capture.output(print(N)), capture.output(print(E)), capture.output(print(O)), collapse=" ")
stopifnot(!grepl("2050|2075", raw_text), !grepl("hazard_score|risk_score|mortality|social_vulnerability", raw_text, ignore.case=TRUE))
cat(sprintf("Phase 9A R validation passed: %d nodes, %d edges, %d observations, %d sources; Map 29 present\n", nrow(N), nrow(E), nrow(O), nrow(S)))
