args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[[1]] else normalizePath(file.path(dirname(sys.frame(1)$ofile), "../../.."), mustWork=FALSE)
read_csv <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE, na.strings=c(""))
N <- file.path(root, "data/processed/networks"); A <- file.path(root, "data/processed/analysis"); M <- file.path(root, "outputs/maps/systems"); R <- file.path(root, "reports")
d <- read_csv(file.path(A,"governance_dependency_register.csv")); e <- read_csv(file.path(N,"governance_dependency_edges.csv")); k <- read_csv(file.path(A,"governance_coordination_mechanisms.csv")); m <- read_csv(file.path(A,"governance_dependency_matrix.csv")); s <- read_csv(file.path(A,"governance_sources.csv")); actors <- read_csv(file.path(A,"governance_actors.csv")); auth <- read_csv(file.path(A,"governance_authorities.csv"))
dep_cols <- c("dependency_id","system_a","system_b","actor_a","actor_b","role_a","role_b","dependency_type","coordination_mechanism","mandatory_or_voluntary","documented_or_inferred","jurisdictional_scale","evidence_strength","source_id","notes")
edge_cols <- c("edge_id","system_a","system_b","actor_a","actor_b","role_a","role_b","dependency_type","coordination_mechanism","source_id","evidence_strength","notes")
mech_cols <- c("mechanism_id","mechanism_type","mechanism_name","actors","systems","mandatory_or_voluntary","documented_or_inferred","binding_character","source_id","evidence_strength","notes")
mat_cols <- c("pathway","authority_clarity","jurisdiction_overlap","coordination_requirement","monitoring_alignment","enforcement_basis","funding_dependency","public_private_dependency","cross_border_dependency","data_dependency","decision_sequence","uncertainty","notes")
stopifnot(setequal(names(d),dep_cols), setequal(names(e),edge_cols), setequal(names(k),mech_cols), setequal(names(m),mat_cols))
stopifnot(nrow(d)==25,nrow(e)==25,nrow(k)==14,nrow(m)==10,nrow(s)==48)
stopifnot(length(unique(d$dependency_id))==25,length(unique(e$edge_id))==25,length(unique(k$mechanism_id))==14,length(unique(m$pathway))==10)
qual <- c("strong","moderate","limited","unknown","not_applicable"); evid <- c("high","moderate","limited","unknown"); state <- c("mandatory","voluntary","mixed","unknown","not_applicable"); doc <- c("documented","inferred")
dep_types <- c("overlapping_authority","sequential_authority","split_responsibility","information_dependency","funding_dependency","permit_dependency","public_private_dependency","interstate_dependency","binational_dependency","monitoring-without-control","control-without-direct-observation","voluntary_coordination","mandatory_coordination","emergency_coordination","advisory_relationship")
mech_types <- c("statute/regulation","permit","compact","treaty/agreement","memorandum/agreement","funding program","market/operator rule","planning process","emergency protocol","scientific/data-sharing network","consultation relationship")
stopifnot(all(d$dependency_type %in% dep_types),all(d$coordination_mechanism %in% mech_types),all(d$mandatory_or_voluntary %in% state),all(d$documented_or_inferred %in% doc),all(d$evidence_strength %in% evid))
stopifnot(all(k$mechanism_type %in% mech_types),all(k$mandatory_or_voluntary %in% state),all(k$documented_or_inferred %in% doc),all(k$evidence_strength %in% evid),all(as.character(unlist(m[,2:12])) %in% qual))
stopifnot(all(d$actor_a %in% actors$actor_id),all(d$actor_b %in% actors$actor_id),all(d$source_id %in% s$source_id),all(e$source_id %in% s$source_id),all(k$source_id %in% s$source_id))
pairs <- paste(auth$actor_id,auth$authority_or_role)
stopifnot(all(paste(d$actor_a,d$role_a) %in% pairs),all(paste(d$actor_b,d$role_b) %in% pairs))
stopifnot(all(e$edge_id==sub("GDEP","GEDGE",d$dependency_id)),all(e$system_a==d$system_a),all(e$system_b==d$system_b),all(e$actor_a==d$actor_a),all(e$actor_b==d$actor_b))
get <- function(id) d[d$dependency_id==id,,drop=FALSE]
z <- get("GDEP-002"); stopifnot(z$role_a=="regulate",z$role_b=="operate",z$mandatory_or_voluntary=="mandatory",z$dependency_type=="mandatory_coordination",z$documented_or_inferred=="documented")
z <- get("GDEP-007"); stopifnot(z$actor_a=="GA-026",z$role_a=="operate",z$actor_b=="GA-030",z$dependency_type=="public_private_dependency")
z <- get("GDEP-009"); stopifnot(z$actor_a=="GA-025",z$role_a=="set_standard",z$dependency_type=="control-without-direct-observation")
z <- get("GDEP-014"); stopifnot(z$dependency_type=="overlapping_authority",z$coordination_mechanism=="permit",z$source_id=="s05_ohio_npdes",z$documented_or_inferred=="inferred")
z <- get("GDEP-018"); stopifnot(z$documented_or_inferred=="inferred",grepl("no Western Basin jurisdiction",z$notes,fixed=TRUE))
z <- get("GDEP-019"); stopifnot(z$documented_or_inferred=="documented",z$coordination_mechanism=="consultation relationship")
z <- get("GDEP-020"); stopifnot(z$mandatory_or_voluntary=="voluntary",z$dependency_type=="voluntary_coordination")
stopifnot(grepl("no Western Basin jurisdiction",get("GDEP-018")$notes,fixed=TRUE))
stopifnot(!grepl("gap",tolower(paste(d$notes,collapse=" ")),fixed=TRUE),!any(grepl("universal|all assets|always",tolower(k$binding_character))))
text <- tolower(paste(capture.output(print(d)),capture.output(print(e)),capture.output(print(k)),capture.output(print(m)),collapse=" "))
stopifnot(!grepl("2050|2075|future|scenario|partisan|election",text),grepl("unknown",text,fixed=TRUE),grepl("mandatory",text,fixed=TRUE),grepl("voluntary",text,fixed=TRUE),grepl("no individual nutrient duty",text,fixed=TRUE),grepl("no western basin jurisdiction",text,fixed=TRUE))
stopifnot(file.exists(file.path(M,"33_cross_system_governance_dependencies_2026.png")),file.info(file.path(M,"33_cross_system_governance_dependencies_2026.png"))$size>1000,file.exists(file.path(M,"33_cross_system_governance_dependencies_2026.svg")),file.info(file.path(M,"33_cross_system_governance_dependencies_2026.svg"))$size>1000)
svg_text <- tolower(paste(readLines(file.path(M,"33_cross_system_governance_dependencies_2026.svg"),warn=FALSE),collapse=" "))
for (term in c("map 33","cross-system","nutrient","weather","wetland","energy","private rail","unknown","failure","overlap","dysfunction")) stopifnot(grepl(term,svg_text,fixed=TRUE))
stopifnot(file.exists(file.path(R,"governance_baseline_manifest.json")),file.exists(file.path(R,"governance_dependency_manifest.json")))
for (manifest in c("phase3a_freeze_manifest.json","phase3b_freeze_manifest.json","phase4b_information_freeze_manifest.json","phase4c_information_freeze_manifest.json","phase5a_freight_freeze_manifest.json","phase5b_freight_evidence_freeze_manifest.json","phase5c_freight_dependency_freeze_manifest.json","phase6a_ecology_freeze_manifest.json","phase6b_ecological_dependency_freeze_manifest.json","phase6c_ecological_futures_freeze_manifest.json","phase7a_exposure_environmental_health_freeze_manifest.json","phase8a_biogeochemical_nutrient_flux_freeze_manifest.json","phase8b_biogeochemical_dependencies_controls_freeze_manifest.json","phase8c_biogeochemical_futures_freeze_manifest.json","phase9a_climate_natural_hazards_freeze_manifest.json","phase9b_climate_hazard_dependencies_resilience_freeze_manifest.json","phase9c_climate_hazard_futures_freeze_manifest.json")) stopifnot(file.exists(file.path(R,manifest)))
cat(sprintf("Phase 10B R validation passed: %d dependency rows, %d dependency edges, %d coordination mechanisms, %d matrix rows; Phase 10A baseline present; Map 33 present; dependency and gap-discipline checks passed\n",nrow(d),nrow(e),nrow(k),nrow(m)))
