args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)
read_table <- function(p) read.csv(p, stringsAsFactors=FALSE, check.names=FALSE, na.strings="")
d <- read_table(file.path(root,"data","processed","networks","ecology_dependency_edges.csv")); x <- read_table(file.path(root,"data","processed","analysis","ecological_disturbance_register.csv")); r <- read_table(file.path(root,"data","processed","analysis","ecological_resilience_matrix.csv")); n <- read_table(file.path(root,"data","processed","networks","ecology_system_nodes.csv")); meta <- readLines(file.path(root,"metadata","sources.yml"),warn=FALSE)
stopifnot(nrow(d)==18,nrow(x)==10,nrow(r)==6,!anyDuplicated(d$dependency_id),!anyDuplicated(x$disturbance_id),!anyDuplicated(r$ecological_system))
stopifnot(all(d$source_node_id %in% n$node_id),all(d$dependent_node_id %in% n$node_id),all(d$confidence %in% c("low","moderate","high","unknown")),all(unlist(r[,2:10]) %in% c("low","moderate","high","unknown")))
for (sid in unique(c(d$source_id,x$source_id))) stopifnot(any(grepl(paste0("^  ",sid,":"),meta)))
t <- paste(d$ecological_function,d$notes,x$description,x$notes,r$notes,collapse=" ")
stopifnot(!grepl("2050|2075|scenario|population|extinction|abundance|species richness|exact (animal|migration|flight) route|risk score|vulnerability score|disease|malaria|arbovirus",t,ignore.case=TRUE))
stopifnot(file.exists(file.path(root,"outputs","maps","systems","21_ecological_dependencies_disturbances_2026.png")),file.exists(file.path(root,"outputs","maps","systems","21_ecological_dependencies_disturbances_2026.svg")))
svg <- paste(readLines(file.path(root,"outputs","maps","systems","21_ecological_dependencies_disturbances_2026.svg"),warn=FALSE),collapse=" ")
stopifnot(grepl("MAP 21",svg,fixed=TRUE),grepl("DISTURBANCES",svg,fixed=TRUE),grepl("Great Black Swamp",svg,fixed=TRUE))
cat("R Phase 6B ecology dependency validation passed: 18 dependencies, 10 disturbances, 6x10 resilience matrix, Map 21 present\n")
