args <- commandArgs(trailingOnly=TRUE)
root <- if(length(args)) args[1] else "."
sd <- file.path(root,"data","processed","scenarios")
a <- read.csv(file.path(sd,"energy_scenario_assumptions.csv"), stringsAsFactors=FALSE)
n <- read.csv(file.path(sd,"energy_nodes_scenario.csv"), stringsAsFactors=FALSE)
e <- read.csv(file.path(sd,"energy_edges_scenario.csv"), stringsAsFactors=FALSE)
c <- read.csv(file.path(root,"outputs","figures","energy_scenarios_comparison.csv"), stringsAsFactors=FALSE)
base <- read.csv(file.path(root,"data","processed","networks","energy_system_nodes.csv"), stringsAsFactors=FALSE)
dep <- read.csv(file.path(root,"data","processed","networks","energy_dependency_nodes.csv"), stringsAsFactors=FALSE)
stopifnot(nrow(a)==36, length(unique(a$assumption_id))==36, all(table(a$scenario_id)==6))
stopifnot(nrow(n)==114, length(unique(n$object_id))==114, all(table(n$scenario_id)==19))
stopifnot(nrow(e)==114, all(table(e$scenario_id)==19), all(e$relationship_basis=="scenario_assumption"))
stopifnot(nrow(c)==48, all(table(c$scenario_id)==8), all(c$level %in% c("low","moderate","high")))
stopifnot(nrow(base)==18, nrow(dep)==5)
stopifnot(base$status_2026[base$node_id=="ENE-EIA-1733"]=="operating_planned_retirement")
stopifnot(base$status_2026[base$node_id=="ENE-COMPUTE-BG-5MW"]=="permitted_or_planned_unverified_operation")
stopifnot(all(grepl("Not a power-flow route",e$notes)))
png(file.path(root,"outputs","figures","energy_scenarios_R_validation.png"),width=1800,height=950,res=150)
par(mar=c(9,5,4,2),bg="#eee6d3")
tab <- table(c$scenario_id,c$level)
barplot(t(tab),beside=TRUE,col=c("#b8d4cf","#e3b96e","#c45a47"),las=2,ylab="Dimension count",main="Phase 3C qualitative scenario validation")
legend("topright",legend=colnames(tab),fill=c("#b8d4cf","#e3b96e","#c45a47"),bty="n")
mtext("Separate 2050/2075 scenario deltas; no probability, MW forecast, or power-flow model",side=1,line=7,cex=.8)
dev.off()
cat("R Phase 3C validation passed: 36 assumptions, 114 node states, 114 edge deltas, 48 comparison rows\n")
