# Independent base-R validation of Phase 2C history/exposure tables.

args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
script_path <- normalizePath(sub("^--file=", "", file_arg), winslash = "/")
root <- normalizePath(file.path(dirname(script_path), "../../.."), winslash = "/")
history <- file.path(root, "data/processed/history")
networks <- file.path(root, "data/processed/networks")

events <- read.csv(file.path(history, "materials_exposure_events.csv"), stringsAsFactors = FALSE, na.strings = NULL)
substances <- read.csv(file.path(history, "materials_exposure_substances.csv"), stringsAsFactors = FALSE, na.strings = NULL)
pathways <- read.csv(file.path(history, "materials_exposure_pathways.csv"), stringsAsFactors = FALSE, na.strings = NULL)
sources <- read.csv(file.path(history, "materials_exposure_sources.csv"), stringsAsFactors = FALSE, na.strings = NULL)
nodes <- read.csv(file.path(networks, "materials_system_nodes.csv"), stringsAsFactors = FALSE, na.strings = NULL)
edges <- read.csv(file.path(networks, "materials_system_edges.csv"), stringsAsFactors = FALSE, na.strings = NULL)

stopifnot(nrow(events) == 30L, nrow(substances) == 9L, nrow(pathways) == 7L, nrow(sources) == 13L)
stopifnot(!anyDuplicated(events$event_id), !anyDuplicated(substances$substance_id), !anyDuplicated(pathways$pathway_id), !anyDuplicated(sources$source_id))
stopifnot(all(pathways$documented_human_exposure == "false"))
stopifnot(all(pathways$evidence_class %in% c("potential_exposure_pathway", "documented_environmental_contamination", "documented_waste_logistics", "controlled_potential_pathway", "generalized_regulated_pathway")))
stopifnot(any(events$start_date == "1942" & events$material == "magnesium"))
stopifnot(any(events$start_date == "1949" & events$material == "beryllium"))
stopifnot(any(events$start_date == "1992" & events$event_type == "federal_designation"))
stopifnot(any(events$start_date == "2006" & grepl("soil", events$activity, ignore.case = TRUE)))
stopifnot(any(events$start_date == "2008" & grepl("groundwater", events$activity, ignore.case = TRUE)))
stopifnot(any(events$start_date == "2018-04-16" & events$event_type == "excavation"))
stopifnot(any(events$start_date == "2025-09-15" & events$event_type == "groundwater_monitoring"))
stopifnot(nrow(nodes) == 30L, nrow(edges) == 31L)
stopifnot(!any(edges$from_id == "BER-LEG-LUCKEY" & edges$to_id == "BER-PROC-ELMORE"))
stopifnot(nodes$supply_chain_role[nodes$node_id == "BER-LEG-LUCKEY"] == "legacy_cleanup")
stopifnot(nodes$supply_chain_role[nodes$node_id == "BER-PROC-ELMORE"] == "advanced_processing")
stopifnot(nodes$local_resource[nodes$node_id == "BER-PROC-ELMORE"] == "false")

figure_path <- file.path(root, "outputs/figures/materials_exposure_history_R_validation.png")
png(figure_path, width = 1800, height = 1050, res = 150)
par(mfrow = c(1, 2), mar = c(8, 4, 4, 1), bg = "#f7f4ec")
event_year <- as.integer(substr(events$start_date, 1, 4))
hist(event_year, breaks = seq(1940, 2040, by = 10), col = "#52796f", border = "white", main = "Phase 2C chronology", xlab = "Event start year")
barplot(table(pathways$evidence_class), col = "#b56576", las = 2, cex.names = 0.72, main = "Qualified pathway classes", ylab = "Count")
mtext("Independent R validation — PASS · no individual exposure findings", outer = TRUE, line = -2, font = 2, col = "#17324d")
dev.off()

cat(sprintf("PASS: %d events; %d substances; %d qualified pathways; 0 documented individual exposures.\n", nrow(events), nrow(substances), nrow(pathways)))
