args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) normalizePath(args[[1]], mustWork=TRUE) else normalizePath(".", mustWork=TRUE)
a <- file.path(root, "data", "processed", "analysis")
n <- file.path(root, "data", "processed", "networks")
m <- file.path(root, "outputs", "maps", "systems")
r <- file.path(root, "reports")
read_table <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE, na.strings=c("", "NA"))
mob <- read_table(file.path(a, "population_mobility_observations.csv"))
rel <- read_table(file.path(n, "population_mobility_relationships.csv"))
dep <- read_table(file.path(a, "population_system_dependency_register.csv"))
mat <- read_table(file.path(a, "population_system_dependency_matrix.csv"))
nodes <- read_table(file.path(a, "population_settlement_nodes.csv"))
sources <- read_table(file.path(a, "population_settlement_sources.csv"))
stopifnot(nrow(mob) == 302, !anyDuplicated(mob$record_id), nrow(rel) == 142, !anyDuplicated(rel$relationship_id), nrow(dep) == 520, !anyDuplicated(dep$dependency_id), nrow(mat) == 52, !anyDuplicated(mat$object_id))
stopifnot(all(mob$source_id %in% sources$source_id), all(rel$source_id %in% sources$source_id), all(dep$source_id %in% sources$source_id))
diffs <- mob[mob$metric == "workplace_residence_difference", , drop=FALSE]
stopifnot(nrow(diffs) == 16)
for (i in seq_len(nrow(diffs))) {
  s <- sources[sources$source_id == diffs$source_id[[i]], , drop=FALSE]
  stopifnot(nrow(s) == 1L, diffs$source_product[[i]] == s$source_product[[1]], as.character(diffs$reference_year[[i]]) == as.character(s$reference_year[[1]]), as.character(diffs$estimate_period[[i]]) == as.character(s$estimate_period[[1]]), !grepl("mi_wac_rac$", diffs$source_id[[i]]))
}
stopifnot(all(mob$metric %in% c("job_count","worker_count","workplace_residence_difference","drive_alone_share","carpool_share","public_transit_share","walk_share","work_from_home_share","commute_45_plus_share","commuter_flow")))
stopifnot(all(mob$observed_estimated_modeled %in% c("estimated","modeled")), all(mob$geographic_scale %in% c("county","county_pair")))
stopifnot(all(rel$module == "11B"), all(rel$relationship_type == "commuting_interface_with"), all(rel$geographic_scale == "county_pair"), all(rel$units == "jobs"), all(rel$observed_estimated_modeled == "modeled"), all(rel$source_node_id %in% nodes$node_id), all(rel$target_node_id %in% nodes$node_id), all(rel$source_node_id != rel$target_node_id))
stopifnot(all(dep$population_or_settlement_object %in% nodes$node_id), all(dep$system %in% c("water","wastewater","energy","transport","climate_hazard","environmental_health","ecology_land","biogeochemical","housing_infrastructure","governance")), all(dep$evidence_strength %in% c("strong","moderate","limited","unknown","not_applicable")))
node_state <- setNames(nodes$state, nodes$node_id)
transport <- dep[dep$system == "transport", , drop=FALSE]
stopifnot(all(transport$documented_or_inferred == "inferred"), all(transport$source_id == paste0("s11b_lodes_", tolower(node_state[transport$population_or_settlement_object]), "_od")))
water_expected <- ifelse(dep$population_or_settlement_object %in% c("POP-ZONE-39095", "MUNI-3977000"), "phase10_s03_toledo_treatment", "phase10_governance_context")
stopifnot(all(dep$source_id[dep$system == "water"] == water_expected[dep$system == "water"]))
waste_expected <- ifelse(node_state[dep$population_or_settlement_object] == "OH", "phase10_s05_ohio_npdes", "phase10_governance_context")
stopifnot(all(dep$source_id[dep$system == "wastewater"] == waste_expected[dep$system == "wastewater"]))
dims <- c("settlement_concentration","mobility_dependency","employment_access","housing_constraint","water_dependency","wastewater_dependency","energy_dependency","transport_dependency","climate_hazard_interface","environmental_health_interface","governance_dependency","service_access","data_certainty")
stopifnot(all(dims %in% names(mat)))
for (d in dims) stopifnot(all(mat[[d]] %in% c("strong","moderate","limited","unknown","not_applicable")))
stopifnot(all(mat$object_id %in% nodes$node_id), all(grepl("derived from the dependency register", mat$notes, fixed=TRUE)))
all_text <- tolower(paste(capture.output(write.table(mob,row.names=FALSE,quote=FALSE)), capture.output(write.table(rel,row.names=FALSE,quote=FALSE)), capture.output(write.table(dep,row.names=FALSE,quote=FALSE)), capture.output(write.table(mat,row.names=FALSE,quote=FALSE)), collapse=" "))
stopifnot(!grepl("\\b(2050|2075)\\b", all_text, perl=TRUE), !grepl("vulnerability_score|ej_score|risk_score|protected_class_rank|dose|illness|mortality", paste(names(mob),names(rel),names(dep),names(mat),collapse=" "), ignore.case=TRUE))
stopifnot(grepl("commuting is not migration", all_text, fixed=TRUE) || grepl("not migration", all_text, fixed=TRUE), grepl("not a vulnerability", all_text, fixed=TRUE) || grepl("vulnerability score", all_text, fixed=TRUE))
for (p in c("35_population_settlement_2026.png","36_population_mobility_dependencies_2026.png")) stopifnot(file.exists(file.path(m,p)), file.info(file.path(m,p))$size > 10000)
svg36 <- tolower(paste(readLines(file.path(m,"36_population_mobility_dependencies_2026.svg"),warn=FALSE,encoding="UTF-8"),collapse=" "))
for (term in c("map 36","mobility","commuting","employment","migration","vulnerability")) stopifnot(grepl(term,svg36,fixed=TRUE))
stopifnot(file.exists(file.path(r,"population_settlement_baseline_manifest.json")), file.exists(file.path(r,"phase11_working_manifest.json")))
phase10 <- c("phase10a_governance_jurisdiction_freeze_manifest.json","phase10b_governance_dependencies_coordination_freeze_manifest.json","phase10c_governance_futures_freeze_manifest.json")
stopifnot(all(file.exists(file.path(r,phase10))))
prior <- list.files(r,pattern="^phase.*_freeze_manifest[.]json$",full.names=TRUE); prior <- prior[!basename(prior) %in% phase10]
prior_text <- paste(unlist(lapply(prior,readLines,warn=FALSE)),collapse=" ")
stopifnot(length(unlist(regmatches(prior_text,gregexpr("[0-9a-f]{64}",prior_text,perl=TRUE)))) >= 196)
working <- paste(readLines(file.path(r,"phase11_working_manifest.json"),warn=FALSE),collapse=" ")
stopifnot(grepl('"phase": "11A/11B"',working,fixed=TRUE),grepl('"phase11c_implemented": false',working,fixed=TRUE),grepl('"active_holds_preserved": true',working,fixed=TRUE))
cat(sprintf("Phase 11B R validation passed: %d mobility observations, %d mobility relationships, %d dependencies, %d matrix rows; Maps 35/36; baseline, freeze inventory, holds, and Phase 11C absence checked\n",nrow(mob),nrow(rel),nrow(dep),nrow(mat)))
