args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) normalizePath(args[[1]], mustWork=TRUE) else normalizePath(".", mustWork=TRUE)
a <- file.path(root, "data", "processed", "analysis")
n <- file.path(root, "data", "processed", "networks")
m <- file.path(root, "outputs", "maps", "systems")
r <- file.path(root, "reports")
read_table <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE, na.strings=c("", "NA"))
stopifnot(file.exists(file.path(a, "population_settlement_nodes.csv")), file.exists(file.path(a, "population_settlement_observations.csv")), file.exists(file.path(n, "population_settlement_relationships.csv")))
nodes <- read_table(file.path(a, "population_settlement_nodes.csv"))
obs <- read_table(file.path(a, "population_settlement_observations.csv"))
rel <- read_table(file.path(n, "population_settlement_relationships.csv"))
sources <- read_table(file.path(a, "population_settlement_sources.csv"))
unc <- read_table(file.path(a, "population_settlement_uncertainty.csv"))
node_cols <- c("node_id","node_type","name","state","geoid","geographic_unit","geographic_scale","latitude","longitude","settlement_class","study_frame","source_id","confidence","reality_status","canon_status","notes")
obs_cols <- c("record_id","metric","value","units","reference_year","release_year","estimate_period","geographic_unit","geographic_scale","node_id","source_product","observed_estimated_modeled","source_id","confidence","reality_status","canon_status","notes")
rel_cols <- c("relationship_id","module","source_node_id","target_node_id","relationship_type","value","units","reference_year","release_year","estimate_period","origin_geography","destination_geography","geographic_scale","source_product","observed_estimated_modeled","source_id","evidence_strength","relationship_basis","confidence","reality_status","canon_status","notes")
source_cols <- c("source_id","title","url","source_type","source_product","reference_year","release_year","estimate_period","geographic_scale","observed_estimated_modeled","retrieval_date","use_limitations")
unc_cols <- c("uncertainty_id","subject_id","category","statement","resolution_status","source_id","confidence","notes")
stopifnot(setequal(names(nodes), node_cols), setequal(names(obs), obs_cols), setequal(names(rel), rel_cols), setequal(names(sources), source_cols), setequal(names(unc), unc_cols))
stopifnot(nrow(nodes) == 62, !anyDuplicated(nodes$node_id), nrow(obs) == 918, !anyDuplicated(obs$record_id), nrow(rel) == 44, !anyDuplicated(rel$relationship_id), nrow(sources) == 34, !anyDuplicated(sources$source_id), nrow(unc) == 9)
stopifnot(all(nodes$node_type %in% c("population_zone","municipality","employment_center")))
stopifnot(all(obs$observed_estimated_modeled %in% c("observed","estimated","modeled")))
stopifnot(all(obs$source_id %in% sources$source_id), all(nodes$source_id %in% sources$source_id), all(rel$source_id %in% sources$source_id), all(unc$source_id %in% sources$source_id))
stopifnot(all(obs$reference_year != ""), all(obs$release_year != ""), all(obs$estimate_period != ""))
stopifnot(all(obs$metric[obs$metric == "population_count"] == "population_count"), all(obs$units[obs$metric == "population_count"] == "persons"))
stopifnot(all(obs$units[obs$metric == "household_count"] == "households"), all(obs$units[obs$metric == "housing_unit_count"] == "housing_units"), all(obs$units[obs$metric == "population_density"] == "persons_per_square_mile"))
stopifnot(all(rel$module == "11A"), all(rel$relationship_type %in% c("contains_settlement","employment_concentration")), all(rel$source_node_id %in% nodes$node_id), all(rel$target_node_id %in% nodes$node_id))
all_text <- tolower(paste(capture.output(write.table(nodes, row.names=FALSE, quote=FALSE)), capture.output(write.table(obs, row.names=FALSE, quote=FALSE)), capture.output(write.table(rel, row.names=FALSE, quote=FALSE)), collapse=" "))
stopifnot(!grepl("\\b(2050|2075)\\b", all_text, perl=TRUE), !grepl("risk_score|vulnerability_score|ej_score|protected_class_rank|dose|mortality", paste(names(nodes), names(obs), names(rel), collapse=" "), ignore.case=TRUE))
unc_text <- tolower(paste(unc$statement, collapse=" "))
stopifnot(grepl("great black swamp", unc_text, fixed=TRUE), grepl("noncanonical", unc_text, fixed=TRUE), grepl("intake-coordinate discrepancy", unc_text, fixed=TRUE), grepl("unresolved", unc_text, fixed=TRUE))
png <- file.path(m, "35_population_settlement_2026.png"); svg <- file.path(m, "35_population_settlement_2026.svg")
stopifnot(file.exists(png), file.exists(svg), file.info(png)$size > 10000, file.info(svg)$size > 10000)
svg_text <- tolower(paste(readLines(svg, warn=FALSE, encoding="UTF-8"), collapse=" "))
for (term in c("map 35", "population", "settlement", "2020 census", "person", "household", "great black swamp")) stopifnot(grepl(term, svg_text, fixed=TRUE))
# Independent freeze-boundary presence/count checks; Python performs the byte-portable hash recomputation.
freeze_files <- list.files(r, pattern="^phase.*_freeze_manifest[.]json$", full.names=TRUE)
stopifnot(all(file.exists(file.path(r, c("phase10a_governance_jurisdiction_freeze_manifest.json", "phase10b_governance_dependencies_coordination_freeze_manifest.json", "phase10c_governance_futures_freeze_manifest.json")))))
prior <- freeze_files[!basename(freeze_files) %in% c("phase10a_governance_jurisdiction_freeze_manifest.json", "phase10b_governance_dependencies_coordination_freeze_manifest.json", "phase10c_governance_futures_freeze_manifest.json")]
prior_text <- paste(unlist(lapply(prior, readLines, warn=FALSE)), collapse=" ")
prior_hash_count <- length(unlist(regmatches(prior_text, gregexpr("[0-9a-f]{64}", prior_text, perl=TRUE))))
stopifnot(prior_hash_count >= 196)
stopifnot(file.exists(file.path(r, "population_settlement_baseline_manifest.json")))
manifest_text <- paste(readLines(file.path(r, "population_settlement_baseline_manifest.json"), warn=FALSE), collapse=" ")
stopifnot(grepl('"phase": "11A"', manifest_text, fixed=TRUE), grepl('"map_number": 35', manifest_text, fixed=TRUE), grepl('"phase11c_implemented": false', manifest_text, fixed=TRUE))
cat(sprintf("Phase 11A R validation passed: %d nodes, %d observations, %d relationships, %d sources, %d uncertainties; Map 35; Phase 1-10 freeze manifests present and prior manifest hash inventory >=196; holds and Phase 11C absence checked\n", nrow(nodes), nrow(obs), nrow(rel), nrow(sources), nrow(unc)))
