args <- commandArgs(trailingOnly=TRUE)
root <- if(length(args)) args[1] else "."
nodes <- read.csv(file.path(root,"data","processed","networks","energy_system_nodes.csv"))
dep <- read.csv(file.path(root,"data","processed","networks","energy_dependency_nodes.csv"))
edges <- read.csv(file.path(root,"data","processed","networks","energy_dependency_edges.csv"))
matrix <- read.csv(file.path(root,"outputs","figures","energy_dependency_matrix_2026.csv"),check.names=FALSE)
stopifnot(nrow(nodes)==18,nrow(dep)==5,nrow(edges)==28,nrow(matrix)==10,ncol(matrix)==8)
all_ids <- c(nodes$node_id,dep$node_id)
stopifnot(all(edges$from_node_id %in% all_ids),all(edges$to_node_id %in% all_ids))
stopifnot(all(edges$dependency_type != ""),all(edges$relationship_basis != ""),all(edges$confidence != ""))
stopifnot(all(edges$dependency_strength %in% c("low","moderate","high")))
stopifnot(all(edges$outage_sensitivity %in% c("low","moderate","high","unknown")))
stopifnot(all(as.character(unlist(matrix[,-1])) %in% c("none","low","moderate","high","unknown")))
png(file.path(root,"outputs","figures","energy_dependency_R_validation.png"),width=1400,height=850,res=150)
par(mar=c(7,5,4,2),bg="#f2ead8")
barplot(table(edges$dependency_type),las=2,col="#2b7a78",border=NA,ylab="Dependency-edge count",main="Phase 3B qualitative dependency validation")
mtext("Separate analytical layer; no power-flow or outage-probability model",side=1,line=5.5,cex=.8)
dev.off()
cat("R Phase 3B dependency validation passed: 5 generalized nodes, 28 edges, 10x7 matrix\n")
