args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)

read_table <- function(...) read.csv(..., stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
assumptions <- read_table(file.path(root, "data", "processed", "scenarios", "information_scenario_assumptions.csv"))
nodes <- read_table(file.path(root, "data", "processed", "scenarios", "information_nodes_scenario.csv"))
edges <- read_table(file.path(root, "data", "processed", "scenarios", "information_edges_scenario.csv"))
blind <- read_table(file.path(root, "data", "processed", "scenarios", "information_blind_spots_scenario.csv"))
authority <- read_table(file.path(root, "data", "processed", "scenarios", "information_authority_scenario.csv"))
comparison <- read_table(file.path(root, "outputs", "figures", "information_scenarios_comparison.csv"))
phase4a_nodes <- read_table(file.path(root, "data", "processed", "networks", "observation_system_nodes.csv"))
phase4a_edges <- read_table(file.path(root, "data", "processed", "networks", "observation_system_edges.csv"))
metadata <- readLines(file.path(root, "metadata", "sources.yml"), warn = FALSE)

scenario_ids <- c("A2050", "A2075", "B2050", "B2075", "C2050", "C2075")
scenario_years <- c(A2050=2050, A2075=2075, B2050=2050, B2075=2075, C2050=2050, C2075=2075)
stopifnot(nrow(assumptions) == 36, nrow(nodes) == 72, nrow(edges) == 48, nrow(blind) == 36, nrow(authority) == 6, nrow(comparison) == 6)
stopifnot(setequal(unique(assumptions$scenario_id), scenario_ids), setequal(unique(nodes$scenario_id), scenario_ids), setequal(unique(edges$scenario_id), scenario_ids), setequal(unique(blind$scenario_id), scenario_ids), setequal(unique(authority$scenario_id), scenario_ids), setequal(unique(comparison$scenario_id), scenario_ids))
stopifnot(all(as.integer(assumptions$scenario_year) == scenario_years[assumptions$scenario_id]))
stopifnot(all(as.integer(nodes$scenario_year) == scenario_years[nodes$scenario_id]))
stopifnot(all(as.integer(edges$scenario_year) == scenario_years[edges$scenario_id]))
stopifnot(all(as.integer(blind$scenario_year) == scenario_years[blind$scenario_id]))
stopifnot(all(as.integer(authority$scenario_year) == scenario_years[authority$scenario_id]))
stopifnot(all(as.integer(comparison$scenario_year) == scenario_years[comparison$scenario_id]))
stopifnot(!anyDuplicated(assumptions$assumption_id), !anyDuplicated(nodes$object_id), !anyDuplicated(edges$edge_id), !anyDuplicated(blind$blindspot_state_id))
stopifnot(all(nodes$reality_status == "fictional"), all(nodes$relationship_basis == "scenario_assumption"), all(edges$reality_status == "fictional"), all(edges$relationship_basis == "scenario_assumption"), all(blind$relationship_basis == "scenario_assumption"), all(authority$reality_status == "fictional"), all(authority$relationship_basis == "scenario_assumption"))
stopifnot(all(nodes$assumption_id %in% assumptions$assumption_id), all(edges$assumption_id %in% assumptions$assumption_id), all(blind$assumption_id %in% assumptions$assumption_id), all(authority$assumption_id %in% assumptions$assumption_id))
stopifnot(all(nodes$source_or_basis %in% c(assumptions$source_id, unique(nodes$source_or_basis))), all(edges$source_or_basis %in% c(assumptions$source_id, unique(edges$source_or_basis))))
for (source_id in unique(c(assumptions$source_id, nodes$source_or_basis, edges$source_or_basis, blind$source_or_basis, authority$source_or_basis))) {
  stopifnot(any(grepl(paste0("^  ", source_id, ":"), metadata)))
}
stopifnot(all(is.na(nodes$baseline_object_id) | nodes$baseline_object_id == "" | nodes$baseline_object_id %in% phase4a_nodes$node_id))
stopifnot(all(edges$from_object_id %in% nodes$object_id), all(edges$to_object_id %in% nodes$object_id))
stopifnot(all(is.na(blind$baseline_blindspot_id) | blind$baseline_blindspot_id == "" | blind$baseline_blindspot_id %in% read_table(file.path(root, "data", "processed", "analysis", "information_blind_spots.csv"))$blindspot_id))
stopifnot(all(assumptions$plausibility %in% c("high", "moderate", "exploratory")), all(nodes$plausibility %in% c("high", "moderate", "exploratory")), all(edges$plausibility %in% c("high", "moderate", "exploratory")), all(blind$plausibility %in% c("high", "moderate", "exploratory")), all(authority$plausibility %in% c("high", "moderate", "exploratory")))
stopifnot(all(unlist(comparison[, 4:ncol(comparison)]) %in% c("low", "moderate", "high")))
substantive <- paste(assumptions$assumption, nodes$object_name, nodes$future_role, nodes$change_type, edges$relationship_type, edges$change_type, blind$future_blindspot, blind$change_type, authority$authority_pattern, collapse = " ")
stopifnot(!grepl("attack path|exploit|credential|red[- ]team|surveillance[- ]state|fictional sensor|SCADA|target prioritization|sovereign AI|final governmental AI", substantive, ignore.case = TRUE))
stopifnot(!any(grepl("trigger|final authority", tolower(edges$relationship_type))))
stopifnot(file.exists(file.path(root, "reports", "phase4b_information_freeze_manifest.json")))
map_files <- file.path(root, "outputs", "maps", "systems", c("16_information_governance_futures_2050.png", "16_information_governance_futures_2050.svg", "16b_information_governance_futures_2075.png", "16b_information_governance_futures_2075.svg"))
comparison_files <- file.path(root, "outputs", "figures", c("information_scenarios_comparison.png", "information_scenarios_comparison.svg"))
stopifnot(all(file.exists(c(map_files, comparison_files))))
stopifnot(all(file.info(c(map_files, comparison_files))$size > 10000))

validation_png <- file.path(root, "outputs", "figures", "information_scenarios_R_validation.png")
png(validation_png, width = 1600, height = 900, res = 150, bg = "#f1eadc")
par(mar = c(8, 5, 4, 2), bg = "#f1eadc", fg = "#263238")
barplot(table(factor(nodes$scenario_id, levels = scenario_ids)), col = rep(c("#5a9b83", "#2d7fa6", "#c56b5c"), each = 2), border = NA, las = 2, ylab = "Scenario node-state count", main = "Phase 4C scenario validation")
mtext("Independent R check: six scenario states, 36 assumptions, 72 node states, 48 edge deltas, and explicit human authority", side = 1, line = 5.8, cex = 0.8)
dev.off()
cat("R Phase 4C validation passed: 36 assumptions, 72 node states, 48 edge deltas, 36 blind-spot states, 6 authority rows\n")
