args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[[1]] else normalizePath(file.path(dirname(sys.frame(1)$ofile), "../../.."), mustWork=FALSE)
read_csv <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE, na.strings=c(""))
N <- file.path(root, "data/processed/networks")
A <- file.path(root, "data/processed/analysis")
M <- file.path(root, "outputs/maps/systems")
R <- file.path(root, "reports")
actors <- read_csv(file.path(A, "governance_actors.csv"))
auth <- read_csv(file.path(A, "governance_authorities.csv"))
rel <- read_csv(file.path(N, "governance_relationships.csv"))
sources <- read_csv(file.path(A, "governance_sources.csv"))
unc <- read_csv(file.path(A, "governance_uncertainty_register.csv"))
actor_cols <- c("actor_id","name","actor_type","jurisdictional_scale","geographic_scope","systems","operational_or_authority_summary","source_id","evidence_strength","reality_status","canon_status","notes")
auth_cols <- c("authority_id","actor_id","domain_system","authority_or_role","authority_type","binding_or_nonbinding","legal_or_operational_basis","geographic_scope","jurisdictional_scale","source_id","evidence_strength","reality_status","canon_status","notes")
rel_cols <- c("relationship_id","actor_id","domain_system","relationship_type","authority_or_role","binding_or_nonbinding","geographic_scope","jurisdictional_scale","source_id","evidence_strength","reality_status","canon_status","notes")
source_cols <- c("source_id","title","url","source_type","evidence_role","publication_or_update","retrieval_date","geographic_scope","use_limitations","retrieval_status")
unc_cols <- c("uncertainty_id","subject_type","subject_id","domain_system","uncertainty_category","statement","resolution_status","evidence_strength","source_id","notes")
stopifnot(setequal(names(actors),actor_cols), setequal(names(auth),auth_cols), setequal(names(rel),rel_cols), setequal(names(sources),source_cols), setequal(names(unc),unc_cols))
stopifnot(nrow(actors)==40, nrow(auth)==100, nrow(rel)==100, nrow(sources)==47, nrow(unc)==16)
stopifnot(length(unique(actors$actor_id))==40, length(unique(auth$authority_id))==100, length(unique(rel$relationship_id))==100, length(unique(sources$source_id))==47, length(unique(unc$uncertainty_id))==16, length(unique(sources$url))==47)
qual <- c("high","moderate","limited","unknown")
scales <- c("federal","state","interstate","binational","tribal","county","municipal","regional authority","public utility","system operator","private","special district")
binding <- c("binding","nonbinding","mixed","unknown","not_applicable")
roles <- c("regulate","permit","enforce","operate","own","monitor","fund","coordinate","advise","plan","warn","respond","restore","set_standard","research","provide_data")
types <- c("regulatory_authority","permitting","enforcement","operational_control","ownership","monitoring","funding","coordination","advisory","planning","warning","response","restoration","standard_setting","research","scientific_information")
role_type <- setNames(types, roles)
stopifnot(all(actors$actor_type %in% c("federal_agency","state_agency","tribal_sovereign","binational_body","interstate_body","county_government","municipal_government","regional_authority","public_utility","system_operator","private_operator","research_monitoring_body","special_district")))
stopifnot(all(actors$jurisdictional_scale %in% scales), all(auth$jurisdictional_scale %in% scales), all(rel$jurisdictional_scale %in% scales))
stopifnot(all(actors$evidence_strength %in% qual), all(auth$evidence_strength %in% qual), all(rel$evidence_strength %in% qual), all(unc$evidence_strength %in% qual))
stopifnot(all(actors$reality_status=="real"), all(auth$reality_status=="real"), all(rel$reality_status=="real"), all(actors$canon_status %in% c("verified","inferred")), all(auth$canon_status %in% c("verified","inferred")))
stopifnot(all(auth$authority_or_role %in% roles), all(auth$authority_type == unname(role_type[auth$authority_or_role])), all(auth$binding_or_nonbinding %in% binding), all(rel$relationship_type=="actor_system_role"))
stopifnot(all(auth$actor_id %in% actors$actor_id), all(rel$actor_id %in% actors$actor_id), all(auth$source_id %in% sources$source_id), all(rel$source_id %in% sources$source_id), all(actors$source_id %in% sources$source_id), all(unc$source_id %in% sources$source_id))
stopifnot(all(sources$retrieval_status %in% c("retrieved","retrieved_limited","reference_only")), all(nchar(sources$use_limitations)>0), all(nchar(auth$notes)>0), all(nchar(unc$notes)>0))
for (id in c("GA-005","GA-007")) { z <- auth[auth$actor_id==id,,drop=FALSE]; stopifnot(all(z$authority_or_role %in% c("monitor","research","provide_data","advise"))) }
for (id in c("GA-030","GA-036","GA-037")) { z <- auth[auth$actor_id==id,,drop=FALSE]; stopifnot(all(z$authority_or_role %in% c("own","operate")), !any(z$authority_or_role %in% c("regulate","permit","enforce","set_standard"))) }
z <- auth[auth$actor_id=="GA-026",,drop=FALSE]; stopifnot(!any(z$authority_or_role %in% c("own","regulate","permit","enforce")))
stopifnot(one <- TRUE)
stopifnot(auth[auth$authority_id=="AUTH-059","actor_id"]=="GA-024", auth[auth$authority_id=="AUTH-059","authority_or_role"]=="regulate")
stopifnot(auth[auth$authority_id=="AUTH-062","actor_id"]=="GA-025", auth[auth$authority_id=="AUTH-062","authority_or_role"]=="set_standard")
stopifnot(auth[auth$authority_id=="AUTH-065","actor_id"]=="GA-026", auth[auth$authority_id=="AUTH-065","authority_or_role"]=="operate")
stopifnot(auth[auth$authority_id=="AUTH-034","binding_or_nonbinding"]=="mixed", grepl("not a general enforceable",auth[auth$authority_id=="AUTH-034","notes"],fixed=TRUE))
stopifnot(auth[auth$authority_id=="AUTH-057","binding_or_nonbinding"]=="unknown", grepl("current project jurisdiction",auth[auth$authority_id=="AUTH-057","notes"],fixed=TRUE))
stopifnot(auth[auth$authority_id=="AUTH-087","authority_or_role"]=="own", auth[auth$authority_id=="AUTH-088","authority_or_role"]=="operate", grepl("not operation of every",tolower(auth[auth$authority_id=="AUTH-088","notes"]),fixed=TRUE))
stopifnot(all(grepl("not|no",auth$notes[auth$authority_or_role=="fund"],ignore.case=TRUE) | grepl("distinct",auth$notes[auth$authority_or_role=="fund"],ignore.case=TRUE)))
tribal <- auth[auth$actor_id %in% c("GA-022","GA-023") & auth$authority_or_role=="advise",,drop=FALSE]
stopifnot(nrow(tribal)==2, all(tribal$binding_or_nonbinding=="unknown"), all(tribal$canon_status=="inferred"))
unc_text <- tolower(paste(capture.output(print(unc)),collapse=" "))
stopifnot(grepl("great black swamp",unc_text,fixed=TRUE), grepl("noncanonical",unc_text,fixed=TRUE), grepl("intake-coordinate discrepancy",unc_text,fixed=TRUE), grepl("unresolved",unc_text,fixed=TRUE))
data_text <- tolower(paste(capture.output(print(actors)),capture.output(print(auth)),capture.output(print(rel)),capture.output(print(sources)),collapse=" "))
stopifnot(!grepl("2050|2075|scenario",data_text), !grepl("partisan|election",data_text), !any(names(actors) %in% c("risk_score","hazard_score","probability","mortality","dose","social_vulnerability")))
stopifnot(file.exists(file.path(M,"32_governance_jurisdiction_2026.png")), file.info(file.path(M,"32_governance_jurisdiction_2026.png"))$size>1000, file.exists(file.path(M,"32_governance_jurisdiction_2026.svg")), file.info(file.path(M,"32_governance_jurisdiction_2026.svg"))$size>1000)
svg_text <- tolower(paste(readLines(file.path(M,"32_governance_jurisdiction_2026.svg"),warn=FALSE),collapse=" "))
for (term in c("map 32","governance","role distinctions","institutional scales","private operation is not public control","tribal sovereignty","not jurisdiction polygons")) stopifnot(grepl(term,svg_text,fixed=TRUE))
stopifnot(file.exists(file.path(R,"governance_baseline_manifest.json")))
for (manifest in c("phase3a_freeze_manifest.json","phase3b_freeze_manifest.json","phase4b_information_freeze_manifest.json","phase4c_information_freeze_manifest.json","phase5a_freight_freeze_manifest.json","phase5b_freight_evidence_freeze_manifest.json","phase5c_freight_dependency_freeze_manifest.json","phase6a_ecology_freeze_manifest.json","phase6b_ecological_dependency_freeze_manifest.json","phase6c_ecological_futures_freeze_manifest.json","phase7a_exposure_environmental_health_freeze_manifest.json","phase8a_biogeochemical_nutrient_flux_freeze_manifest.json","phase8b_biogeochemical_dependencies_controls_freeze_manifest.json","phase8c_biogeochemical_futures_freeze_manifest.json","phase9a_climate_natural_hazards_freeze_manifest.json","phase9b_climate_hazard_dependencies_resilience_freeze_manifest.json","phase9c_climate_hazard_futures_freeze_manifest.json")) stopifnot(file.exists(file.path(R,manifest)))
cat(sprintf("Phase 10A R validation passed: %d actors, %d authority rows, %d actor-system relationships, %d sources, %d uncertainties; Map 32 present; role-separation and prior-freeze boundary checks passed\n",nrow(actors),nrow(auth),nrow(rel),nrow(sources),nrow(unc)))
