args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)

read_table <- function(...) read.csv(..., stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
dep <- read_table(file.path(root, "data", "processed", "networks", "information_dependency_edges.csv"))
blind <- read_table(file.path(root, "data", "processed", "analysis", "information_blind_spots.csv"))
authority <- read_table(file.path(root, "data", "processed", "analysis", "decision_authority_matrix.csv"))
matrix <- read_table(file.path(root, "outputs", "figures", "information_dependency_matrix_2026.csv"))
nodes <- read_table(file.path(root, "data", "processed", "networks", "observation_system_nodes.csv"))
metadata <- readLines(file.path(root, "metadata", "sources.yml"), warn = FALSE)

stopifnot(nrow(dep) == 20, nrow(blind) == 10, nrow(authority) == 4, nrow(matrix) == 4)
stopifnot(!anyDuplicated(dep$dependency_id), !anyDuplicated(blind$blindspot_id), !anyDuplicated(authority$domain), !anyDuplicated(matrix$domain))
stopifnot(all(dep$source_node_id %in% nodes$node_id), all(dep$dependent_node_id %in% nodes$node_id))
stopifnot(all(nchar(dep$source_id) > 0), all(nchar(blind$source_id) > 0), all(nchar(authority$source_id) > 0))
for (source_id in unique(c(dep$source_id, blind$source_id, authority$source_id))) {
  stopifnot(any(grepl(paste0("^  ", source_id, ":"), metadata)))
}
stopifnot(all(dep$timeliness %in% c("real_time_or_near_real_time", "hourly_or_subdaily", "daily", "periodic", "event_driven", "unknown")))
stopifnot(all(dep$availability_requirement %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(dep$coverage %in% c("point", "local", "regional", "basin", "systemwide", "unknown")))
stopifnot(all(dep$uncertainty %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(dep$authority_level %in% c("operator", "municipal", "county", "state", "regional", "federal", "multi_agency", "unknown")))
stopifnot(all(dep$access_class %in% c("public", "partially_public", "operational_nonpublic", "unknown")))
stopifnot(all(blind$blindspot_type %in% c("spatial_coverage", "temporal_latency", "measurement_uncertainty", "model_uncertainty", "jurisdiction_boundary", "organizational_handoff", "single_source_dependency", "public_data_gap", "status_uncertainty")))
stopifnot(all(as.character(unlist(matrix[, -1])) %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(c("A", "B", "C", "D") %in% substr(dep$dependency_id, 5, 5)))
stopifnot(all(c("A", "B", "C", "D") %in% blind$affected_chain))
model_text <- paste(capture.output(print(dep)), capture.output(print(blind)), capture.output(print(authority)), collapse = " ")
stopifnot(!grepl("attack path|exploit|credential assumption|red[- ]team|surveillance[- ]state|fictional sensor|2050|2075", model_text, ignore.case = TRUE))
stopifnot(!any(grepl("trigger|automated|control", dep$dependency_role, ignore.case = TRUE)))

map_png <- file.path(root, "outputs", "maps", "systems", "15_information_dependencies_governance_2026.png")
map_svg <- file.path(root, "outputs", "maps", "systems", "15_information_dependencies_governance_2026.svg")
matrix_png <- file.path(root, "outputs", "figures", "information_dependency_matrix_2026.png")
matrix_svg <- file.path(root, "outputs", "figures", "information_dependency_matrix_2026.svg")
stopifnot(all(file.exists(c(map_png, map_svg, matrix_png, matrix_svg))))
stopifnot(all(file.info(c(map_png, map_svg, matrix_png, matrix_svg))$size > 10000))
stopifnot(any(grepl("<svg", readLines(map_svg, warn = FALSE), fixed = TRUE)))
stopifnot(any(grepl("<svg", readLines(matrix_svg, warn = FALSE), fixed = TRUE)))

validation_png <- file.path(root, "outputs", "figures", "information_dependency_R_validation.png")
png(validation_png, width = 1600, height = 900, res = 150, bg = "#f1eadc")
par(mar = c(8, 5, 4, 2), bg = "#f1eadc", fg = "#263238")
barplot(table(factor(dep$domain, levels = c("lake_erie_hab", "maumee_hydrology", "environmental_regulatory", "energy_information"))), col = c("#a8a92e", "#2d7fa6", "#4f8a72", "#c37d32"), border = NA, las = 2, ylab = "Information-dependency count", main = "Phase 4B information dependency validation")
mtext("Independent R check: 20 dependencies, 10 blind spots, four authority rows; ordinal matrix is not risk scoring", side = 1, line = 5.8, cex = 0.8)
dev.off()
cat("R Phase 4B validation passed: 20 dependencies, 10 blind spots, 4 authority rows, 4x7 matrix\n")
