args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)
read_table <- function(path) read.csv(path, stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
edges <- read_table(file.path(root, "data", "processed", "networks", "freight_dependency_edges.csv"))
register <- read_table(file.path(root, "data", "processed", "analysis", "freight_dependency_register.csv"))
modal <- read_table(file.path(root, "data", "processed", "analysis", "modal_substitutability_matrix.csv"))
matrix <- read_table(file.path(root, "outputs", "figures", "freight_dependency_matrix_2026.csv"))
freight_nodes <- read_table(file.path(root, "data", "processed", "networks", "freight_system_nodes.csv"))
energy_nodes <- read_table(file.path(root, "data", "processed", "networks", "energy_system_nodes.csv"))
metadata <- readLines(file.path(root, "metadata", "sources.yml"), warn = FALSE)

stopifnot(nrow(edges) == 20, nrow(register) == 12, nrow(modal) == 6, nrow(matrix) == 6)
stopifnot(!anyDuplicated(edges$dependency_id), !anyDuplicated(register$register_id), !anyDuplicated(modal$system_function), !anyDuplicated(matrix$system_function))
valid_nodes <- c(freight_nodes$node_id, energy_nodes$node_id)
stopifnot(all(edges$source_node_id %in% valid_nodes), all(edges$dependent_node_id %in% valid_nodes), all(register$system_node_id %in% freight_nodes$node_id))
stopifnot(all(edges$dependency_strength %in% c("low", "moderate", "high", "unknown")), all(edges$evidence_confidence %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(register$dependency_strength %in% c("low", "moderate", "high", "unknown")), all(register$evidence_confidence %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(unlist(modal[, 2:8]) %in% c("low", "moderate", "high", "unknown")), all(unlist(matrix[, 2:8]) %in% c("low", "moderate", "high", "unknown")))
stopifnot(all(edges$source_id %in% c(unique(metadata[grepl("^  ", metadata)]), edges$source_id)))
for (source_id in unique(c(edges$source_id, register$source_id))) {
  stopifnot(any(grepl(paste0("^  ", source_id, ":"), metadata)))
}
stopifnot(all(edges$relationship_basis %in% c("documented_flow", "documented_corridor", "documented_facility_access", "documented_interchange", "documented_shipment_relationship", "generalized_supply_chain", "engineering_logistics_dependency", "proximity_only", "inferred")))
stopifnot(any(edges$dependency_type == "marine_gateway_dependency"), any(edges$dependency_type == "rail_dependency"), any(edges$dependency_type == "highway_dependency"), any(edges$dependency_type == "fuel_logistics_dependency"), any(edges$dependency_type == "external_market_dependency"), any(edges$dependency_type == "interchange_dependency"))
substantive <- paste(edges$domain, edges$dependency_type, edges$dependency_strength, edges$relationship_basis, register$domain, register$dependency_classes, modal$system_function, matrix$system_function, collapse = " ")
stopifnot(!grepl("2050|2075|scenario|fictional|attack path|exploit|credential|target prioritization|SCADA|sabotage opportunity", substantive, ignore.case = TRUE))
stopifnot(!grepl("[0-9][0-9,]*[.]?[0-9]*[ ]*(tons?|trucks?|railcars?|vessels?|calls?|MW|MGD)", substantive, ignore.case = TRUE))
for (manifest in c("phase3a_freeze_manifest.json", "phase3b_freeze_manifest.json", "phase4b_information_freeze_manifest.json", "phase4c_information_freeze_manifest.json", "phase5a_freight_freeze_manifest.json", "phase5b_freight_evidence_freeze_manifest.json", "phase5a_prior_map_hashes.json")) {
  stopifnot(file.exists(file.path(root, "reports", manifest)))
}
map_files <- file.path(root, "outputs", "maps", "systems", c("19_freight_dependencies_critical_interfaces_2026.png", "19_freight_dependencies_critical_interfaces_2026.svg"))
matrix_files <- file.path(root, "outputs", "figures", c("freight_dependency_matrix_2026.png", "freight_dependency_matrix_2026.svg"))
stopifnot(all(file.exists(c(map_files, matrix_files))), all(file.info(c(map_files, matrix_files))$size > 10000))
stopifnot(any(grepl("<svg", readLines(map_files[2], warn = FALSE), fixed = TRUE)), any(grepl("<svg", readLines(matrix_files[2], warn = FALSE), fixed = TRUE)))

validation_png <- file.path(root, "outputs", "figures", "freight_dependency_R_validation.png")
png(validation_png, width = 1600, height = 900, res = 150, bg = "#f1eadc")
par(mar = c(8, 5, 4, 2), bg = "#f1eadc", fg = "#263238")
barplot(table(factor(edges$dependency_type)), col = "#7a4f92", border = NA, las = 2, ylab = "Dependency-edge count", main = "Phase 5C freight dependency validation")
mtext("Independent R check: 20 dependency edges, 12 register rows, 6x8 matrices; concentration is not vulnerability", side = 1, line = 5.8, cex = 0.8)
dev.off()
cat("R Phase 5C freight dependency validation passed: 20 edges, 12 register rows, 6x8 matrices\n")
