args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[[1]] else normalizePath(file.path(dirname(sys.frame(1)$ofile), "../../.."), mustWork=FALSE)
read_csv <- function(p) read.csv(p, stringsAsFactors=FALSE, check.names=FALSE)
d <- read_csv(file.path(root,"data/processed/networks/climate_hazard_dependency_edges.csv"))
r <- read_csv(file.path(root,"data/processed/analysis/climate_hazard_dependency_register.csv"))
c <- read_csv(file.path(root,"data/processed/analysis/climate_compound_event_register.csv"))
k <- read_csv(file.path(root,"data/processed/analysis/climate_resilience_control_register.csv"))
m <- read_csv(file.path(root,"data/processed/analysis/climate_hazard_dependency_matrix.csv"))
s <- read_csv(file.path(root,"data/processed/analysis/climate_dependency_sources.csv"))
base <- read_csv(file.path(root,"data/processed/networks/climate_hazard_nodes.csv"))
stopifnot(nrow(d)==24, nrow(r)==24, nrow(c)==9, nrow(k)==12, nrow(m)==9, nrow(s)==11)
stopifnot(length(unique(d$dependency_id))==24, length(unique(r$dependency_id))==24, length(unique(c$compound_id))==9, length(unique(k$control_id))==12)
all_source_ids <- c(s$source_id, read_csv(file.path(root,"data/processed/analysis/climate_hazard_sources.csv"))$source_id)
stopifnot(all(d$hazard_node_id %in% base$node_id), all(r$hazard_node_id %in% base$node_id), all(d$source_id %in% all_source_ids), all(r$source_id %in% all_source_ids), all(c$source_id %in% all_source_ids), all(k$source_id %in% all_source_ids))
qual <- c("strong","moderate","limited","unknown","not_applicable")
stopifnot(all(d$dependency_strength %in% qual), all(d$monitoring_strength %in% qual), all(d$warning_capacity %in% qual), all(d$spatial_certainty %in% qual), all(d$temporal_certainty %in% qual))
stopifnot(all(r$dependency_strength %in% qual), all(c$observed_or_plausible %in% c("historically_documented","physically_plausible_pathway","documented_mechanism_plus_plausible_pathway")), all(c$confidence %in% c("high","moderate","limited","unknown")))
stopifnot(all(unlist(m[,2:12]) %in% qual))
stopifnot(!grepl("2050|2075", paste(capture.output(print(d)),capture.output(print(r)),capture.output(print(c)),capture.output(print(k)),capture.output(print(m)),collapse=" ")))
map_png <- file.path(root,"outputs/maps/systems/30_climate_hazard_dependencies_resilience_2026.png"); map_svg <- file.path(root,"outputs/maps/systems/30_climate_hazard_dependencies_resilience_2026.svg"); stopifnot(file.exists(map_png),file.info(map_png)$size>1000,file.exists(map_svg),file.info(map_svg)$size>1000)
t <- tolower(paste(readLines(map_svg,warn=FALSE),collapse=" ")); for (term in c("map 30","compound pathways","heat + power","precipitation + nutrient","lake level","freeze-thaw","not routes","seiche","not ocean storm surge")) stopifnot(grepl(term,t,fixed=TRUE))
stopifnot(file.exists(file.path(root,"reports/phase9a_artifact_check.json")))
cat(sprintf("Phase 9B R validation passed: %d dependency edges, %d compound events, %d controls, %d matrix rows; Map 30 present\n",nrow(d),nrow(c),nrow(k),nrow(m)))
