args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[1] else "."
nodes <- read.csv(file.path(root,"data","processed","networks","energy_system_nodes.csv"))
edges <- read.csv(file.path(root,"data","processed","networks","energy_system_edges.csv"))
stopifnot(nrow(nodes)==18, nrow(edges)==17, length(unique(nodes$node_id))==18)
expected <- c(compute=1,generation=9,grid=2,major_load=4,storage=2)
stopifnot(all(table(nodes$node_type)[names(expected)]==expected))
stopifnot(all(edges$from_node_id %in% nodes$node_id), all(edges$to_node_id %in% nodes$node_id))
png(file.path(root,"outputs","figures","energy_system_R_validation.png"),width=1400,height=850,res=150)
par(mar=c(7,5,4,2),bg="#f2ead8")
cols <- c("#d28b23","#c2543d","#273d66","#2b7a78","#78549a")
barplot(table(nodes$node_type),las=2,col=cols,border=NA,ylab="Node count",main="Phase 3A energy / grid / compute validation")
mtext("Factual 2026 baseline; relationships are coarse and not power-flow results",side=1,line=5.5,cex=.8)
dev.off()
cat("R Phase 3A validation passed: 18 nodes, 17 edges\n")
