args <- commandArgs(trailingOnly=TRUE)
root <- if (length(args)) args[[1]] else normalizePath(file.path(dirname(sys.frame(1)$ofile), "../../.."), mustWork=FALSE)
read_csv <- function(path) read.csv(path, stringsAsFactors=FALSE, check.names=FALSE)
n <- read_csv(file.path(root,"data/processed/networks/biogeochemical_system_nodes.csv"))
e <- read_csv(file.path(root,"data/processed/networks/biogeochemical_flux_edges.csv"))
q <- read_csv(file.path(root,"data/processed/analysis/biogeochemical_quantitative_fluxes.csv"))
d <- read_csv(file.path(root,"data/processed/networks/biogeochemical_dependency_edges.csv"))
c <- read_csv(file.path(root,"data/processed/analysis/biogeochemical_control_register.csv"))
m <- read_csv(file.path(root,"data/processed/analysis/biogeochemical_dependency_matrix.csv"))
a <- read_csv(file.path(root,"data/processed/scenarios/biogeochemical_scenario_assumptions.csv"))
sn <- read_csv(file.path(root,"data/processed/scenarios/biogeochemical_nodes_scenario.csv"))
se <- read_csv(file.path(root,"data/processed/scenarios/biogeochemical_edges_scenario.csv"))
sc <- read_csv(file.path(root,"data/processed/scenarios/biogeochemical_controls_scenario.csv"))
su <- read_csv(file.path(root,"data/processed/scenarios/biogeochemical_uncertainty_scenario.csv"))
stopifnot(nrow(n)==18, nrow(e)==24, nrow(q)==10, nrow(d)==22, nrow(c)==10, nrow(m)==8)
stopifnot(nrow(a)==36, nrow(sn)==48, nrow(se)==42, nrow(sc)==48, nrow(su)==48)
stopifnot(length(unique(n$node_id))==18, length(unique(e$edge_id))==24, all(e$from_id %in% n$node_id), all(e$to_id %in% n$node_id))
stopifnot(all(sn$reality_status=="fictional"), all(se$reality_status=="fictional"), all(sc$reality_status=="fictional"))
stopifnot(all(a$scenario_id %in% c("A","B","C")), all(a$scenario_year %in% c(2050,2075)))
stopifnot(all(unlist(m[,2:11]) %in% c("strong","moderate","limited","unknown","not_applicable")))
cat(sprintf("Phase 8A-8C R validation passed: %d nodes, %d flux edges, %d quantitative records, %d dependencies, %d controls, %d scenario nodes, %d scenario edges\n",nrow(n),nrow(e),nrow(q),nrow(d),nrow(c),nrow(sn),nrow(se)))
