args <- commandArgs(trailingOnly = TRUE)
root <- if (length(args)) normalizePath(args[1], mustWork = TRUE) else normalizePath(".", mustWork = TRUE)
read_table <- function(path) read.csv(path, stringsAsFactors = FALSE, check.names = FALSE, na.strings = "")
crosswalk <- read_table(file.path(root, "data", "processed", "analysis", "freight_evidence_crosswalk.csv"))
relationships <- read_table(file.path(root, "data", "processed", "networks", "freight_evidence_relationships.csv"))
interchange <- read_table(file.path(root, "data", "processed", "analysis", "freight_interchange_matrix.csv"))
freight_nodes <- read_table(file.path(root, "data", "processed", "networks", "freight_system_nodes.csv"))
freight_edges <- read_table(file.path(root, "data", "processed", "networks", "freight_system_edges.csv"))
metadata <- readLines(file.path(root, "metadata", "sources.yml"), warn = FALSE)

stopifnot(nrow(crosswalk) == 20, nrow(relationships) == 12, nrow(interchange) == 9)
stopifnot(!anyDuplicated(crosswalk$evidence_id), !anyDuplicated(relationships$relationship_id), !anyDuplicated(interchange$interface_id))
stopifnot(all(crosswalk$phase5a_object_id %in% freight_nodes$node_id), all(relationships$phase5a_edge_id %in% freight_edges$edge_id))
valid_ids <- c(freight_nodes$node_id, "ENE-EIA-59764")
stopifnot(all(relationships$from_id %in% valid_ids), all(relationships$to_id %in% valid_ids))
classes <- c("documented_facility_access", "documented_shipment_relationship", "documented_interchange", "documented_corridor", "generalized_logistics_dependency", "proximity_only", "unresolved")
stopifnot(all(crosswalk$evidence_class %in% classes), all(relationships$evidence_class %in% classes), all(interchange$evidence_class %in% classes))
stopifnot(all(crosswalk$upgrade_status %in% c("confirmed", "strengthened", "unchanged", "downgraded", "unresolved")), all(relationships$upgrade_status %in% c("confirmed", "strengthened", "unchanged", "downgraded", "unresolved")))
stopifnot(all(nchar(crosswalk$source_id) > 0), all(nchar(relationships$source_id) > 0), all(nchar(interchange$source_id) > 0))
for (source_id in unique(c(crosswalk$source_id, relationships$source_id, interchange$source_id))) {
  stopifnot(any(grepl(paste0("^  ", source_id, ":"), metadata)))
}
stopifnot(all(crosswalk$mode %in% c("marine", "rail", "highway", "generalized", "multimodal", "pipeline")), all(relationships$mode %in% c("marine", "rail", "highway", "generalized", "multimodal", "pipeline")))
stopifnot(!grepl("2050|2075|scenario|fictional", paste(crosswalk$facility_or_corridor, crosswalk$notes, relationships$notes, interchange$notes), ignore.case = TRUE))
stopifnot(!grepl("SCADA|control architecture|attack path|exploit|credential|target prioritization", paste(crosswalk$notes, relationships$notes, interchange$notes), ignore.case = TRUE))
stopifnot(file.exists(file.path(root, "reports", "phase5a_freight_freeze_manifest.json")))
stopifnot(file.exists(file.path(root, "reports", "phase5a_prior_map_hashes.json")))
map_files <- file.path(root, "outputs", "maps", "systems", c("18_freight_evidence_interchange_2026.png", "18_freight_evidence_interchange_2026.svg"))
stopifnot(all(file.exists(map_files)), all(file.info(map_files)$size > 10000))
stopifnot(any(grepl("<svg", readLines(map_files[2], warn = FALSE), fixed = TRUE)))

validation_png <- file.path(root, "outputs", "figures", "freight_evidence_R_validation.png")
png(validation_png, width = 1600, height = 900, res = 150, bg = "#f1eadc")
par(mar = c(8, 5, 4, 2), bg = "#f1eadc", fg = "#263238")
barplot(table(factor(crosswalk$evidence_class, levels = classes)), col = "#1c6f83", border = NA, las = 2, ylab = "Evidence-record count", main = "Phase 5B freight evidence validation")
mtext("Independent R check: 20 evidence records, 12 strengthened relationships, 9 interchange interfaces; no quantities or routes", side = 1, line = 5.8, cex = 0.8)
dev.off()
cat("R Phase 5B freight evidence validation passed: 20 crosswalk records, 12 relationships, 9 interchange rows\n")
