"""Build the bounded Phase 7A 2026 exposure-context baseline and Map 23."""
from pathlib import Path
import hashlib,json
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch
ROOT=Path(__file__).resolve().parents[3]; N=ROOT/'data/processed/networks'; A=ROOT/'data/processed/analysis'; M=ROOT/'outputs/maps/systems'; R=ROOT/'reports'
SOURCES=['toledo_water','ohio_epa_hab','noaa_hab','epa_lake_erie','epa_aqs','ohio_epa_air','michigan_air','usace_luckey_2026','usace_luckey_groundwater_2026','ohio_fish_advisories','ohio_recreational_water','nws_heat','noaa_climate','usgs_3dhp_all','glos_intake']
receptors=['water_system_users','residential_population','workers','outdoor_workers','fish_consumers','recreational_users','general_public']
node_cols=['node_id','name','node_type','pathway_family','environmental_medium','status','receptor_context','latitude','longitude','source_id','confidence','notes']
nodes=[]
def node(i,name,typ,fam,med,status,rec,lat='',lon='',src='epa_lake_erie',conf='moderate',notes=''): nodes.append([i,name,typ,fam,med,status,rec,lat,lon,src,conf,notes])
node('EXP-001','Lake Erie source-water / HAB condition','environmental_condition','drinking_water_hab','surface_water','environmental_presence','water_system_users','41.75','-83.20','noaa_hab','high','Source-water condition; not finished-water quality or personal exposure.')
node('EXP-002','Toledo water intake context','hazard_source','drinking_water_hab','surface_water','potential_pathway','water_system_users','41.70','-83.35','glos_intake','moderate','Coordinate discrepancy unresolved; coordinate is contextual and not adopted as sole intake location.')
node('EXP-003','Collins Park treatment / control','treatment_or_control','drinking_water_hab','finished_water','controlled_pathway','water_system_users','41.68','-83.48','toledo_water','high','Treatment/control interface; no cyanotoxin dose inferred.')
node('EXP-004','HAB and drinking-water monitoring','monitoring_network','drinking_water_hab','surface_water','monitoring_control','water_system_users','','','ohio_epa_hab','high','Monitoring supports control and advisory decisions, not human exposure confirmation.')
node('EXP-005','Ambient PM2.5 / ozone context','environmental_condition','ambient_air','ambient_air','environmental_presence','general_public','','','epa_aqs','moderate','Regional monitoring context; no plume or facility attribution.')
node('EXP-006','EPA AQS / AirData network','monitoring_network','ambient_air','ambient_air','monitoring_control','general_public','','','epa_aqs','high','Public ambient observations and regulatory interpretation.')
node('EXP-007','Ohio / Michigan air monitoring context','monitoring_network','ambient_air','ambient_air','monitoring_control','general_public','','','ohio_epa_air','moderate','Geographically relevant state monitoring context; coverage is not uniform.')
node('EXP-008','Luckey documented legacy contamination','legacy_site','legacy_contamination','soil_groundwater','environmental_presence','workers','','','usace_luckey_2026','high','Documented contamination and remediation; no receptor-reaching plume asserted.')
node('EXP-009','Luckey groundwater monitoring / remedy','monitoring_network','legacy_contamination','groundwater','controlled_pathway','workers','','','usace_luckey_groundwater_2026','high','Onsite well exceedances and sampled residential-well result are source-qualified; no individual exposure finding.')
node('EXP-010','Luckey remediation controls','treatment_or_control','legacy_contamination','soil_groundwater','monitoring_control','workers','','','usace_luckey_2026','high','Excavation, water treatment, dust controls, and institutional controls.')
node('EXP-011','Fish-consumption advisory system','advisory_system','food_fish_recreation','fish','advisory_context','fish_consumers','','','ohio_fish_advisories','high','Advisory context does not establish individual consumption or harm.')
node('EXP-012','Western Lake Erie fish context','environmental_condition','food_fish_recreation','fish','environmental_presence','fish_consumers','41.75','-83.15','epa_lake_erie','moderate','Environmental/fishery context; no consumption assumed.')
node('EXP-013','Recreational-water monitoring / advisory','monitoring_network','food_fish_recreation','recreational_water','advisory_context','recreational_users','','','ohio_recreational_water','high','Monitoring and advisory system; no individual recreation assumed.')
node('EXP-014','Heat and humidity conditions','environmental_condition','heat','ambient_air','environmental_presence','general_public','','','nws_heat','high','Broad meteorological stress context; no heat dose or illness model.')
node('EXP-015','NWS heat warning / observation system','monitoring_network','heat','ambient_air','monitoring_control','general_public','','','nws_heat','high','Warnings and observations support general protective action.')
node('EXP-016','Outdoor-work context','receptor_context','heat','ambient_air','potential_pathway','outdoor_workers','','','nws_heat','moderate','Generic receptor only; no individual worksite or outcome.')
node('EXP-017','Residential population context','receptor_context','ambient_air','ambient_air','potential_pathway','residential_population','','','epa_aqs','limited','Generic population context; no residence-level exposure or risk score.')
node('EXP-018','Water-system users context','receptor_context','drinking_water_hab','finished_water','potential_pathway','water_system_users','','','toledo_water','moderate','Generic users only; source and finished water remain distinct.')
node('EXP-019','Recreational users context','receptor_context','food_fish_recreation','recreational_water','potential_pathway','recreational_users','','','ohio_recreational_water','moderate','Generic users only; use is not assumed.')
node('EXP-020','Workers context','receptor_context','legacy_contamination','soil_groundwater','potential_pathway','workers','','','usace_luckey_2026','moderate','Generic site/work context; no individual exposure or illness.')
edge_cols=['edge_id','from_node_id','to_node_id','relationship_type','pathway_family','exposure_status','evidence_type','source_id','confidence','notes']
edges=[]
def edge(i,f,t,rel,fam,status,ev,src,conf,notes): edges.append([i,f,t,rel,fam,status,ev,src,conf,notes])
edge('E-001','EXP-001','EXP-004','monitored_by','drinking_water_hab','environmental_presence','environmental_evidence','noaa_hab','high','Source-water condition is monitored; this does not confirm exposure.')
edge('E-002','EXP-004','EXP-003','information_supports_control','drinking_water_hab','controlled_pathway','monitoring_control','ohio_epa_hab','high','Monitoring informs treatment/control decisions.')
edge('E-003','EXP-003','EXP-018','control_reduces_pathway','drinking_water_hab','controlled_pathway','institutional_control','toledo_water','high','Finished-water treatment is distinct from source-water condition; no dose inferred.')
edge('E-004','EXP-001','EXP-002','present_in','drinking_water_hab','potential_pathway','environmental_evidence','noaa_hab','high','Lake/source context reaches intake interface conceptually; intake coordinate remains unresolved.')
edge('E-005','EXP-005','EXP-006','monitored_by','ambient_air','environmental_presence','environmental_evidence','epa_aqs','high','Ambient measurements support condition interpretation, not personal dose.')
edge('E-006','EXP-006','EXP-007','regulated_by','ambient_air','monitoring_control','regulatory_evidence','ohio_epa_air','moderate','State and federal monitoring/regulatory interfaces are represented without uniform coverage claim.')
edge('E-007','EXP-005','EXP-017','potential_exposure_pathway','ambient_air','potential_pathway','environmental_evidence','epa_aqs','limited','Generic inhalation context only; no proximity or dose inference.')
edge('E-008','EXP-008','EXP-009','monitored_by','legacy_contamination','environmental_presence','environmental_evidence','usace_luckey_groundwater_2026','high','Documented contamination is monitored; not documented individual exposure.')
edge('E-009','EXP-008','EXP-010','treated_by','legacy_contamination','controlled_pathway','institutional_control','usace_luckey_2026','high','Remediation/control is documented; no plume drawn.')
edge('E-010','EXP-009','EXP-020','potential_exposure_pathway','legacy_contamination','potential_pathway','environmental_evidence','usace_luckey_groundwater_2026','moderate','Receptor context is generic; sampled residential well result does not establish individual exposure.')
edge('E-011','EXP-012','EXP-011','advisory_for','food_fish_recreation','advisory_context','advisory_evidence','ohio_fish_advisories','high','Advisory translates environmental/fish evidence into generic consumption guidance.')
edge('E-012','EXP-011','EXP-019','advisory_for','food_fish_recreation','advisory_context','advisory_evidence','ohio_fish_advisories','moderate','No actual consumption or documented harm inferred.')
edge('E-013','EXP-013','EXP-019','advisory_for','food_fish_recreation','advisory_context','monitoring_control','ohio_recreational_water','high','Recreational-water monitoring/advisory interface; no individual use assumed.')
edge('E-014','EXP-014','EXP-015','monitored_by','heat','environmental_presence','meteorological_evidence','nws_heat','high','Observation/warning system supports public guidance.')
edge('E-015','EXP-015','EXP-016','information_supports_control','heat','controlled_pathway','advisory_evidence','nws_heat','high','Generic outdoor-worker context; no heat dose or illness.')
edge('E-016','EXP-014','EXP-016','potential_exposure_pathway','heat','potential_pathway','meteorological_evidence','nws_heat','moderate','Environmental stress context is not individual dose.')
edge('E-017','EXP-014','EXP-018','receptor_context','heat','potential_pathway','meteorological_evidence','nws_heat','limited','General public context only; no outcome model.')
edge('E-018','EXP-001','EXP-018','receptor_context','drinking_water_hab','potential_pathway','environmental_evidence','toledo_water','moderate','Potential system-user context; source/finished water distinction retained.')
edge('E-019','EXP-012','EXP-013','monitored_by','food_fish_recreation','environmental_presence','environmental_evidence','epa_lake_erie','moderate','Broad lake condition informs fish/recreation monitoring; no direct individual exposure.')
edge('E-020','EXP-008','EXP-020','receptor_context','legacy_contamination','potential_pathway','environmental_evidence','usace_luckey_2026','moderate','Historical/current site context does not establish a receptor-reaching pathway.')
path_cols=['pathway_id','pathway_family','hazard_stressor','environmental_medium','potential_pathway','receptor_context','monitoring_control_advisory','exposure_status','documented_exposure','dose_status','health_outcome_status','source_id','confidence','notes']
paths=[['P-01','Drinking Water / HAB','HAB/source-water condition','surface_water → finished_water','source water to intake and treatment interface','water_system_users','Ohio EPA/NOAA monitoring; City of Toledo treatment','controlled_pathway','false','unknown','unknown','noaa_hab','high','Source-water and finished-water condition are distinct; no cyanotoxin dose or harm inferred.'],['P-02','Ambient Air','PM2.5/ozone and supported criteria pollutants','ambient_air','ambient condition to generic inhalation context','residential_population;general_public','EPA AQS/AirData and state monitoring/regulatory interpretation','potential_pathway','false','unknown','unknown','epa_aqs','moderate','No plume, facility assignment, personal concentration, dose, or causation.'],['P-03','Soil / Groundwater / Legacy Contamination','Luckey legacy contaminants','soil_groundwater','contamination/remediation and generic site/work context','workers','USACE monitoring, remediation, dust/water controls, land-use controls','controlled_pathway','false','unknown','unknown','usace_luckey_2026','high','Documented contamination/remediation; no individual exposure, illness, or receptor-reaching plume.'],['P-04','Food / Fish / Recreational Water','fish/environmental condition','fish;recreational_water','condition to fish advisory or recreation advisory','fish_consumers;recreational_users','Ohio fish advisory and recreational-water monitoring/advisory systems','advisory_context','false','unknown','unknown','ohio_fish_advisories','high','Advisory is not proof of consumption, dose, or harm.'],['P-05','Heat','heat/humidity','ambient_air','meteorological stress to generic outdoor/general-public context','outdoor_workers;general_public','NWS observations and warnings','potential_pathway','false','unknown','unknown','nws_heat','high','No individual heat dose, heat illness, mortality, or future climate scenario.']]
mat_cols=['pathway_family','hazard_observation','environmental_monitoring','regulatory_standard','treatment_or_control','public_advisory','spatial_coverage','temporal_coverage','exposure_confirmation','health_outcome_linkage','notes']
matrix=[['Drinking Water / HAB','strong','strong','strong','strong','strong','moderate','moderate','unknown','unknown','Strong monitoring/control does not mean high exposure.'],['Ambient Air','moderate','strong','strong','not_applicable','moderate','moderate','moderate','unknown','unknown','Limited spatial coverage is not a risk score.'],['Soil / Groundwater / Legacy Contamination','strong','strong','strong','strong','limited','limited','moderate','unknown','unknown','Luckey evidence supports contamination/remediation, not individual exposure.'],['Food / Fish / Recreational Water','moderate','moderate','moderate','not_applicable','strong','moderate','moderate','unknown','unknown','Advisories provide context, not documented consumption or harm.'],['Heat','strong','strong','not_applicable','moderate','strong','moderate','strong','unknown','unknown','Warnings and observations are not dose or illness evidence.']]
cross_cols=['crosswalk_id','pathway','claim','source','evidence_type','supports','does_not_support','confidence','status','notes']
cross=[]
def cw(i,p,c,s,e,sup,not_,conf,status,n): cross.append([i,p,c,s,e,sup,not_,conf,status,n or 'Claim boundary is limited to the stated evidence.'])
cw('C-001','Drinking Water / HAB','Western Lake Erie HAB/source-water conditions are monitored','NOAA HAB forecast; Ohio EPA HAB','environmental evidence','source-water condition and monitoring context','finished-water concentration, exposure, dose, illness','high','environmental_presence','')
cw('C-002','Drinking Water / HAB','Toledo treatment is a control interface','City of Toledo Water Treatment','institutional control','treatment/control context','effective personal dose or harm','high','controlled_pathway','')
cw('C-003','Ambient Air','EPA AQS provides public ambient observations','EPA AQS/AirData','environmental evidence','monitoring and regulatory interpretation','facility plume, personal concentration, dose, illness','high','monitoring_control','')
cw('C-004','Ambient Air','Ohio/Michigan stations provide geographically relevant context','Ohio EPA; Michigan EGLE air monitoring','environmental evidence','state monitoring context','uniform regional coverage or causation','moderate','monitoring_control','')
cw('C-005','Legacy Contamination','Luckey contamination and remediation are documented','USACE Luckey Site','environmental evidence','soil/groundwater legacy and cleanup','individual exposure, illness, plume','high','environmental_presence','')
cw('C-006','Legacy Contamination','Luckey groundwater monitoring includes onsite exceedances and sampled residential result','USACE Fall 2025 groundwater release','environmental evidence','monitoring distinction between onsite and sampled residential well','documented individual exposure or dose','high','monitoring_control','')
cw('C-007','Food / Fish','Ohio fish advisories provide consumption guidance','Ohio EPA/ODH fish advisories','advisory evidence','generic consumption advisory context','actual consumption, dose, harm','high','advisory_context','')
cw('C-008','Recreational Water','Ohio recreational-water monitoring supports advisories','Ohio EPA recreational water','monitoring/advisory evidence','generic recreation context','individual recreation or illness','moderate','advisory_context','')
cw('C-009','Heat','NWS warnings/observations identify heat stress conditions','NWS heat products','meteorological evidence','environmental stress and protective guidance','individual dose, illness, mortality','high','environmental_presence','')
cw('C-010','All pathways','No included source demonstrates an actual individual exposure','Phase 2C and Phase 7A evidence review','evidence gap','absence of documented exposure claim in package','proof that no person was ever exposed','moderate','unknown','This is a scope/evidence statement, not a population study.')
unc_cols=['uncertainty_id','pathway_family','category','issue','effect_on_interpretation','status','source_id','confidence','notes']
unc=[['U-001','Drinking Water / HAB','spatial_uncertainty','Toledo intake coordinates differ across public sources','Intake map context remains qualified; no coordinate selected as definitive','open','glos_intake','high','Preserve unresolved discrepancy.'],['U-002','Drinking Water / HAB','pathway_uncertainty','Source-water observations do not equal finished-water condition','Potential pathway is not exposure confirmation','open','toledo_water','high','Treatment is represented separately.'],['U-003','Ambient Air','spatial_uncertainty','Station coverage is not a continuous regional field','No plume or neighborhood assignment','open','epa_aqs','high','Point monitoring only.'],['U-004','Ambient Air','dose_unknown','Ambient concentration is not personal inhaled dose','No dose inference','open','epa_aqs','high',''],['U-005','Legacy Contamination','pathway_uncertainty','No receptor-reaching plume is established','Luckey remains contamination/remediation context','open','usace_luckey_groundwater_2026','high',''],['U-006','Legacy Contamination','receptor_uncertainty','Generic workers/site users are not identified individuals','No documented exposure relationship','open','usace_luckey_2026','high',''],['U-007','Food / Fish','receptor_uncertainty','Actual consumption is not observed','Advisory context only','open','ohio_fish_advisories','high',''],['U-008','Recreational Water','receptor_uncertainty','Actual recreational use is not observed','Advisory context only','open','ohio_recreational_water','moderate',''],['U-009','Heat','temporal_uncertainty','2026 conditions vary by day and warning period','Broad baseline, not a continuous dose series','open','nws_heat','high',''],['U-010','Heat','health_outcome_unknown','No health outcomes are modeled','No illness or mortality claim','open','nws_heat','high',''],['U-011','All pathways','source_uncertainty','Public sources differ in detail and refresh timing','Confidence remains source-qualified','managed','epa_aqs','moderate',''],['U-012','All pathways','monitoring_gap','Exposure confirmation is not a product of these monitoring systems','No documented exposure relationships','open','epa_lake_erie','high',''],['U-013','All pathways','status_uncertainty','Advisory status changes over time','Rows are a 2026 context snapshot','open','ohio_fish_advisories','moderate','Advisory timing is a bounded snapshot, not a permanent status.']]
for row in cross: row[-1]=row[-1] or 'Claim boundary is limited to the stated evidence.'
for row in unc: row[-1]=row[-1] or 'Uncertainty is retained rather than resolved by inference.'
def write(df,path,cols): path.parent.mkdir(parents=True,exist_ok=True); df.to_csv(path,index=False,columns=cols)
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def render():
 fig=plt.figure(figsize=(16,10),facecolor='#f3eee3'); ax=fig.add_axes([.04,.17,.56,.75],facecolor='#e7dfcd')
 ax.set_xlim(-84.5,-82.5); ax.set_ylim(40.9,42.2); ax.add_patch(plt.Rectangle((-84.5,41.65),2,.55,color='#b6dce2',alpha=.8)); ax.plot([-83.7,-83.3,-82.9],[41.1,41.45,41.7],color='#4e8ba0',lw=3,alpha=.7); ax.plot([-83.4,-83.1], [41.6,41.72], 'o',color='#614a87',ms=9); ax.text(-83.25,41.78,'Toledo / intake context',fontsize=8); ax.plot(-83.48,41.68,'s',color='#b45d3b',ms=8); ax.text(-83.48,41.63,'treatment',fontsize=8,ha='center'); ax.plot(-83.48,41.42,'D',color='#995a35',ms=8); ax.text(-83.48,41.37,'Luckey',fontsize=8,ha='center'); ax.scatter([-83.0,-83.8,-82.8],[41.85,41.15,41.5],marker='^',color='#327b72',s=55); ax.text(-83.0,41.91,'HAB/fish/recreation context',fontsize=8); ax.text(-83.78,41.08,'air / heat monitoring context',fontsize=8); ax.axis('off'); ax.set_title('MAP 23 — ENVIRONMENTAL EXPOSURE CONTEXT, 2026',loc='left',fontsize=14,weight='bold',color='#17384b',pad=8)
 side=fig.add_axes([.64,.06,.33,.87]); side.axis('off'); side.text(.02,.98,'FIVE PATHWAY FAMILIES',va='top',fontsize=13,weight='bold',color='#17384b'); ys=[.91,.82,.73,.64,.55]; labels=['Drinking Water / HAB','Ambient Air','Soil / Groundwater / Legacy Contamination','Food / Fish / Recreational Water','Heat / Climate-Sensitive Stress']; colors=['#614a87','#4c7f9b','#995a35','#327b72','#c28b32']
 for y,l,c in zip(ys,labels,colors): side.text(.04,y,'●  '+l,fontsize=9,color=c,weight='bold'); side.text(.09,y-.035,'condition → medium → potential pathway → generic receptor → monitoring/control',fontsize=7.5,color='#444')
 side.text(.02,.43,'SYSTEM CHAIN',fontsize=11,weight='bold',color='#17384b'); chain=['HAZARD / STRESSOR','ENVIRONMENTAL MEDIUM','POTENTIAL PATHWAY','RECEPTOR CONTEXT','MONITORING / CONTROL / ADVISORY']; y=.39
 for i,x in enumerate(chain): side.text(.08,y,x,fontsize=8.5,weight='bold',color='#444',bbox=dict(boxstyle='round,pad=.25',fc='#e7dfcd',ec='#b5a992')); y-=.047
 side.text(.02,.13,'BOUNDARIES',fontsize=11,weight='bold',color='#17384b'); side.text(.04,.10,'Environmental presence ≠ exposure ≠ dose ≠ illness\nAdvisory ≠ documented harm. No personal data, plume, exposure zone, health-risk score, vector/infectious disease, or future health scenario. Great Black Swamp: C — HOLD. Toledo intake discrepancy: UNRESOLVED.',fontsize=7.8,color='#444',va='top',linespacing=1.35)
 fig.savefig(M/'23_environmental_exposure_context_2026.png',dpi=220,bbox_inches='tight'); plt.rcParams['svg.fonttype']='none'; fig.savefig(M/'23_environmental_exposure_context_2026.svg',bbox_inches='tight',metadata={'Date':None}); svg=M/'23_environmental_exposure_context_2026.svg'; svg.write_text('\n'.join(line.rstrip() for line in svg.read_text(encoding='utf-8').splitlines())+'\n',encoding='utf-8'); plt.close(fig)
def main():
 write(pd.DataFrame(nodes,columns=node_cols),N/'exposure_context_nodes.csv',node_cols); write(pd.DataFrame(edges,columns=edge_cols),N/'exposure_pathway_edges.csv',edge_cols); write(pd.DataFrame(paths,columns=path_cols),A/'exposure_pathway_register.csv',path_cols); write(pd.DataFrame(matrix,columns=mat_cols),A/'environmental_health_monitoring_matrix.csv',mat_cols); write(pd.DataFrame(cross,columns=cross_cols),A/'exposure_evidence_crosswalk.csv',cross_cols); write(pd.DataFrame(unc,columns=unc_cols),A/'exposure_uncertainty_register.csv',unc_cols); render()
 arts=[N/'exposure_context_nodes.csv',N/'exposure_pathway_edges.csv',A/'exposure_pathway_register.csv',A/'environmental_health_monitoring_matrix.csv',A/'exposure_evidence_crosswalk.csv',A/'exposure_uncertainty_register.csv',M/'23_environmental_exposure_context_2026.png',M/'23_environmental_exposure_context_2026.svg']
 man={'phase':'7A','status':'exposure_context_baseline','counts':{'nodes':len(nodes),'edges':len(edges),'pathway_register':len(paths),'monitoring_matrix_rows':len(matrix),'monitoring_matrix_dimensions':[len(matrix),len(mat_cols)-1],'evidence_crosswalk':len(cross),'uncertainty_register':len(unc)},'artifacts':{str(p.relative_to(ROOT)).replace('\\','/'):sha(p) for p in arts}}; (R/'exposure_context_manifest.json').write_text(json.dumps(man,indent=2)+'\n'); print(json.dumps(man['counts'],indent=2))
if __name__=='__main__': main()
