"""Build separate qualitative Phase 7C environmental-health futures."""
from pathlib import Path
import csv,json,hashlib
ROOT=Path(__file__).resolve().parents[3]; S=ROOT/'data/processed/scenarios'; M=ROOT/'outputs/maps/systems'; F=ROOT/'outputs/figures'; R=ROOT/'reports'
P=[('P-01','Drinking Water / HAB'),('P-02','Ambient Air'),('P-03','Legacy Contamination'),('P-04','Food / Fish / Recreational Water'),('P-05','Heat')]
ST=[('A',2050,'Preventive Environmental Health Infrastructure'),('A',2075,'Preventive Environmental Health Infrastructure'),('B',2050,'Managed Exposure Landscape'),('B',2075,'Managed Exposure Landscape'),('C',2050,'Compound Environmental Stress'),('C',2075,'Compound Environmental Stress')]
def wr(path,fields,rows):
 path.parent.mkdir(parents=True,exist_ok=True)
 with path.open('w',newline='',encoding='utf-8') as f: w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def main():
 af=['assumption_id','scenario_id','scenario_year','pathway_family','assumption','driver','basis','source_id','plausibility','uncertainty','dependency','status','notes']; assumptions=[]
 drivers={'A':'proactive civic infrastructure, integration, adaptation','B':'targeted controls in a working landscape','C':'compound stress and constrained institutions'}
 for si,(sc,y,name) in enumerate(ST,1):
  for j,(pid,p) in enumerate(P,1): assumptions.append(dict(zip(af,[f'EA-{si:02}-{j:02}',sc,y,p,f'{p} follows the {sc} institutional pathway at {y}; monitoring and control states evolve qualitatively.','environmental conditions and institutional capacity',drivers[sc],'noaa_climate','high' if sc=='A' else 'moderate' if sc=='B' else 'exploratory','moderate','monitoring/control capacity','scenario','No exposure, dose, or illness is implied.'])))
 for si,(sc,y,name) in enumerate(ST,1): assumptions.append(dict(zip(af,[f'EA-{si:02}-06',sc,y,'All pathways','Institutional data integration and public information evolve with the scenario.','institutional capacity',drivers[sc],'noaa_climate','moderate','moderate','data and maintenance','scenario','Qualitative scenario premise; no probability.'])))
 wr(S/'environmental_health_scenario_assumptions.csv',af,assumptions)
 nf=['scenario_id','scenario_year','pathway_family','baseline_object_id','change_type','state','reality_status','relationship_basis','assumption_id','plausibility','source_or_basis','notes']; nodes=[]
 for si,(sc,y,name) in enumerate(ST,1):
  for j,(pid,p) in enumerate(P,1):
   ct='monitoring_expanded' if sc=='A' else 'persist' if sc=='B' else 'monitoring_reduced'; state='monitoring and control capacity is strengthened' if sc=='A' else 'managed controls persist with heterogeneous capacity' if sc=='B' else 'control dependence and evidence gaps increase'; nodes.append(dict(zip(nf,[sc,y,p,pid,ct,state,'fictional','scenario delta over validated 2026 baseline',f'EA-{si:02}-{j:02}','high' if sc=='A' else 'moderate' if sc=='B' else 'exploratory','Phase 7C scenario basis','Does not assert exposure or dose.'])))
 wr(S/'exposure_nodes_scenario.csv',nf,nodes)
 ef=['scenario_id','scenario_year','pathway_family','baseline_object_id','change_type','state','assumption_id','plausibility','relationship_basis','notes']; edges=[]
 for si,(sc,y,name) in enumerate(ST,1):
  for j,(pid,p) in enumerate(P,1): edges.append(dict(zip(ef,[sc,y,p,pid,'control_strengthened' if sc=='A' else 'persist' if sc=='B' else 'uncertainty_increased','condition → monitoring → control remains a qualitative dependency chain',f'EA-{si:02}-{j:02}','high' if sc=='A' else 'moderate' if sc=='B' else 'exploratory','scenario relationship; not an exact route','No exposure magnitude or disease outcome.'])))
 wr(S/'exposure_edges_scenario.csv',ef,edges)
 cf=['scenario_id','scenario_year','pathway_family','baseline_control_id','change_type','state','assumption_id','plausibility','notes']; ctr=[]; uf=['scenario_id','scenario_year','pathway_family','baseline_uncertainty','change_type','state','assumption_id','plausibility','notes']; unc=[]
 for si,(sc,y,name) in enumerate(ST,1):
  for j,(pid,p) in enumerate(P,1):
   ctr.append(dict(zip(cf,[sc,y,p,f'CTL-{((j-1)%7)+1:03}','strengthened' if sc=='A' else 'persists' if sc=='B' else 'weakened', 'preventive capacity expands' if sc=='A' else 'targeted management continues' if sc=='B' else 'reliance and burden increase',f'EA-{si:02}-{j:02}','high' if sc=='A' else 'moderate' if sc=='B' else 'exploratory','Qualitative control evolution; no efficiency claim.'])))
   unc.append(dict(zip(uf,[sc,y,p,'receptor contact, spatial coverage, and temporal evidence', 'reduced' if sc=='A' else 'persists' if sc=='B' else 'increased','uncertainty is reduced through integration' if sc=='A' else 'uncertainty remains heterogeneous' if sc=='B' else 'evidence gaps and burden expand',f'EA-{si:02}-{j:02}','high' if sc=='A' else 'moderate' if sc=='B' else 'exploratory','Does not create documented exposure.'])))
 wr(S/'exposure_controls_scenario.csv',cf,ctr);wr(S/'exposure_uncertainty_scenario.csv',uf,unc)
 dims=['monitoring_capacity','treatment_capacity','remediation_capacity','advisory_capacity','pathway_control','institutional_capacity','data_integration','public_information','heat_adaptation','water_resilience','uncertainty','control_dependence']; comp=[]
 for sc,y,name in ST:
  level='high' if sc=='A' else 'moderate' if sc=='B' else 'low'; comp.append({'scenario_id':sc+str(y),'scenario':name,'scenario_year':y,**{d:level for d in dims}})
 wr(F/'environmental_health_scenarios_comparison.csv',list(comp[0]),comp)
 for title,year,file in [('25_environmental_health_futures_2050',2050,'25_environmental_health_futures_2050'),('25b_environmental_health_futures_2075',2075,'25b_environmental_health_futures_2075')]: mapit(file,year)
 import matplotlib; matplotlib.use('Agg'); import matplotlib.pyplot as plt
 fig,ax=plt.subplots(figsize=(12,5)); ax.axis('off'); ax.set_facecolor('#101820');fig.patch.set_facecolor('#101820'); ax.set_title('ENVIRONMENTAL HEALTH SCENARIO COMPARISON — QUALITATIVE STATES',color='white',weight='bold'); ax.table(cellText=[[r['scenario_id'],r['scenario'],r['monitoring_capacity'],r['pathway_control'],r['institutional_capacity'],r['uncertainty']] for r in comp],colLabels=['State','Scenario','Monitoring','Control','Institutional capacity','Uncertainty'],loc='center',cellLoc='left'); fig.savefig(F/'environmental_health_scenarios_comparison.png',dpi=160,bbox_inches='tight',facecolor=fig.get_facecolor());plt.close(fig)
 for name,text in {'environmental_health_scenario_sources.md':'# Scenario Sources\n\nPhase 7C uses the validated Phase 7B baseline and general plausibility anchors from NOAA climate information, NWS heat guidance, EPA/Ohio EPA monitoring and resilience programs, USACE remediation context, and public water/advisory guidance. This is not an exhaustive health literature review.\n','environmental_health_scenario_assumptions.md':'# Scenario Assumptions\n\nA is preventive infrastructure; B is managed coexistence; C is compound stress. These are alternatives, not forecasts or probabilities. 2026 remains factual; future rows are fictional scenario deltas.\n','environmental_health_scenario_consistency.md':'# Scenario Consistency\n\nAll six states carry scenario/year and remain outside factual Phase 7A/7B tables. Toledo intake discrepancy remains unresolved; Luckey remains documented contamination/remediation without individual exposure; Great Black Swamp remains C — HOLD.\n','environmental_health_future_worldbuilding.md':'# Environmental Health Future Worldbuilding\n\nSpeculative themes include treatment plants as civic defense, advisories as governance, remediation as institutional memory, heat adaptation in public-space design, and data legitimacy. None implies future exposure, dose, illness, or disease.\n','environmental_health_scenario_qa.md':'# Scenario QA\n\nScenario objects are qualitative and separate. Maps 25/25b show divergence in monitoring, controls, institutional capacity, and uncertainty, not exposure magnitude or health outcomes.\n'}.items(): (R/name).write_text(text,encoding='utf-8')
 manifest={'phase':'7C','counts':{'assumptions':len(assumptions),'scenario_nodes':len(nodes),'scenario_edges':len(edges),'control_states':len(ctr),'uncertainty_states':len(unc),'comparison_rows':len(comp)},'artifacts':{}}
 for p in [S/'environmental_health_scenario_assumptions.csv',S/'exposure_nodes_scenario.csv',S/'exposure_edges_scenario.csv',S/'exposure_controls_scenario.csv',S/'exposure_uncertainty_scenario.csv',F/'environmental_health_scenarios_comparison.csv',F/'environmental_health_scenarios_comparison.png',M/'25_environmental_health_futures_2050.png',M/'25_environmental_health_futures_2050.svg',M/'25b_environmental_health_futures_2075.png',M/'25b_environmental_health_futures_2075.svg'] : manifest['artifacts'][str(p.relative_to(ROOT)).replace('\\','/')]=hashlib.sha256(p.read_bytes()).hexdigest()
 (R/'environmental_health_scenario_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
def mapit(file,year):
 import matplotlib;matplotlib.use('Agg');import matplotlib.pyplot as plt
 matplotlib.rcParams['svg.fonttype']='none';fig,axs=plt.subplots(1,3,figsize=(15,6));fig.patch.set_facecolor('#101820')
 for ax,(sc,_,name) in zip(axs,[x for x in ST if x[1]==year]):
  ax.set_facecolor('#172431');ax.axis('off');ax.set_title(f'{sc} — {name}',color='white',fontsize=10,weight='bold'); lines=['2026 FACTUAL ANCHOR','environmental condition','pathway opportunity','monitoring / information','controls / advisories','institutional capacity','uncertainty']
  for i,t in enumerate(lines): ax.text(.08,.86-i*.11,t,color=['#9cc9ef','#f0b35a','#f0b35a','#70c7a1','#b58be8','#f18f8f','#f4e66b'][i],fontsize=9,transform=ax.transAxes)
  ax.text(.08,.08,'Qualitative scenario delta\nNo exposure, dose, illness, probability,\nplume, or vector/disease content.',color='#d6dee5',fontsize=8,transform=ax.transAxes)
 fig.suptitle(f'MAP {"25" if year==2050 else "25b"} — ENVIRONMENTAL HEALTH FUTURES, {year}',color='white',fontsize=16,weight='bold');fig.savefig(M/(file+'.png'),dpi=160,bbox_inches='tight',facecolor=fig.get_facecolor());fig.savefig(M/(file+'.svg'),bbox_inches='tight',facecolor=fig.get_facecolor());plt.close(fig);p=M/(file+'.svg');p.write_text('\n'.join(x.rstrip() for x in p.read_text(encoding='utf-8').splitlines())+'\n',encoding='utf-8')
if __name__=='__main__':main()
